package ch.metzenthin.svm.ui.components;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemListener;

/**
 * @author hans
 */
public class AngehoerigerPanel {
    private JPanel panel;
    private NameAdressePanel nameAdressePanel;
    private AdresseCheckboxPanel adresseCheckboxPanel;

    public void addRechnungsempfaengerAdresseItemListener(ItemListener listener) {
        adresseCheckboxPanel.addRechnungsempfaengerAdresseItemListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel.add(panel1, BorderLayout.CENTER);
        nameAdressePanel = new NameAdressePanel();
        panel1.add(nameAdressePanel.$$$getRootComponent$$$(), BorderLayout.NORTH);
        adresseCheckboxPanel = new AdresseCheckboxPanel();
        panel1.add(adresseCheckboxPanel.$$$getRootComponent$$$(), BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
