package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.domain.model.AngehoerigerEinEintragPasstResult;
import ch.metzenthin.svm.domain.model.SchuelerErfassenModel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class AngehoerigerEinEintragPasstDialog extends SchuelerErfassenDialog {
    private final AngehoerigerEinEintragPasstResult angehoerigerEinEintragPasstResult;
    private final SchuelerErfassenModel schuelerErfassenModel;
    private JPanel contentPane;
    private JButton buttonUebernehmen;
    private JButton buttonKorrigieren;
    private JLabel lblBeschreibung;
    private JLabel lblAngehoeriger;

    public AngehoerigerEinEintragPasstDialog(
            AngehoerigerEinEintragPasstResult angehoerigerEinEintragPasstResult,
            SchuelerErfassenModel schuelerErfassenModel) {
        this.angehoerigerEinEintragPasstResult = angehoerigerEinEintragPasstResult;
        this.schuelerErfassenModel = schuelerErfassenModel;
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonUebernehmen);

        setTitle(angehoerigerEinEintragPasstResult.getAngehoerigenArt() + " bereits in Datenbank");
        lblBeschreibung.setText("In der Datenbank wurde ein Eintrag gefunden, der auf die erfassten Angaben von " + angehoerigerEinEintragPasstResult.getAngehoerigenArt() + " passt:");
        lblAngehoeriger.setText(angehoerigerEinEintragPasstResult.getAngehoerigerFound().toString());

        buttonUebernehmen.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onUebernehmen();
            }
        });

        buttonKorrigieren.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onZurueck();
            }
        });

        // call onZurueck() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onZurueck();
            }
        });

        // call onZurueck() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onZurueck();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void onUebernehmen() {
        setResult(schuelerErfassenModel.proceedUebernehmen(angehoerigerEinEintragPasstResult));
        dispose();
    }

    private void onZurueck() {
        schuelerErfassenModel.abbrechen();
        abbrechen();
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        contentPane.add(panel1, BorderLayout.CENTER);
        lblBeschreibung = new JLabel();
        lblBeschreibung.setText("Beschreibung");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(lblBeschreibung, gbc);
        lblAngehoeriger = new JLabel();
        lblAngehoeriger.setText("Angehöriger");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 5, 5);
        panel1.add(lblAngehoeriger, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        contentPane.add(panel2, BorderLayout.SOUTH);
        buttonUebernehmen = new JButton();
        buttonUebernehmen.setText("Eintrag übernehmen");
        buttonUebernehmen.setMnemonic('E');
        buttonUebernehmen.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel2.add(buttonUebernehmen, gbc);
        buttonKorrigieren = new JButton();
        buttonKorrigieren.setText("Eingabe korrigieren");
        buttonKorrigieren.setMnemonic('K');
        buttonKorrigieren.setDisplayedMnemonicIndex(8);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel2.add(buttonKorrigieren, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
