package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.domain.model.AngehoerigerMehrereEintraegeGleicherNameAndereAttributeResult;
import ch.metzenthin.svm.domain.model.SchuelerErfassenModel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class AngehoerigerMehrereEintraegeGleicherNameAndereAttributeDialog extends SchuelerErfassenDialog {
    private final AngehoerigerMehrereEintraegeGleicherNameAndereAttributeResult angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult;
    private final SchuelerErfassenModel schuelerErfassenModel;
    private JPanel contentPane;
    private JButton buttonNeuErfasstenEintragVerwenden;
    private JButton buttonKorrigieren;
    private JLabel lblBeschreibung1;
    private JLabel lblAngehoerigerErfasst;
    private JLabel lblBeschreibung2;
    private JLabel lblAngehoerigeFound;

    public AngehoerigerMehrereEintraegeGleicherNameAndereAttributeDialog(
            AngehoerigerMehrereEintraegeGleicherNameAndereAttributeResult angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult,
            SchuelerErfassenModel schuelerErfassenModel
    ) {
        this.angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult = angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult;
        this.schuelerErfassenModel = schuelerErfassenModel;
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonNeuErfasstenEintragVerwenden);

        setTitle(angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult.getAngehoerigenArt() + " möglicherweise bereits in Datenbank");

        lblBeschreibung1.setText("In der Datenbank wurden mehrere Einträge gefunden, der mit den erfassten Angaben für " + angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult.getAngehoerigenArt());
        lblAngehoerigerErfasst.setText(angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult.getAngehoerigerErfasst().toString());
        lblBeschreibung2.setText("teilweise übereinstimmen:");
        setAngehoerigeFound();

        buttonNeuErfasstenEintragVerwenden.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onNeuErfasstenEintragVerwenden();
            }
        });

        buttonKorrigieren.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onKorrigieren();
            }
        });

        // call onKorrigieren() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onKorrigieren();
            }
        });

        // call onKorrigieren() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onKorrigieren();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void setAngehoerigeFound() {
        StringBuilder angehoerigeFoundStb = new StringBuilder("<html>");
        angehoerigeFoundStb.append(angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult.getAngehoerigeFoundInDatabase().get(0));
        for (int i = 1; i < angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult.getAngehoerigeFoundInDatabase().size(); i++) {
            angehoerigeFoundStb.append("<br>").append(angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult.getAngehoerigeFoundInDatabase().get(i));
        }
        angehoerigeFoundStb.append("</html>");
        lblAngehoerigeFound.setText(angehoerigeFoundStb.toString());
    }

    private void onNeuErfasstenEintragVerwenden() {
        setResult(schuelerErfassenModel.proceedWeiterfahren(angehoerigerMehrereEintraegeGleicherNameAndereAttributeResult));
        dispose();
    }

    private void onKorrigieren() {
        schuelerErfassenModel.abbrechen();
        abbrechen();
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        contentPane.add(panel1, BorderLayout.CENTER);
        lblBeschreibung1 = new JLabel();
        lblBeschreibung1.setText("Beschreibung1");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(lblBeschreibung1, gbc);
        lblAngehoerigerErfasst = new JLabel();
        lblAngehoerigerErfasst.setText("AngehoerigerErfasst");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 5, 5);
        panel1.add(lblAngehoerigerErfasst, gbc);
        lblBeschreibung2 = new JLabel();
        lblBeschreibung2.setText("Beschreibung2");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 5, 5);
        panel1.add(lblBeschreibung2, gbc);
        lblAngehoerigeFound = new JLabel();
        lblAngehoerigeFound.setText("AngehoerigeFoundInDatabase");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 5, 5);
        panel1.add(lblAngehoerigeFound, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        contentPane.add(panel2, BorderLayout.SOUTH);
        buttonKorrigieren = new JButton();
        buttonKorrigieren.setText("Eingabe korrigieren");
        buttonKorrigieren.setMnemonic('E');
        buttonKorrigieren.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel2.add(buttonKorrigieren, gbc);
        buttonNeuErfasstenEintragVerwenden = new JButton();
        buttonNeuErfasstenEintragVerwenden.setText("Neu erfassten Eintrag verwenden");
        buttonNeuErfasstenEintragVerwenden.setMnemonic('N');
        buttonNeuErfasstenEintragVerwenden.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel2.add(buttonNeuErfasstenEintragVerwenden, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
