package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.domain.model.AngehoerigerEinEintragGleicherNameAndereAttributeResult;
import ch.metzenthin.svm.domain.model.SchuelerErfassenModel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class AngehoerigerEinEintragGleicherNameAndereAttributeDialog extends SchuelerErfassenDialog {
    private final AngehoerigerEinEintragGleicherNameAndereAttributeResult angehoerigerEinEintragGleicherNameAndereAttributeResult;
    private final SchuelerErfassenModel schuelerErfassenModel;
    private JPanel contentPane;
    private JButton buttonDbUebernehmen;
    private JButton buttonAbbrechen;
    private JButton buttonNeuErfasstenEintragVerwenden;
    private JLabel lblBeschreibung1;
    private JLabel lblAngehoerigerErfasst;
    private JLabel lblBeschreibung2;
    private JLabel lblAngehoerigerDb;

    public AngehoerigerEinEintragGleicherNameAndereAttributeDialog(
            AngehoerigerEinEintragGleicherNameAndereAttributeResult angehoerigerEinEintragGleicherNameAndereAttributeResult,
            SchuelerErfassenModel schuelerErfassenModel
    ) {
        this.angehoerigerEinEintragGleicherNameAndereAttributeResult = angehoerigerEinEintragGleicherNameAndereAttributeResult;
        this.schuelerErfassenModel = schuelerErfassenModel;
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonDbUebernehmen);

        setTitle(angehoerigerEinEintragGleicherNameAndereAttributeResult.getAngehoerigenArt() + " möglicherweise bereits in Datenbank");

        lblBeschreibung1.setText("In der Datenbank wurde ein Eintrag gefunden, der mit den erfassten Angaben für " + angehoerigerEinEintragGleicherNameAndereAttributeResult.getAngehoerigenArt());
        lblAngehoerigerErfasst.setText(angehoerigerEinEintragGleicherNameAndereAttributeResult.getAngehoerigerErfasst().toString());
        lblBeschreibung2.setText("teilweise übereinstimmt:");
        lblAngehoerigerDb.setText(angehoerigerEinEintragGleicherNameAndereAttributeResult.getAngehoerigerFoundInDatabase().toString());

        buttonDbUebernehmen.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onDbUebernehmen();
            }
        });

        buttonNeuErfasstenEintragVerwenden.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onNeuErfasstenEintragVerwenden();
            }
        });

        buttonAbbrechen.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onAbbrechen();
            }
        });

        // call onAbbrechen() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onAbbrechen();
            }
        });

        // call onAbbrechen() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onAbbrechen();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void onDbUebernehmen() {
        setResult(schuelerErfassenModel.proceedUebernehmen(angehoerigerEinEintragGleicherNameAndereAttributeResult));
        dispose();
    }

    private void onNeuErfasstenEintragVerwenden() {
        setResult(schuelerErfassenModel.proceedWeiterfahren(angehoerigerEinEintragGleicherNameAndereAttributeResult));
        dispose();
    }

    private void onAbbrechen() {
        schuelerErfassenModel.abbrechen();
        abbrechen();
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        contentPane.add(panel1, BorderLayout.CENTER);
        lblBeschreibung1 = new JLabel();
        lblBeschreibung1.setText("Beschreibung1");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(lblBeschreibung1, gbc);
        lblAngehoerigerErfasst = new JLabel();
        lblAngehoerigerErfasst.setText("AngehoerigerErfasst");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 5, 5);
        panel1.add(lblAngehoerigerErfasst, gbc);
        lblBeschreibung2 = new JLabel();
        lblBeschreibung2.setText("Beschreibung2");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 5, 5);
        panel1.add(lblBeschreibung2, gbc);
        lblAngehoerigerDb = new JLabel();
        lblAngehoerigerDb.setText("AngehoerigerDb");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 5, 5);
        panel1.add(lblAngehoerigerDb, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        contentPane.add(panel2, BorderLayout.SOUTH);
        buttonDbUebernehmen = new JButton();
        buttonDbUebernehmen.setText("Eintrag aus Datenbank übernehmen");
        buttonDbUebernehmen.setMnemonic('E');
        buttonDbUebernehmen.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel2.add(buttonDbUebernehmen, gbc);
        buttonAbbrechen = new JButton();
        buttonAbbrechen.setText("Abbrechen");
        buttonAbbrechen.setMnemonic('A');
        buttonAbbrechen.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel2.add(buttonAbbrechen, gbc);
        buttonNeuErfasstenEintragVerwenden = new JButton();
        buttonNeuErfasstenEintragVerwenden.setText("Neu erfassten Eintrag verwenden");
        buttonNeuErfasstenEintragVerwenden.setMnemonic('N');
        buttonNeuErfasstenEintragVerwenden.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel2.add(buttonNeuErfasstenEintragVerwenden, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
