package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.domain.commands.ValidateSchuelerCommand;
import ch.metzenthin.svm.domain.model.AngehoerigerMehrereEintraegePassenResult;
import ch.metzenthin.svm.domain.model.SchuelerErfassenModel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class AngehoerigerMehrereEintraegePassenDialog extends SchuelerErfassenDialog {
    private final AngehoerigerMehrereEintraegePassenResult angehoerigerMehrereEintraegePassenResult;
    private final SchuelerErfassenModel schuelerErfassenModel;
    private JPanel contentPane;
    private JButton buttonOk;
    private JLabel lblBeschreibung1;
    private JLabel lblAngehoerigeFound;
    private JLabel lblBeschreibung2;

    public AngehoerigerMehrereEintraegePassenDialog(
            AngehoerigerMehrereEintraegePassenResult angehoerigerMehrereEintraegePassenResult,
            SchuelerErfassenModel schuelerErfassenModel
    ) {
        this.angehoerigerMehrereEintraegePassenResult = angehoerigerMehrereEintraegePassenResult;
        this.schuelerErfassenModel = schuelerErfassenModel;
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOk);

        setTitle("Fehler");
        lblBeschreibung1.setText("In der Datenbank wurden mehrere Einträge gefunden, die auf die erfassten Eingaben für " + angehoerigerMehrereEintraegePassenResult.getAngehoerigenArt() + " passen:");
        setAngehoerigeFound();
        setBeschreibung2();

        buttonOk.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onOk();
            }
        });

        // call onOk() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onOk();
            }
        });

        // call onOk() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onOk();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void setAngehoerigeFound() {
        StringBuilder angehoerigeFoundStb = new StringBuilder("<html>");
        angehoerigeFoundStb.append(angehoerigerMehrereEintraegePassenResult.getAngehoerigeFound().get(0));
        for (int i = 1; i < angehoerigerMehrereEintraegePassenResult.getAngehoerigeFound().size(); i++) {
            angehoerigeFoundStb.append("<br>").append(angehoerigerMehrereEintraegePassenResult.getAngehoerigeFound().get(i));
        }
        angehoerigeFoundStb.append("</html>");
        lblAngehoerigeFound.setText(angehoerigeFoundStb.toString());
    }

    private void setBeschreibung2() {
        String angehoerigerArtikel;
        if (angehoerigerMehrereEintraegePassenResult.getAngehoerigenArt() == ValidateSchuelerCommand.AngehoerigenArt.MUTTER) {
            angehoerigerArtikel = "Die ";
        } else {
            angehoerigerArtikel = "Der ";
        }
        lblBeschreibung2.setText(angehoerigerArtikel + angehoerigerMehrereEintraegePassenResult.getAngehoerigenArt() + " muss genauer erfasst werden.");
    }

    private void onOk() {
        schuelerErfassenModel.abbrechen();
        abbrechen();
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        contentPane.add(panel1, BorderLayout.CENTER);
        lblBeschreibung1 = new JLabel();
        lblBeschreibung1.setText("Beschreibung1");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(lblBeschreibung1, gbc);
        lblAngehoerigeFound = new JLabel();
        lblAngehoerigeFound.setText("AngehoerigeFound");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 30, 5, 5);
        panel1.add(lblAngehoerigeFound, gbc);
        lblBeschreibung2 = new JLabel();
        lblBeschreibung2.setText("Beschreibung2");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 5, 5);
        panel1.add(lblBeschreibung2, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        contentPane.add(panel2, BorderLayout.SOUTH);
        buttonOk = new JButton();
        buttonOk.setText("OK");
        buttonOk.setMnemonic('O');
        buttonOk.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel2.add(buttonOk, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
