package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.domain.model.SchuelerDatenblattModel;
import ch.metzenthin.svm.ui.componentmodel.DispensationenTableModel;
import ch.metzenthin.svm.ui.componentmodel.SchuelerSuchenTableModel;
import ch.metzenthin.svm.ui.control.DispensationenController;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.Locale;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;

/**
 * @author Martin Schraner
 */
@SuppressWarnings({"java:S100", "java:S1450"})
public class DispensationenPanel {

  private JPanel panel1;
  private JTable dispensationenTable;
  private JLabel lblTitel;
  private JButton btnBearbeiten;
  private JButton btnNeu;
  private JButton btnZurueck;
  private JPanel datenPanel;
  private JPanel buttonPanel;
  private JPanel titelPanel;
  private JButton btnLoeschen;
  private DispensationenController dispensationenController;

  public DispensationenPanel(
      SvmContext svmContext,
      DispensationenTableModel dispensationenTableModel,
      SchuelerDatenblattModel schuelerDatenblattModel,
      SchuelerSuchenTableModel schuelerSuchenTableModel,
      JTable schuelerSuchenResultTable,
      int selectedRow,
      boolean isFromSchuelerSuchenResult) {
    $$$setupUI$$$();
    initDispensationenTable(dispensationenTableModel);
    createDispensationenController(
        svmContext,
        dispensationenTableModel,
        schuelerDatenblattModel,
        schuelerSuchenTableModel,
        schuelerSuchenResultTable,
        selectedRow,
        isFromSchuelerSuchenResult);
  }

  private void initDispensationenTable(DispensationenTableModel dispensationenTableModel) {
    dispensationenTable.setModel(dispensationenTableModel);
  }

  private void createDispensationenController(
      SvmContext svmContext,
      DispensationenTableModel dispensationenTableModel,
      SchuelerDatenblattModel schuelerDatenblattModel,
      SchuelerSuchenTableModel schuelerSuchenTableModel,
      JTable schuelerSuchenResultTable,
      int selectedRow,
      boolean isFromSchuelerSuchenResult) {
    dispensationenController =
        new DispensationenController(
            svmContext.getModelFactory().createDispensationenModel(),
            svmContext,
            dispensationenTableModel,
            schuelerDatenblattModel,
            schuelerSuchenTableModel,
            schuelerSuchenResultTable,
            selectedRow,
            isFromSchuelerSuchenResult);
    dispensationenController.setDispensationenTable(dispensationenTable);
    dispensationenController.setLblTitel(lblTitel);
    dispensationenController.setBtnNeu(btnNeu);
    dispensationenController.setBtnBearbeiten(btnBearbeiten);
    dispensationenController.setBtnLoeschen(btnLoeschen);
    dispensationenController.setBtnZurueck(btnZurueck);
  }

  public void addNextPanelListener(ActionListener actionListener) {
    dispensationenController.addNextPanelListener(actionListener);
  }

  public void addCloseListener(ActionListener closeListener) {
    dispensationenController.addCloseListener(closeListener);
  }

  public void addZurueckZuSchuelerSuchenListener(ActionListener zurueckZuSchuelerSuchenListener) {
    dispensationenController.addZurueckZuSchuelerSuchenListener(zurueckZuSchuelerSuchenListener);
  }

  private void createUIComponents() {
    dispensationenTable = new JTable();
    dispensationenTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
  }

  /** Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    panel1 = new JPanel();
    panel1.setLayout(new BorderLayout(0, 0));
    datenPanel = new JPanel();
    datenPanel.setLayout(new GridBagLayout());
    panel1.add(datenPanel, BorderLayout.CENTER);
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new GridBagLayout());
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.gridwidth = 5;
    gbc.insets = new Insets(10, 10, 10, 10);
    datenPanel.add(panel2, gbc);
    panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Dispensationen",
        TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION,
        this.$$$getFont$$$(null, Font.BOLD, -1, panel2.getFont()), new Color(-16777216)));
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    panel2.add(spacer2, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    panel2.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(spacer4, gbc);
    final JScrollPane scrollPane1 = new JScrollPane();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.BOTH;
    panel2.add(scrollPane1, gbc);
    dispensationenTable.setOpaque(false);
    dispensationenTable.setPreferredScrollableViewportSize(new Dimension(900, 200));
    scrollPane1.setViewportView(dispensationenTable);
    titelPanel = new JPanel();
    titelPanel.setLayout(new GridBagLayout());
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.gridwidth = 5;
    gbc.weightx = 1.0;
    gbc.anchor = GridBagConstraints.NORTH;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(10, 10, 20, 10);
    datenPanel.add(titelPanel, gbc);
    lblTitel = new JLabel();
    Font lblTitelFont = this.$$$getFont$$$(null, -1, 36, lblTitel.getFont());
    if (lblTitelFont != null)
      lblTitel.setFont(lblTitelFont);
    lblTitel.setText("Dispensationen Vorname Nachname");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    titelPanel.add(lblTitel, gbc);
    final JPanel spacer5 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    titelPanel.add(spacer5, gbc);
    final JPanel spacer6 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.gridwidth = 5;
    gbc.weighty = 0.5;
    gbc.fill = GridBagConstraints.VERTICAL;
    datenPanel.add(spacer6, gbc);
    final JPanel spacer7 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 3;
    gbc.weighty = 0.5;
    gbc.fill = GridBagConstraints.VERTICAL;
    datenPanel.add(spacer7, gbc);
    buttonPanel = new JPanel();
    buttonPanel.setLayout(new GridBagLayout());
    panel1.add(buttonPanel, BorderLayout.SOUTH);
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1, true, false));
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill = GridBagConstraints.BOTH;
    buttonPanel.add(panel3, gbc);
    final JPanel panel4 = new JPanel();
    panel4.setLayout(new GridBagLayout());
    panel3.add(panel4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    final JPanel panel5 = new JPanel();
    panel5.setLayout(new GridBagLayout());
    panel3.add(panel5, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    btnZurueck = new JButton();
    btnZurueck.setMaximumSize(new Dimension(114, 29));
    btnZurueck.setMinimumSize(new Dimension(114, 29));
    btnZurueck.setPreferredSize(new Dimension(114, 29));
    btnZurueck.setText("Zurück");
    btnZurueck.setMnemonic('Z');
    btnZurueck.setDisplayedMnemonicIndex(0);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.EAST;
    gbc.insets = new Insets(0, 0, 0, 10);
    panel5.add(btnZurueck, gbc);
    final JPanel spacer8 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel5.add(spacer8, gbc);
    final JPanel spacer9 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    panel5.add(spacer9, gbc);
    final JPanel spacer10 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    panel5.add(spacer10, gbc);
    final JPanel panel6 = new JPanel();
    panel6.setLayout(new GridBagLayout());
    panel3.add(panel6, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    btnNeu = new JButton();
    btnNeu.setActionCommand("Neuer Eintrag");
    btnNeu.setMaximumSize(new Dimension(114, 29));
    btnNeu.setMinimumSize(new Dimension(114, 29));
    btnNeu.setPreferredSize(new Dimension(114, 29));
    btnNeu.setSelected(true);
    btnNeu.setText("Neu");
    btnNeu.setMnemonic('N');
    btnNeu.setDisplayedMnemonicIndex(0);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel6.add(btnNeu, gbc);
    btnBearbeiten = new JButton();
    btnBearbeiten.setMaximumSize(new Dimension(114, 29));
    btnBearbeiten.setMinimumSize(new Dimension(114, 29));
    btnBearbeiten.setPreferredSize(new Dimension(114, 29));
    btnBearbeiten.setText("Bearbeiten");
    btnBearbeiten.setMnemonic('B');
    btnBearbeiten.setDisplayedMnemonicIndex(0);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel6.add(btnBearbeiten, gbc);
    btnLoeschen = new JButton();
    btnLoeschen.setMaximumSize(new Dimension(114, 29));
    btnLoeschen.setMinimumSize(new Dimension(114, 29));
    btnLoeschen.setPreferredSize(new Dimension(114, 29));
    btnLoeschen.setText("Löschen");
    btnLoeschen.setMnemonic('L');
    btnLoeschen.setDisplayedMnemonicIndex(0);
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel6.add(btnLoeschen, gbc);
    final JPanel spacer11 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    panel6.add(spacer11, gbc);
    final JPanel spacer12 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    panel6.add(spacer12, gbc);
    final JPanel spacer13 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel6.add(spacer13, gbc);
    final JPanel spacer14 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel6.add(spacer14, gbc);
  }

  /** @noinspection ALL */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null)
      return null;
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(),
        size >= 0 ? size : currentFont.getSize());
    boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
    Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize())
        : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
    return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() {
    return panel1;
  }

}
