package ch.metzenthin.svm.ui.components;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemListener;

/**
 * @author hans
 */
public class ElternteilZweiPanel {
    private JPanel panel;
    private AngehoerigerPanel angehoerigerPanel;

    public void addRechnungsempfaengerAdresseItemListener(ItemListener listener) {
        angehoerigerPanel.addRechnungsempfaengerAdresseItemListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        panel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Elternteil 2"));
        angehoerigerPanel = new AngehoerigerPanel();
        panel.add(angehoerigerPanel.$$$getRootComponent$$$(), BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
