package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.common.dataTypes.Elternteil;
import ch.metzenthin.svm.common.dataTypes.Gruppe;
import ch.metzenthin.svm.domain.model.MaercheneinteilungErfassenModel;
import ch.metzenthin.svm.domain.model.MaercheneinteilungenModel;
import ch.metzenthin.svm.domain.model.SchuelerDatenblattModel;
import ch.metzenthin.svm.persistence.entities.ElternmithilfeCode;
import ch.metzenthin.svm.ui.componentmodel.MaercheneinteilungenTableModel;
import ch.metzenthin.svm.ui.control.MaercheneinteilungErfassenController;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MaercheneinteilungErfassenDialog extends JDialog {
    private JPanel contentPane;
    private JPanel datenPanel;
    private JPanel buttonPanel;
    private JSpinner spinnerMaerchen;
    private JComboBox<Gruppe> comboBoxGruppe;
    private JTextField txtRolle1;
    private JTextField txtBilderRolle1;
    private JTextField txtRolle2;
    private JTextField txtBilderRolle2;
    private JTextField txtRolle3;
    private JTextField txtBilderRolle3;
    private JComboBox<Elternteil> comboBoxElternmithilfe;
    private JComboBox<ElternmithilfeCode> comboBoxElternmithilfeCode;
    private JCheckBox checkBoxKuchenVorstellung1;
    private JCheckBox checkBoxKuchenVorstellung2;
    private JCheckBox checkBoxKuchenVorstellung3;
    private JCheckBox checkBoxKuchenVorstellung4;
    private JCheckBox checkBoxKuchenVorstellung5;
    private JCheckBox checkBoxKuchenVorstellung6;
    private JCheckBox checkBoxKuchenVorstellung7;
    private JCheckBox checkBoxKuchenVorstellung8;
    private JCheckBox checkBoxKuchenVorstellung9;
    private JTextField txtZusatzattribut;
    private JTextField txtBemerkungen;
    private JLabel errLblMaerchen;
    private JLabel errLblGruppe;
    private JLabel errLblRolle1;
    private JLabel errLblBilderRolle1;
    private JLabel errLblRolle2;
    private JLabel errLblBilderRolle2;
    private JLabel errLblRolle3;
    private JLabel errLblBilderRolle3;
    private JLabel errLblElternmithilfe;
    private JLabel errLblElternmithilfeCode;
    private JLabel errLblZusatzattribut;
    private JLabel errLblBemerkungen;
    private JButton btnSpeichern;
    private JButton btnAbbrechen;

    public MaercheneinteilungErfassenDialog(SvmContext svmContext, MaercheneinteilungenModel maercheneinteilungenModel, MaercheneinteilungenTableModel maercheneinteilungenTableModel, SchuelerDatenblattModel schuelerDatenblattModel, int indexBearbeiten, boolean isBearbeiten, String title) {
        $$$setupUI$$$();
        setContentPane(contentPane);
        setModal(true);
        setTitle(title);
        createMaercheneinteilungErfassenController(svmContext, maercheneinteilungenModel, maercheneinteilungenTableModel, schuelerDatenblattModel, indexBearbeiten, isBearbeiten);
        initializeErrLbls();
    }

    private void createMaercheneinteilungErfassenController(SvmContext svmContext, MaercheneinteilungenModel maercheneinteilungenModel, MaercheneinteilungenTableModel maercheneinteilungenTableModel, SchuelerDatenblattModel schuelerDatenblattModel, int indexBearbeiten, boolean isBearbeiten) {
        MaercheneinteilungErfassenModel maercheneinteilungErfassenModel = (isBearbeiten ? maercheneinteilungenModel.getMaercheneinteilungErfassenModel(svmContext, maercheneinteilungenTableModel, indexBearbeiten) : svmContext.getModelFactory().createMaercheneinteilungErfassenModel());
        MaercheneinteilungErfassenController maercheneinteilungErfassenController = new MaercheneinteilungErfassenController(svmContext, maercheneinteilungErfassenModel, maercheneinteilungenTableModel, maercheneinteilungenModel, schuelerDatenblattModel, isBearbeiten);
        maercheneinteilungErfassenController.setMaercheneinteilungErfassenDialog(this);
        maercheneinteilungErfassenController.setContentPane(contentPane);
        maercheneinteilungErfassenController.setComboBoxGruppe(comboBoxGruppe);
        maercheneinteilungErfassenController.setTxtRolle1(txtRolle1);
        maercheneinteilungErfassenController.setTxtBilderRolle1(txtBilderRolle1);
        maercheneinteilungErfassenController.setTxtRolle2(txtRolle2);
        maercheneinteilungErfassenController.setTxtBilderRolle2(txtBilderRolle2);
        maercheneinteilungErfassenController.setTxtRolle3(txtRolle3);
        maercheneinteilungErfassenController.setTxtBilderRolle3(txtBilderRolle3);
        maercheneinteilungErfassenController.setComboBoxElternmithilfe(comboBoxElternmithilfe);
        maercheneinteilungErfassenController.setComboBoxElternmithilfeCode(comboBoxElternmithilfeCode);
        maercheneinteilungErfassenController.setCheckBoxKuchenVorstellung1(checkBoxKuchenVorstellung1);
        maercheneinteilungErfassenController.setCheckBoxKuchenVorstellung2(checkBoxKuchenVorstellung2);
        maercheneinteilungErfassenController.setCheckBoxKuchenVorstellung3(checkBoxKuchenVorstellung3);
        maercheneinteilungErfassenController.setCheckBoxKuchenVorstellung4(checkBoxKuchenVorstellung4);
        maercheneinteilungErfassenController.setCheckBoxKuchenVorstellung5(checkBoxKuchenVorstellung5);
        maercheneinteilungErfassenController.setCheckBoxKuchenVorstellung6(checkBoxKuchenVorstellung6);
        maercheneinteilungErfassenController.setCheckBoxKuchenVorstellung7(checkBoxKuchenVorstellung7);
        maercheneinteilungErfassenController.setCheckBoxKuchenVorstellung8(checkBoxKuchenVorstellung8);
        maercheneinteilungErfassenController.setCheckBoxKuchenVorstellung9(checkBoxKuchenVorstellung9);
        maercheneinteilungErfassenController.setTxtZusatzattribut(txtZusatzattribut);
        maercheneinteilungErfassenController.setTxtBemerkungen(txtBemerkungen);
        maercheneinteilungErfassenController.setBtnSpeichern(btnSpeichern);
        maercheneinteilungErfassenController.setBtnAbbrechen(btnAbbrechen);
        maercheneinteilungErfassenController.setErrLblGruppe(errLblGruppe);
        maercheneinteilungErfassenController.setErrLblRolle1(errLblRolle1);
        maercheneinteilungErfassenController.setErrLblBilderRolle1(errLblBilderRolle1);
        maercheneinteilungErfassenController.setErrLblRolle2(errLblRolle2);
        maercheneinteilungErfassenController.setErrLblBilderRolle2(errLblBilderRolle2);
        maercheneinteilungErfassenController.setErrLblRolle3(errLblRolle3);
        maercheneinteilungErfassenController.setErrLblBilderRolle3(errLblBilderRolle3);
        maercheneinteilungErfassenController.setErrLblElternmithilfe(errLblElternmithilfe);
        maercheneinteilungErfassenController.setErrLblElternmithilfeCode(errLblElternmithilfeCode);
        maercheneinteilungErfassenController.setErrLblZusatzattribut(errLblZusatzattribut);
        maercheneinteilungErfassenController.setErrLblBemerkungen(errLblBemerkungen);
        maercheneinteilungErfassenController.setErrLblMaerchen(errLblMaerchen);
        maercheneinteilungErfassenController.setSpinnerMaerchen(spinnerMaerchen);   // muss am Schluss aufgerufen werden!
        maercheneinteilungErfassenController.constructionDone();
    }

    private void initializeErrLbls() {
        errLblMaerchen.setVisible(false);
        errLblMaerchen.setForeground(Color.RED);
        errLblGruppe.setVisible(false);
        errLblGruppe.setForeground(Color.RED);
        errLblRolle1.setVisible(false);
        errLblRolle1.setForeground(Color.RED);
        errLblBilderRolle1.setVisible(false);
        errLblBilderRolle1.setForeground(Color.RED);
        errLblRolle2.setVisible(false);
        errLblRolle2.setForeground(Color.RED);
        errLblBilderRolle2.setVisible(false);
        errLblBilderRolle2.setForeground(Color.RED);
        errLblRolle3.setVisible(false);
        errLblRolle3.setForeground(Color.RED);
        errLblBilderRolle3.setVisible(false);
        errLblBilderRolle3.setForeground(Color.RED);
        errLblElternmithilfe.setVisible(false);
        errLblElternmithilfe.setForeground(Color.RED);
        errLblElternmithilfeCode.setVisible(false);
        errLblElternmithilfeCode.setForeground(Color.RED);
        errLblZusatzattribut.setVisible(false);
        errLblZusatzattribut.setForeground(Color.RED);
        errLblBemerkungen.setVisible(false);
        errLblBemerkungen.setForeground(Color.RED);
    }

    private void createUIComponents() {
        spinnerMaerchen = new JSpinner();
        comboBoxGruppe = new JComboBox<>(Gruppe.values());
        comboBoxElternmithilfe = new JComboBox<>(Elternteil.values());
        comboBoxElternmithilfeCode = new JComboBox<>();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        datenPanel = new JPanel();
        datenPanel.setLayout(new GridBagLayout());
        contentPane.add(datenPanel, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 10, 10);
        datenPanel.add(panel1, gbc);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Märcheneinteilung", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(panel1.getFont().getName(), Font.BOLD, panel1.getFont().getSize())));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Märchen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 11;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer4, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Rolle 1");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label2, gbc);
        txtRolle1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(txtRolle1, gbc);
        errLblRolle1 = new JLabel();
        errLblRolle1.setText("errLblRolle1");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblRolle1, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer5, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Rolle 2");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label3, gbc);
        txtRolle2 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(txtRolle2, gbc);
        errLblRolle2 = new JLabel();
        errLblRolle2.setText("errLblRolle2");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblRolle2, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer6, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Rolle 3");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label4, gbc);
        txtRolle3 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(txtRolle3, gbc);
        errLblRolle3 = new JLabel();
        errLblRolle3.setText("errLblRolle3");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblRolle3, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer7, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Elternmithilfe");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label5, gbc);
        errLblElternmithilfe = new JLabel();
        errLblElternmithilfe.setText("errLblElternmithilfe");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblElternmithilfe, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer8, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Vorst. m. Kuchen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label6, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 15;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 400;
        panel2.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 15;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 15;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 115;
        panel2.add(spacer11, gbc);
        errLblMaerchen = new JLabel();
        errLblMaerchen.setText("errLblMaerchen");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblMaerchen, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(comboBoxElternmithilfe, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Gruppe");
        gbc = new GridBagConstraints();
        gbc.gridx = 13;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label7, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Bilder Rolle 1");
        gbc = new GridBagConstraints();
        gbc.gridx = 13;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label8, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Bilder Rolle 2");
        gbc = new GridBagConstraints();
        gbc.gridx = 13;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label9, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Bilder Rolle 3");
        gbc = new GridBagConstraints();
        gbc.gridx = 13;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label10, gbc);
        txtBilderRolle1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(txtBilderRolle1, gbc);
        txtBilderRolle2 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(txtBilderRolle2, gbc);
        txtBilderRolle3 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(txtBilderRolle3, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(comboBoxGruppe, gbc);
        errLblGruppe = new JLabel();
        errLblGruppe.setText("errLblGruppe");
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblGruppe, gbc);
        errLblBilderRolle1 = new JLabel();
        errLblBilderRolle1.setText("errLblBilderRolle1");
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblBilderRolle1, gbc);
        errLblBilderRolle2 = new JLabel();
        errLblBilderRolle2.setText("errLblBilderRolle2");
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblBilderRolle2, gbc);
        errLblBilderRolle3 = new JLabel();
        errLblBilderRolle3.setText("errLblBilderRolle3");
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblBilderRolle3, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 15;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 400;
        panel2.add(spacer12, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 13;
        gbc.gridy = 15;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 115;
        panel2.add(spacer13, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 15;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer14, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(panel3, gbc);
        checkBoxKuchenVorstellung1 = new JCheckBox();
        checkBoxKuchenVorstellung1.setText("1");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel3.add(checkBoxKuchenVorstellung1, gbc);
        checkBoxKuchenVorstellung2 = new JCheckBox();
        checkBoxKuchenVorstellung2.setText("2");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel3.add(checkBoxKuchenVorstellung2, gbc);
        checkBoxKuchenVorstellung3 = new JCheckBox();
        checkBoxKuchenVorstellung3.setText("3");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel3.add(checkBoxKuchenVorstellung3, gbc);
        checkBoxKuchenVorstellung4 = new JCheckBox();
        checkBoxKuchenVorstellung4.setText("4");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel3.add(checkBoxKuchenVorstellung4, gbc);
        checkBoxKuchenVorstellung5 = new JCheckBox();
        checkBoxKuchenVorstellung5.setText("5");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel3.add(checkBoxKuchenVorstellung5, gbc);
        checkBoxKuchenVorstellung6 = new JCheckBox();
        checkBoxKuchenVorstellung6.setText("6");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel3.add(checkBoxKuchenVorstellung6, gbc);
        checkBoxKuchenVorstellung7 = new JCheckBox();
        checkBoxKuchenVorstellung7.setText("7");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel3.add(checkBoxKuchenVorstellung7, gbc);
        checkBoxKuchenVorstellung8 = new JCheckBox();
        checkBoxKuchenVorstellung8.setText("8");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel3.add(checkBoxKuchenVorstellung8, gbc);
        checkBoxKuchenVorstellung9 = new JCheckBox();
        checkBoxKuchenVorstellung9.setText("9");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel3.add(checkBoxKuchenVorstellung9, gbc);
        final JPanel spacer15 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer15, gbc);
        final JPanel spacer16 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 12;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer16, gbc);
        final JLabel label11 = new JLabel();
        label11.setText("Code");
        gbc = new GridBagConstraints();
        gbc.gridx = 13;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label11, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(comboBoxElternmithilfeCode, gbc);
        final JPanel spacer17 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer17, gbc);
        final JPanel spacer18 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer18, gbc);
        errLblElternmithilfeCode = new JLabel();
        errLblElternmithilfeCode.setText("errLblEltermithilfeCode");
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblElternmithilfeCode, gbc);
        txtZusatzattribut = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(txtZusatzattribut, gbc);
        final JLabel label12 = new JLabel();
        label12.setText("Zusatzattribut");
        gbc = new GridBagConstraints();
        gbc.gridx = 13;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label12, gbc);
        final JLabel label13 = new JLabel();
        label13.setText("Bemerkungen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label13, gbc);
        errLblZusatzattribut = new JLabel();
        errLblZusatzattribut.setText("errLblZusatzattribut");
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblZusatzattribut, gbc);
        errLblBemerkungen = new JLabel();
        errLblBemerkungen.setText("errLblBemerkungen");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(errLblBemerkungen, gbc);
        txtBemerkungen = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(txtBemerkungen, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spinnerMaerchen, gbc);
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridBagLayout());
        contentPane.add(buttonPanel, BorderLayout.SOUTH);
        btnSpeichern = new JButton();
        btnSpeichern.setMaximumSize(new Dimension(114, 29));
        btnSpeichern.setMinimumSize(new Dimension(114, 29));
        btnSpeichern.setPreferredSize(new Dimension(114, 29));
        btnSpeichern.setText("Speichern");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(btnSpeichern, gbc);
        final JPanel spacer19 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(spacer19, gbc);
        final JPanel spacer20 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttonPanel.add(spacer20, gbc);
        final JPanel spacer21 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttonPanel.add(spacer21, gbc);
        btnAbbrechen = new JButton();
        btnAbbrechen.setMaximumSize(new Dimension(114, 29));
        btnAbbrechen.setMinimumSize(new Dimension(114, 29));
        btnAbbrechen.setPreferredSize(new Dimension(114, 29));
        btnAbbrechen.setText("Abbrechen");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(btnAbbrechen, gbc);
        label2.setLabelFor(txtRolle1);
        label3.setLabelFor(txtRolle2);
        label4.setLabelFor(txtRolle3);
        label7.setLabelFor(comboBoxGruppe);
        label9.setLabelFor(txtBilderRolle2);
        label10.setLabelFor(txtBilderRolle3);
        errLblBilderRolle1.setLabelFor(txtBilderRolle1);
        label12.setLabelFor(txtZusatzattribut);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
