package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.ui.componentmodel.SchuelerSuchenTableModel;
import ch.metzenthin.svm.ui.control.SchuelerDatenblattController;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * @author Hans Stamm
 */
public class SchuelerDatenblattPanel {
    private JPanel panel;
    private JLabel lblSchuelerValue;
    private JLabel lblMutterValue;
    private JLabel lblVaterValue;
    private JPanel stammdatenPanel;
    private JPanel leftPanel;
    private JPanel rightPanel;
    private JLabel lblRechnungsempfaengerValue;
    private JLabel lblGeschwisterValue;
    private JButton btnStammdatenBearbeiten;
    private JPanel titelPanel;
    private JLabel lblAnmeldedatumValue;
    private JPanel dispensationenPanel;
    private JButton btnDispensationenBearbeiten;
    private JPanel codesPanel;
    private JButton btnCodesBearbeiten;
    private JPanel rightButtonPanel;
    private JPanel leftButtonPanel;
    private JButton btnErster;
    private JButton btnVorheriger;
    private JButton btnNachfolgender;
    private JButton btnLetzter;
    private JButton btnZurueck;
    private JButton btnAbbrechen;
    private JLabel lblSchuelerGleicherRechnungsempfaenger1;
    private JLabel lblSchuelerGleicherRechnungsempfaengerValue;
    private JLabel lblVornameNachname;
    private JLabel lblSchuelerGleicherRechnungsempfaenger2;
    private JLabel lblGeburtsdatumValue;
    private JLabel lblSchueler;
    private JLabel lblRechnungsempfaenger;
    private JLabel lblAbmeldedatum;
    private JLabel lblAbmeldedatumValue;
    private JLabel lblFruehereAnmeldungen;
    private JLabel lblFruehereAnmeldungenValue;
    private JLabel lblBemerkungenValue;
    private JLabel lblNichtDispensiert;
    private JLabel lblDispensationsdauer;
    private JLabel lblDispensationsdauerValue;
    private JLabel lblDispensationsgrund;
    private JLabel lblDispensationsgrundValue;
    private JLabel lblFruehereDispensationenValue;
    private JLabel lblSchuelerCodesValue;
    private JLabel lblScrollPosition;
    private JPanel datenPanel;
    private JPanel buttonPanel;
    private JPanel kursePanel;
    private JLabel lblSemesterKurseValue;
    private JLabel lblKurseValue;
    private JButton btnKurseBearbeiten;
    private JPanel maerchenPanel;
    private JLabel lblMaerchenValue;
    private JLabel lblGruppeValue;
    private JLabel lblRolle1Value;
    private JLabel lblBilderRolle1Value;
    private JLabel lblRolle2Value;
    private JLabel lblRolle3Value;
    private JLabel lblElternmithilfeValue;
    private JLabel lblElternmithilfeCodeValue;
    private JLabel lblVorstellungenKuchenValue;
    private JLabel lblZusatzattributValue;
    private JLabel lblBemerkungenMaerchenValue;
    private JButton btnMaerchenBearbeiten;
    private JLabel lblBilderRolle2Value;
    private JLabel lblBilderRolle3Value;
    private JLabel lblRolle1;
    private JLabel lblRolle2;
    private JLabel lblRolle3;
    private JLabel lblElternmithilfe;
    private JLabel lblElternmithilfeCode;
    private JLabel lblVorstellungenKuchen;
    private JLabel lblGruppe;
    private JLabel lblBilderRolle1;
    private JLabel lblBilderRolle2;
    private JLabel lblBilderRolle3;
    private JLabel lblZusatzattribut;
    private JLabel lblBemerkungenMaerchen;
    private JButton btnEmail;

    private final SchuelerDatenblattController schuelerDatenblattController;

    public SchuelerDatenblattPanel(SvmContext svmContext, SchuelerSuchenTableModel schuelerSuchenTableModel, JTable schuelerSuchenResultTable, int selectedRow, boolean isFromSchuelerSuchenResult) {
        schuelerDatenblattController = new SchuelerDatenblattController(svmContext, schuelerSuchenTableModel, schuelerSuchenResultTable, selectedRow, isFromSchuelerSuchenResult);
        schuelerDatenblattController.setLabelVornameNachname(lblVornameNachname);
        schuelerDatenblattController.setLabelSchueler(lblSchueler);
        schuelerDatenblattController.setLabelSchuelerValue(lblSchuelerValue);
        schuelerDatenblattController.setLabelMutterValue(lblMutterValue);
        schuelerDatenblattController.setLabelVaterValue(lblVaterValue);
        schuelerDatenblattController.setLabelRechnungsempfaenger(lblRechnungsempfaenger);
        schuelerDatenblattController.setLabelRechnungsempfaengerValue(lblRechnungsempfaengerValue);
        schuelerDatenblattController.setLabelGeschwisterValue(lblGeschwisterValue);
        schuelerDatenblattController.setLabelSchuelerGleicherRechnungsempfaenger1(lblSchuelerGleicherRechnungsempfaenger1);
        schuelerDatenblattController.setLabelSchuelerGleicherRechnungsempfaenger2(lblSchuelerGleicherRechnungsempfaenger2);
        schuelerDatenblattController.setLabelSchuelerGleicherRechnungsempfaengerValue(lblSchuelerGleicherRechnungsempfaengerValue);
        schuelerDatenblattController.setLabelGeburtsdatumValue(lblGeburtsdatumValue);
        schuelerDatenblattController.setLabelAnmeldedatumValue(lblAnmeldedatumValue);
        schuelerDatenblattController.setLabelAbmeldedatum(lblAbmeldedatum);
        schuelerDatenblattController.setLabelAbmeldedatumValue(lblAbmeldedatumValue);
        schuelerDatenblattController.setLabelFruehereAnmeldungen(lblFruehereAnmeldungen);
        schuelerDatenblattController.setLabelFruehereAnmeldungenValue(lblFruehereAnmeldungenValue);
        schuelerDatenblattController.setLabelBemerkungenValue(lblBemerkungenValue);
        schuelerDatenblattController.setLabelNichtDispensiert(lblNichtDispensiert);
        schuelerDatenblattController.setLabelDispensationsdauer(lblDispensationsdauer);
        schuelerDatenblattController.setLabelDispensationsdauerValue(lblDispensationsdauerValue);
        schuelerDatenblattController.setLabelDispensationsgrund(lblDispensationsgrund);
        schuelerDatenblattController.setLabelDispensationsgrundValue(lblDispensationsgrundValue);
        schuelerDatenblattController.setLabelFruehereDispensationenValue(lblFruehereDispensationenValue);
        schuelerDatenblattController.setLabelSchuelerCodesValue(lblSchuelerCodesValue);
        schuelerDatenblattController.setLabelSemesterKurseValue(lblSemesterKurseValue);
        schuelerDatenblattController.setLabelKurseValue(lblKurseValue);
        schuelerDatenblattController.setLabelMaerchenValue(lblMaerchenValue);
        schuelerDatenblattController.setLabelGruppe(lblGruppe);
        schuelerDatenblattController.setLabelGruppeValue(lblGruppeValue);
        schuelerDatenblattController.setLabelRolle1(lblRolle1);
        schuelerDatenblattController.setLabelRolle1Value(lblRolle1Value);
        schuelerDatenblattController.setLabelBilderRolle1(lblBilderRolle1);
        schuelerDatenblattController.setLabelBilderRolle1Value(lblBilderRolle1Value);
        schuelerDatenblattController.setLabelRolle2(lblRolle2);
        schuelerDatenblattController.setLabelRolle2Value(lblRolle2Value);
        schuelerDatenblattController.setLabelBilderRolle2(lblBilderRolle2);
        schuelerDatenblattController.setLabelBilderRolle2Value(lblBilderRolle2Value);
        schuelerDatenblattController.setLabelRolle3(lblRolle3);
        schuelerDatenblattController.setLabelRolle3Value(lblRolle3Value);
        schuelerDatenblattController.setLabelBilderRolle3(lblBilderRolle3);
        schuelerDatenblattController.setLabelBilderRolle3Value(lblBilderRolle3Value);
        schuelerDatenblattController.setLabelElternmithilfe(lblElternmithilfe);
        schuelerDatenblattController.setLabelElternmithilfeValue(lblElternmithilfeValue);
        schuelerDatenblattController.setLabelElternmithilfeCode(lblElternmithilfeCode);
        schuelerDatenblattController.setLabelElternmithilfeCodeValue(lblElternmithilfeCodeValue);
        schuelerDatenblattController.setLabelVorstellungenKuchen(lblVorstellungenKuchen);
        schuelerDatenblattController.setLabelVorstellungenKuchenValue(lblVorstellungenKuchenValue);
        schuelerDatenblattController.setLabelZusatzattribut(lblZusatzattribut);
        schuelerDatenblattController.setLabelZusatzattributValue(lblZusatzattributValue);
        schuelerDatenblattController.setLabelBemerkungenMaerchen(lblBemerkungenMaerchen);
        schuelerDatenblattController.setLabelBemerkungenMaerchenValue(lblBemerkungenMaerchenValue);
        schuelerDatenblattController.setBtnZurueck(btnZurueck);
        schuelerDatenblattController.setBtnAbbrechen(btnAbbrechen);
        schuelerDatenblattController.setBtnErster(btnErster);
        schuelerDatenblattController.setBtnLetzter(btnLetzter);
        schuelerDatenblattController.setBtnNachfolgender(btnNachfolgender);
        schuelerDatenblattController.setBtnVorheriger(btnVorheriger);
        schuelerDatenblattController.setBtnStammdatenBearbeiten(btnStammdatenBearbeiten);
        schuelerDatenblattController.setBtnEmail(btnEmail);
        schuelerDatenblattController.setBtnDispensationenBearbeiten(btnDispensationenBearbeiten);
        schuelerDatenblattController.setBtnCodesBearbeiten(btnCodesBearbeiten);
        schuelerDatenblattController.setBtnKurseBearbeiten(btnKurseBearbeiten);
        schuelerDatenblattController.setBtnMaerchenBearbeiten(btnMaerchenBearbeiten);
        schuelerDatenblattController.setLabelScrollPosition(lblScrollPosition);
    }

    public void addNextPanelListener(ActionListener nextPanelListener) {
        schuelerDatenblattController.addNextPanelListener(nextPanelListener);
    }

    public void addCloseListener(ActionListener closeListener) {
        schuelerDatenblattController.addCloseListener(closeListener);
    }

    public void addZurueckZuSchuelerSuchenListener(ActionListener zurueckZuSchuelerSuchenListener) {
        schuelerDatenblattController.addZurueckZuSchuelerSuchenListener(zurueckZuSchuelerSuchenListener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel.add(panel1, BorderLayout.CENTER);
        titelPanel = new JPanel();
        titelPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 20, 10);
        panel1.add(titelPanel, gbc);
        lblVornameNachname = new JLabel();
        Font lblVornameNachnameFont = this.$$$getFont$$$(null, -1, 36, lblVornameNachname.getFont());
        if (lblVornameNachnameFont != null) lblVornameNachname.setFont(lblVornameNachnameFont);
        lblVornameNachname.setText("Vorname Nachname");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        titelPanel.add(lblVornameNachname, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        titelPanel.add(spacer1, gbc);
        datenPanel = new JPanel();
        datenPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(datenPanel, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        datenPanel.add(scrollPane1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        scrollPane1.setViewportView(panel2);
        stammdatenPanel = new JPanel();
        stammdatenPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        panel2.add(stammdatenPanel, gbc);
        stammdatenPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Stammdaten", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD, -1, stammdatenPanel.getFont()), new Color(-16777216)));
        lblSchueler = new JLabel();
        lblSchueler.setText("Schüler:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(lblSchueler, gbc);
        lblSchuelerValue = new JLabel();
        lblSchuelerValue.setText("SchuelerValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(lblSchuelerValue, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Mutter:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label1, gbc);
        lblMutterValue = new JLabel();
        lblMutterValue.setText("MutterValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(lblMutterValue, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Vater:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label2, gbc);
        lblVaterValue = new JLabel();
        lblVaterValue.setText("VaterValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(lblVaterValue, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer6, gbc);
        lblRechnungsempfaenger = new JLabel();
        lblRechnungsempfaenger.setText("Rechnungsempfänger:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(lblRechnungsempfaenger, gbc);
        lblRechnungsempfaengerValue = new JLabel();
        lblRechnungsempfaengerValue.setText("RechnungsempfaengerValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(lblRechnungsempfaengerValue, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer7, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Geschwister:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label3, gbc);
        lblGeschwisterValue = new JLabel();
        lblGeschwisterValue.setText("GeschwisterValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(lblGeschwisterValue, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer8, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 20;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel3, gbc);
        btnStammdatenBearbeiten = new JButton();
        btnStammdatenBearbeiten.setText("Bearbeiten");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel3.add(btnStammdatenBearbeiten, gbc);
        btnEmail = new JButton();
        btnEmail.setText("E-Mail");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(btnEmail, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 21;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer11, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Anmeldedatum:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 15;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label4, gbc);
        lblAnmeldedatumValue = new JLabel();
        lblAnmeldedatumValue.setText("AnmeldedatumValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 15;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(lblAnmeldedatumValue, gbc);
        lblSchuelerGleicherRechnungsempfaenger1 = new JLabel();
        lblSchuelerGleicherRechnungsempfaenger1.setText("Andere Schüler mit gleichem");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 10);
        stammdatenPanel.add(lblSchuelerGleicherRechnungsempfaenger1, gbc);
        lblSchuelerGleicherRechnungsempfaengerValue = new JLabel();
        lblSchuelerGleicherRechnungsempfaengerValue.setText("SchuelerGleicherRechnungsempfaengerValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.gridheight = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        stammdatenPanel.add(lblSchuelerGleicherRechnungsempfaengerValue, gbc);
        lblSchuelerGleicherRechnungsempfaenger2 = new JLabel();
        lblSchuelerGleicherRechnungsempfaenger2.setText("Rechnungsempfaenger:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(lblSchuelerGleicherRechnungsempfaenger2, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer12, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Geburtsdatum:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label5, gbc);
        lblGeburtsdatumValue = new JLabel();
        lblGeburtsdatumValue.setText("GeburtsdatumValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(lblGeburtsdatumValue, gbc);
        lblAbmeldedatum = new JLabel();
        Font lblAbmeldedatumFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblAbmeldedatum.getFont());
        if (lblAbmeldedatumFont != null) lblAbmeldedatum.setFont(lblAbmeldedatumFont);
        lblAbmeldedatum.setText("Abmeldedatum:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 16;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        stammdatenPanel.add(lblAbmeldedatum, gbc);
        lblAbmeldedatumValue = new JLabel();
        Font lblAbmeldedatumValueFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblAbmeldedatumValue.getFont());
        if (lblAbmeldedatumValueFont != null) lblAbmeldedatumValue.setFont(lblAbmeldedatumValueFont);
        lblAbmeldedatumValue.setText("AbmeldedatumValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 16;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        stammdatenPanel.add(lblAbmeldedatumValue, gbc);
        lblFruehereAnmeldungen = new JLabel();
        lblFruehereAnmeldungen.setText("Frühere Anmeldungen:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 17;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        stammdatenPanel.add(lblFruehereAnmeldungen, gbc);
        lblFruehereAnmeldungenValue = new JLabel();
        lblFruehereAnmeldungenValue.setText("FrühereAnmeldungenValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 17;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        stammdatenPanel.add(lblFruehereAnmeldungenValue, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        stammdatenPanel.add(spacer13, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 18;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer14, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Bemerkungen:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 19;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label6, gbc);
        lblBemerkungenValue = new JLabel();
        lblBemerkungenValue.setText("BemerkungenValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 19;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(lblBemerkungenValue, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(panel4, gbc);
        leftPanel = new JPanel();
        leftPanel.setLayout(new GridBagLayout());
        panel4.add(leftPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        dispensationenPanel = new JPanel();
        dispensationenPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 10, 0);
        leftPanel.add(dispensationenPanel, gbc);
        dispensationenPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Dispensationen", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD, -1, dispensationenPanel.getFont()), new Color(-16777216)));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        dispensationenPanel.add(panel5, gbc);
        btnDispensationenBearbeiten = new JButton();
        btnDispensationenBearbeiten.setText("Details / Bearbeiten");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel5.add(btnDispensationenBearbeiten, gbc);
        final JPanel spacer15 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel5.add(spacer15, gbc);
        final JPanel spacer16 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        dispensationenPanel.add(spacer16, gbc);
        final JPanel spacer17 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        dispensationenPanel.add(spacer17, gbc);
        lblDispensationsdauerValue = new JLabel();
        Font lblDispensationsdauerValueFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblDispensationsdauerValue.getFont());
        if (lblDispensationsdauerValueFont != null) lblDispensationsdauerValue.setFont(lblDispensationsdauerValueFont);
        lblDispensationsdauerValue.setText("DispensationsdauerValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dispensationenPanel.add(lblDispensationsdauerValue, gbc);
        lblDispensationsdauer = new JLabel();
        Font lblDispensationsdauerFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblDispensationsdauer.getFont());
        if (lblDispensationsdauerFont != null) lblDispensationsdauer.setFont(lblDispensationsdauerFont);
        lblDispensationsdauer.setText("Dauer:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        dispensationenPanel.add(lblDispensationsdauer, gbc);
        final JPanel spacer18 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        dispensationenPanel.add(spacer18, gbc);
        final JPanel spacer19 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        dispensationenPanel.add(spacer19, gbc);
        lblDispensationsgrund = new JLabel();
        Font lblDispensationsgrundFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblDispensationsgrund.getFont());
        if (lblDispensationsgrundFont != null) lblDispensationsgrund.setFont(lblDispensationsgrundFont);
        lblDispensationsgrund.setText("Grund:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        dispensationenPanel.add(lblDispensationsgrund, gbc);
        lblDispensationsgrundValue = new JLabel();
        Font lblDispensationsgrundValueFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblDispensationsgrundValue.getFont());
        if (lblDispensationsgrundValueFont != null) lblDispensationsgrundValue.setFont(lblDispensationsgrundValueFont);
        lblDispensationsgrundValue.setText("DispensationsgrundValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        dispensationenPanel.add(lblDispensationsgrundValue, gbc);
        lblNichtDispensiert = new JLabel();
        lblNichtDispensiert.setText("Nicht dispensiert.");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        dispensationenPanel.add(lblNichtDispensiert, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Frühere Dispensationen:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        dispensationenPanel.add(label7, gbc);
        final JPanel spacer20 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        dispensationenPanel.add(spacer20, gbc);
        lblFruehereDispensationenValue = new JLabel();
        lblFruehereDispensationenValue.setText("FrühereDispensationenValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        dispensationenPanel.add(lblFruehereDispensationenValue, gbc);
        final JPanel spacer21 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        dispensationenPanel.add(spacer21, gbc);
        rightPanel = new JPanel();
        rightPanel.setLayout(new GridBagLayout());
        panel4.add(rightPanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        codesPanel = new JPanel();
        codesPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 10, 10);
        rightPanel.add(codesPanel, gbc);
        codesPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Schüler-Codes", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD, -1, codesPanel.getFont()), new Color(-16777216)));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(panel6, gbc);
        btnCodesBearbeiten = new JButton();
        btnCodesBearbeiten.setText("Bearbeiten");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel6.add(btnCodesBearbeiten, gbc);
        final JPanel spacer22 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(spacer22, gbc);
        final JPanel spacer23 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        codesPanel.add(spacer23, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Codes:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        codesPanel.add(label8, gbc);
        final JPanel spacer24 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(spacer24, gbc);
        final JPanel spacer25 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        codesPanel.add(spacer25, gbc);
        final JPanel spacer26 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        codesPanel.add(spacer26, gbc);
        final JPanel spacer27 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(spacer27, gbc);
        final JPanel spacer28 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        codesPanel.add(spacer28, gbc);
        lblSchuelerCodesValue = new JLabel();
        lblSchuelerCodesValue.setText("CodesValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        codesPanel.add(lblSchuelerCodesValue, gbc);
        final JPanel spacer29 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer29, gbc);
        kursePanel = new JPanel();
        kursePanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 10);
        panel2.add(kursePanel, gbc);
        kursePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Aktuelle Kurse", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD, -1, kursePanel.getFont())));
        final JPanel spacer30 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursePanel.add(spacer30, gbc);
        lblSemesterKurseValue = new JLabel();
        lblSemesterKurseValue.setText("SemesterValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        kursePanel.add(lblSemesterKurseValue, gbc);
        final JPanel spacer31 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursePanel.add(spacer31, gbc);
        final JPanel spacer32 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        kursePanel.add(spacer32, gbc);
        lblKurseValue = new JLabel();
        lblKurseValue.setText("KurseValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        kursePanel.add(lblKurseValue, gbc);
        final JPanel spacer33 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursePanel.add(spacer33, gbc);
        final JPanel spacer34 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursePanel.add(spacer34, gbc);
        final JPanel spacer35 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursePanel.add(spacer35, gbc);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        kursePanel.add(panel7, gbc);
        btnKurseBearbeiten = new JButton();
        btnKurseBearbeiten.setText("Details / Bearbeiten");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 10);
        panel7.add(btnKurseBearbeiten, gbc);
        final JPanel spacer36 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel7.add(spacer36, gbc);
        maerchenPanel = new JPanel();
        maerchenPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 10);
        panel2.add(maerchenPanel, gbc);
        maerchenPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Aktuelles Märchen", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD, -1, maerchenPanel.getFont())));
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new GridBagLayout());
        maerchenPanel.add(panel8, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lblRolle1 = new JLabel();
        Font lblRolle1Font = this.$$$getFont$$$(null, Font.BOLD, -1, lblRolle1.getFont());
        if (lblRolle1Font != null) lblRolle1.setFont(lblRolle1Font);
        lblRolle1.setText("Rolle 1:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblRolle1, gbc);
        lblRolle1Value = new JLabel();
        Font lblRolle1ValueFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblRolle1Value.getFont());
        if (lblRolle1ValueFont != null) lblRolle1Value.setFont(lblRolle1ValueFont);
        lblRolle1Value.setText("Rolle1Value");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblRolle1Value, gbc);
        lblRolle2 = new JLabel();
        lblRolle2.setText("Rolle 2:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblRolle2, gbc);
        lblRolle2Value = new JLabel();
        lblRolle2Value.setText("Rolle2Value");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblRolle2Value, gbc);
        lblRolle3 = new JLabel();
        lblRolle3.setText("Rolle 3:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblRolle3, gbc);
        lblRolle3Value = new JLabel();
        lblRolle3Value.setText("Rolle3Value");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblRolle3Value, gbc);
        lblMaerchenValue = new JLabel();
        lblMaerchenValue.setText("MaerchenValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel8.add(lblMaerchenValue, gbc);
        final JPanel spacer37 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        panel8.add(spacer37, gbc);
        final JPanel spacer38 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel8.add(spacer38, gbc);
        lblElternmithilfe = new JLabel();
        lblElternmithilfe.setText("Elternmithilfe:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblElternmithilfe, gbc);
        lblElternmithilfeValue = new JLabel();
        lblElternmithilfeValue.setText("EltermithilfeValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblElternmithilfeValue, gbc);
        final JPanel spacer39 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel8.add(spacer39, gbc);
        final JPanel spacer40 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel8.add(spacer40, gbc);
        final JPanel spacer41 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel8.add(spacer41, gbc);
        lblVorstellungenKuchen = new JLabel();
        lblVorstellungenKuchen.setText("Vorstellungen mit Kuchen:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblVorstellungenKuchen, gbc);
        lblVorstellungenKuchenValue = new JLabel();
        lblVorstellungenKuchenValue.setText("VorstellungenKucheValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblVorstellungenKuchenValue, gbc);
        lblBemerkungenMaerchenValue = new JLabel();
        lblBemerkungenMaerchenValue.setText("BemerkungenValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblBemerkungenMaerchenValue, gbc);
        lblBemerkungenMaerchen = new JLabel();
        lblBemerkungenMaerchen.setText("Bemerkungen:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel8.add(lblBemerkungenMaerchen, gbc);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new GridBagLayout());
        maerchenPanel.add(panel9, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lblGruppe = new JLabel();
        Font lblGruppeFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblGruppe.getFont());
        if (lblGruppeFont != null) lblGruppe.setFont(lblGruppeFont);
        lblGruppe.setText("Gruppe:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel9.add(lblGruppe, gbc);
        lblGruppeValue = new JLabel();
        Font lblGruppeValueFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblGruppeValue.getFont());
        if (lblGruppeValueFont != null) lblGruppeValue.setFont(lblGruppeValueFont);
        lblGruppeValue.setText("GruppeValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel9.add(lblGruppeValue, gbc);
        final JPanel spacer42 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel9.add(spacer42, gbc);
        final JPanel spacer43 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel9.add(spacer43, gbc);
        final JPanel spacer44 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel9.add(spacer44, gbc);
        final JPanel spacer45 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        panel9.add(spacer45, gbc);
        final JPanel spacer46 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel9.add(spacer46, gbc);
        lblBilderRolle1Value = new JLabel();
        lblBilderRolle1Value.setText("BilderRolle1Value");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel9.add(lblBilderRolle1Value, gbc);
        lblBilderRolle1 = new JLabel();
        lblBilderRolle1.setText("Bilder Rolle 1:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel9.add(lblBilderRolle1, gbc);
        lblBilderRolle2Value = new JLabel();
        lblBilderRolle2Value.setText("BilderRolle2Value");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel9.add(lblBilderRolle2Value, gbc);
        lblBilderRolle2 = new JLabel();
        lblBilderRolle2.setText("Bilder Rolle 2:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel9.add(lblBilderRolle2, gbc);
        lblBilderRolle3Value = new JLabel();
        lblBilderRolle3Value.setText("BilderRolle3Value");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel9.add(lblBilderRolle3Value, gbc);
        lblBilderRolle3 = new JLabel();
        lblBilderRolle3.setText("Bilder Rolle 3:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel9.add(lblBilderRolle3, gbc);
        final JPanel spacer47 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel9.add(spacer47, gbc);
        lblElternmithilfeCodeValue = new JLabel();
        lblElternmithilfeCodeValue.setText("ElternmithilfeCodeValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel9.add(lblElternmithilfeCodeValue, gbc);
        lblElternmithilfeCode = new JLabel();
        lblElternmithilfeCode.setText("Code:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel9.add(lblElternmithilfeCode, gbc);
        lblZusatzattributValue = new JLabel();
        lblZusatzattributValue.setText("ZusatzattributValue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel9.add(lblZusatzattributValue, gbc);
        lblZusatzattribut = new JLabel();
        lblZusatzattribut.setText("Zusatzattribut:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 0, 0);
        panel9.add(lblZusatzattribut, gbc);
        final JPanel panel10 = new JPanel();
        panel10.setLayout(new GridBagLayout());
        maerchenPanel.add(panel10, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnMaerchenBearbeiten = new JButton();
        btnMaerchenBearbeiten.setText("Details / Bearbeiten");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel10.add(btnMaerchenBearbeiten, gbc);
        final JPanel spacer48 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel10.add(spacer48, gbc);
        final JPanel spacer49 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel10.add(spacer49, gbc);
        final JPanel spacer50 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel10.add(spacer50, gbc);
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(buttonPanel, gbc);
        leftButtonPanel = new JPanel();
        leftButtonPanel.setLayout(new GridBagLayout());
        buttonPanel.add(leftButtonPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnErster = new JButton();
        btnErster.setPreferredSize(new Dimension(143, 29));
        btnErster.setText("Erster");
        btnErster.setMnemonic('E');
        btnErster.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        leftButtonPanel.add(btnErster, gbc);
        final JPanel spacer51 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        leftButtonPanel.add(spacer51, gbc);
        btnVorheriger = new JButton();
        btnVorheriger.setMaximumSize(new Dimension(143, 29));
        btnVorheriger.setMinimumSize(new Dimension(143, 29));
        btnVorheriger.setPreferredSize(new Dimension(143, 29));
        btnVorheriger.setText("Vorheriger");
        btnVorheriger.setMnemonic('V');
        btnVorheriger.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        leftButtonPanel.add(btnVorheriger, gbc);
        final JPanel spacer52 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        leftButtonPanel.add(spacer52, gbc);
        final JPanel spacer53 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        leftButtonPanel.add(spacer53, gbc);
        final JPanel spacer54 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        leftButtonPanel.add(spacer54, gbc);
        lblScrollPosition = new JLabel();
        lblScrollPosition.setText("Scroll-Position");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        leftButtonPanel.add(lblScrollPosition, gbc);
        final JPanel spacer55 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        leftButtonPanel.add(spacer55, gbc);
        rightButtonPanel = new JPanel();
        rightButtonPanel.setLayout(new GridBagLayout());
        buttonPanel.add(rightButtonPanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnNachfolgender = new JButton();
        btnNachfolgender.setPreferredSize(new Dimension(143, 29));
        btnNachfolgender.setText("Nachfolgender");
        btnNachfolgender.setMnemonic('N');
        btnNachfolgender.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rightButtonPanel.add(btnNachfolgender, gbc);
        final JPanel spacer56 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rightButtonPanel.add(spacer56, gbc);
        btnLetzter = new JButton();
        btnLetzter.setPreferredSize(new Dimension(143, 29));
        btnLetzter.setText("Letzter");
        btnLetzter.setMnemonic('L');
        btnLetzter.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rightButtonPanel.add(btnLetzter, gbc);
        final JPanel spacer57 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rightButtonPanel.add(spacer57, gbc);
        btnZurueck = new JButton();
        btnZurueck.setMaximumSize(new Dimension(114, 29));
        btnZurueck.setMinimumSize(new Dimension(114, 29));
        btnZurueck.setPreferredSize(new Dimension(114, 29));
        btnZurueck.setText("Zurück");
        btnZurueck.setMnemonic('Z');
        btnZurueck.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 10);
        rightButtonPanel.add(btnZurueck, gbc);
        final JPanel spacer58 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        rightButtonPanel.add(spacer58, gbc);
        final JPanel spacer59 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        rightButtonPanel.add(spacer59, gbc);
        btnAbbrechen = new JButton();
        btnAbbrechen.setMaximumSize(new Dimension(114, 29));
        btnAbbrechen.setMinimumSize(new Dimension(114, 29));
        btnAbbrechen.setPreferredSize(new Dimension(114, 29));
        btnAbbrechen.setText("Abbrechen");
        btnAbbrechen.setMnemonic('A');
        btnAbbrechen.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 10);
        rightButtonPanel.add(btnAbbrechen, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
