package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.common.utils.Converter;
import ch.metzenthin.svm.dataTypes.Wochentag;
import ch.metzenthin.svm.ui.control.SchuelerSuchenController;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.GregorianCalendar;

/**
 * @author Martin Schraner
 */
public class SchuelerSuchenPanel {
    private SchuelerSuchenController schuelerSuchenController;
    private JPanel panel;
    private JPanel stammdatenPanel;
    private JPanel kursPanel;
    private JPanel codesPanel;
    private JPanel stichtagPanel;
    private JTextField txtNachname;
    private JTextField txtVorname;
    private JTextField txtStrasseHausnummer;
    private JTextField txtPlz;
    private JTextField txtOrt;
    private JTextField txtFestnetz;
    private JTextField txtNatel;
    private JTextField txtEmail;
    private JTextField txtGeburtsdatumSuchperiode;
    private JTextField txtLehrkraft;
    private JTextField txtVon;
    private JTextField txtBis;
    private JTextField txtCodes;
    private JTextField txtStichtag;
    private JRadioButton radioBtnRolleAlle;
    private JRadioButton radioBtnAngemeldet;
    private JRadioButton radioBtnAbgemeldet;
    private JRadioButton radioBtnAnmeldestatusAlle;
    private JRadioButton radioBtnWeiblich;
    private JRadioButton radioBtnMaennlich;
    private JRadioButton radioBtnGeschlechtAlle;
    private JRadioButton radioBtnDispensiert;
    private JRadioButton radioBtnNichtDispensiert;
    private JRadioButton radioBtnDispensationAlle;
    private JRadioButton radioBtnSchueler;
    private JRadioButton radioBtnEltern;
    private JRadioButton radioBtnRechnungsempfaenger;
    private JComboBox<Wochentag> comboBoxWochentag;
    private JButton btnSuchen;
    private JButton btnAbbrechen;
    private JLabel errLblNachname;
    private JLabel errLblVorname;
    private JLabel errLblStrasseHausnummer;
    private JLabel errLblPlz;
    private JLabel errLblOrt;
    private JLabel errLblFestnetz;
    private JLabel errLblNatel;
    private JLabel errLblEmail;
    private JLabel errLblGeburtsdatumSuchperiode;
    private JLabel errLblLehrkraft;
    private JLabel errLblVon;
    private JLabel errLblBis;
    private JLabel errLblCodes;
    private JLabel errLblStichtag;
    private JPanel panelLeft;
    private JPanel panelRight;
    private JPanel statusDispensationGeschlechtPanel;

    public SchuelerSuchenPanel(SvmContext svmContext) {
        $$$setupUI$$$();
        initializeStichtag();
        initializeErrLbls();
        createSchuelerSuchenController(svmContext);
    }

    private void initializeStichtag() {
        txtStichtag.setText(Converter.asString(new GregorianCalendar()));
    }

    private void initializeErrLbls() {
        errLblNachname.setVisible(false);
        errLblNachname.setForeground(Color.RED);
        errLblVorname.setVisible(false);
        errLblVorname.setForeground(Color.RED);
        errLblStrasseHausnummer.setVisible(false);
        errLblStrasseHausnummer.setForeground(Color.RED);
        errLblOrt.setVisible(false);
        errLblOrt.setForeground(Color.RED);
        errLblPlz.setVisible(false);
        errLblPlz.setForeground(Color.RED);
        errLblFestnetz.setVisible(false);
        errLblFestnetz.setForeground(Color.RED);
        errLblNatel.setVisible(false);
        errLblNatel.setForeground(Color.RED);
        errLblEmail.setVisible(false);
        errLblEmail.setForeground(Color.RED);
        errLblGeburtsdatumSuchperiode.setVisible(false);
        errLblGeburtsdatumSuchperiode.setForeground(Color.RED);
        errLblLehrkraft.setVisible(false);
        errLblLehrkraft.setForeground(Color.RED);
        errLblVon.setVisible(false);
        errLblVon.setForeground(Color.RED);
        errLblBis.setVisible(false);
        errLblBis.setForeground(Color.RED);
        errLblCodes.setVisible(false);
        errLblCodes.setForeground(Color.RED);
        errLblStichtag.setVisible(false);
        errLblStichtag.setForeground(Color.RED);
    }

    private void createSchuelerSuchenController(SvmContext svmContext) {
        schuelerSuchenController = new SchuelerSuchenController(svmContext, svmContext.getModelFactory().createSchuelerSuchenModel());
        schuelerSuchenController.setTxtNachname(txtNachname);
        schuelerSuchenController.setTxtVorname(txtVorname);
        schuelerSuchenController.setTxtStrasseHausnummer(txtStrasseHausnummer);
        schuelerSuchenController.setTxtPlz(txtPlz);
        schuelerSuchenController.setTxtOrt(txtOrt);
        schuelerSuchenController.setTxtFestnetz(txtFestnetz);
        schuelerSuchenController.setTxtNatel(txtNatel);
        schuelerSuchenController.setTxtEmail(txtEmail);
        schuelerSuchenController.setTxtGeburtsdatumSuchperiode(txtGeburtsdatumSuchperiode);
        schuelerSuchenController.setTxtLehrkraft(txtLehrkraft);
        schuelerSuchenController.setTxtVon(txtVon);
        schuelerSuchenController.setTxtBis(txtBis);
        schuelerSuchenController.setTxtCodes(txtCodes);
        schuelerSuchenController.setTxtStichtag(txtStichtag);
        schuelerSuchenController.setComboBoxWochentag(comboBoxWochentag);
        schuelerSuchenController.setRadioBtnGroupRolle(radioBtnSchueler, radioBtnEltern, radioBtnRechnungsempfaenger, radioBtnRolleAlle);
        schuelerSuchenController.setRadioBtnGroupAnmeldestatus(radioBtnAngemeldet, radioBtnAbgemeldet, radioBtnAnmeldestatusAlle);
        schuelerSuchenController.setRadioBtnGroupDispensation(radioBtnDispensiert, radioBtnNichtDispensiert, radioBtnDispensationAlle);
        schuelerSuchenController.setRadioBtnGroupGeschlecht(radioBtnWeiblich, radioBtnMaennlich, radioBtnGeschlechtAlle);
        schuelerSuchenController.setErrLblNachname(errLblNachname);
        schuelerSuchenController.setErrLblVorname(errLblVorname);
        schuelerSuchenController.setErrLblStrasseHausnummer(errLblStrasseHausnummer);
        schuelerSuchenController.setErrLblPlz(errLblPlz);
        schuelerSuchenController.setErrLblOrt(errLblOrt);
        schuelerSuchenController.setErrLblFestnetz(errLblFestnetz);
        schuelerSuchenController.setErrLblNatel(errLblNatel);
        schuelerSuchenController.setErrLblEmail(errLblEmail);
        schuelerSuchenController.setErrLblGeburtsdatumSuchperiode(errLblGeburtsdatumSuchperiode);
        schuelerSuchenController.setErrLblStichtag(errLblStichtag);
        schuelerSuchenController.setBtnSuchen(btnSuchen);
        schuelerSuchenController.setBtnAbbrechen(btnAbbrechen);
    }

    private void createUIComponents() {
        comboBoxWochentag = new JComboBox<>(Wochentag.values());
    }

    public void addCloseListener(ActionListener actionListener) {
        schuelerSuchenController.addCloseListener(actionListener);
    }

    public void addNextPanelListener(ActionListener actionListener) {
        schuelerSuchenController.addNextPanelListener(actionListener);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel.add(panel1, BorderLayout.SOUTH);
        btnSuchen = new JButton();
        btnSuchen.setMaximumSize(new Dimension(114, 29));
        btnSuchen.setMinimumSize(new Dimension(114, 29));
        btnSuchen.setPreferredSize(new Dimension(114, 29));
        btnSuchen.setSelected(true);
        btnSuchen.setText("Suchen");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 5, 10, 5);
        panel1.add(btnSuchen, gbc);
        btnAbbrechen = new JButton();
        btnAbbrechen.setMaximumSize(new Dimension(114, 29));
        btnAbbrechen.setMinimumSize(new Dimension(114, 29));
        btnAbbrechen.setPreferredSize(new Dimension(114, 29));
        btnAbbrechen.setText("Abbrechen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 10, 5);
        panel1.add(btnAbbrechen, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(3, 2, new Insets(10, 0, 0, 0), -1, -1, true, false));
        panel.add(panel2, BorderLayout.CENTER);
        panelLeft = new JPanel();
        panelLeft.setLayout(new GridBagLayout());
        panel2.add(panelLeft, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        stammdatenPanel = new JPanel();
        stammdatenPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 10, 0);
        panelLeft.add(stammdatenPanel, gbc);
        stammdatenPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Stammdaten", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(stammdatenPanel.getFont().getName(), Font.BOLD, stammdatenPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label1 = new JLabel();
        label1.setText("Nachname");
        label1.setDisplayedMnemonic('N');
        label1.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label1, gbc);
        txtNachname = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 9;
        gbc.weightx = 0.3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtNachname, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Vorname");
        label2.setDisplayedMnemonic('V');
        label2.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label2, gbc);
        txtVorname = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtVorname, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("PLZ/Ort");
        label3.setDisplayedMnemonic('P');
        label3.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label3, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel3, gbc);
        txtPlz = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(txtPlz, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer1, gbc);
        txtOrt = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 0.8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(txtOrt, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Geburtsdatum");
        label4.setDisplayedMnemonic('G');
        label4.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 15;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label4, gbc);
        txtGeburtsdatumSuchperiode = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 15;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtGeburtsdatumSuchperiode, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 17;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel4, gbc);
        radioBtnSchueler = new JRadioButton();
        radioBtnSchueler.setSelected(true);
        radioBtnSchueler.setText("Schüler");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnSchueler, gbc);
        radioBtnEltern = new JRadioButton();
        radioBtnEltern.setText("Eltern");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnEltern, gbc);
        radioBtnRechnungsempfaenger = new JRadioButton();
        radioBtnRechnungsempfaenger.setText("Rechnungsempfänger");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnRechnungsempfaenger, gbc);
        radioBtnRolleAlle = new JRadioButton();
        radioBtnRolleAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel4.add(radioBtnRolleAlle, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(spacer2, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Rolle");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 17;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Festnetz");
        label6.setDisplayedMnemonic('F');
        label6.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label6, gbc);
        txtFestnetz = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtFestnetz, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Natel");
        label7.setDisplayedMnemonic('A');
        label7.setDisplayedMnemonicIndex(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label7, gbc);
        txtNatel = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtNatel, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Email");
        label8.setDisplayedMnemonic('E');
        label8.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label8, gbc);
        txtEmail = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtEmail, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 11;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(spacer3, gbc);
        txtStrasseHausnummer = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtStrasseHausnummer, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Strasse/Nr.");
        label9.setDisplayedMnemonic('S');
        label9.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label9, gbc);
        errLblVorname = new JLabel();
        errLblVorname.setText("errLblVorname");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 8;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblVorname, gbc);
        errLblStrasseHausnummer = new JLabel();
        errLblStrasseHausnummer.setText("errLblStrasseNummer");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.gridwidth = 10;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblStrasseHausnummer, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel5, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel5.add(spacer4, gbc);
        errLblOrt = new JLabel();
        errLblOrt.setText("errLblOrt");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel5.add(errLblOrt, gbc);
        errLblPlz = new JLabel();
        errLblPlz.setText("errLblPlz");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel5.add(errLblPlz, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel5.add(spacer5, gbc);
        errLblFestnetz = new JLabel();
        errLblFestnetz.setText("errLblFestnetz");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblFestnetz, gbc);
        errLblNatel = new JLabel();
        errLblNatel.setText("errLblNatel");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblNatel, gbc);
        errLblEmail = new JLabel();
        errLblEmail.setText("errLblEmail");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblEmail, gbc);
        errLblGeburtsdatumSuchperiode = new JLabel();
        errLblGeburtsdatumSuchperiode.setText("errLblGeburtsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 14;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblGeburtsdatumSuchperiode, gbc);
        errLblNachname = new JLabel();
        errLblNachname.setText("errrLblNachname");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblNachname, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        stammdatenPanel.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer11, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer12, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer13, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 16;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer14, gbc);
        final JPanel spacer15 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(spacer15, gbc);
        final JPanel spacer16 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer16, gbc);
        final JPanel spacer17 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 18;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer17, gbc);
        statusDispensationGeschlechtPanel = new JPanel();
        statusDispensationGeschlechtPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        panelLeft.add(statusDispensationGeschlechtPanel, gbc);
        statusDispensationGeschlechtPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Status, Dispensation, Geschlecht", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(statusDispensationGeschlechtPanel.getFont().getName(), Font.BOLD, statusDispensationGeschlechtPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label10 = new JLabel();
        label10.setText("Status");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        statusDispensationGeschlechtPanel.add(label10, gbc);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        statusDispensationGeschlechtPanel.add(panel6, gbc);
        radioBtnAngemeldet = new JRadioButton();
        radioBtnAngemeldet.setSelected(true);
        radioBtnAngemeldet.setText("angemeldet");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel6.add(radioBtnAngemeldet, gbc);
        radioBtnAbgemeldet = new JRadioButton();
        radioBtnAbgemeldet.setText("abgemeldet");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel6.add(radioBtnAbgemeldet, gbc);
        radioBtnAnmeldestatusAlle = new JRadioButton();
        radioBtnAnmeldestatusAlle.setSelected(false);
        radioBtnAnmeldestatusAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel6.add(radioBtnAnmeldestatusAlle, gbc);
        final JPanel spacer18 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(spacer18, gbc);
        final JPanel spacer19 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        statusDispensationGeschlechtPanel.add(spacer19, gbc);
        final JLabel label11 = new JLabel();
        label11.setText("Dispensation");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        statusDispensationGeschlechtPanel.add(label11, gbc);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        statusDispensationGeschlechtPanel.add(panel7, gbc);
        radioBtnDispensiert = new JRadioButton();
        radioBtnDispensiert.setSelected(false);
        radioBtnDispensiert.setText("dispensiert");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel7.add(radioBtnDispensiert, gbc);
        radioBtnNichtDispensiert = new JRadioButton();
        radioBtnNichtDispensiert.setText("nicht dispensiert");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel7.add(radioBtnNichtDispensiert, gbc);
        radioBtnDispensationAlle = new JRadioButton();
        radioBtnDispensationAlle.setSelected(true);
        radioBtnDispensationAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel7.add(radioBtnDispensationAlle, gbc);
        final JPanel spacer20 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel7.add(spacer20, gbc);
        final JLabel label12 = new JLabel();
        label12.setText("Geschlecht");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        statusDispensationGeschlechtPanel.add(label12, gbc);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.BOTH;
        statusDispensationGeschlechtPanel.add(panel8, gbc);
        radioBtnWeiblich = new JRadioButton();
        radioBtnWeiblich.setText("weiblich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel8.add(radioBtnWeiblich, gbc);
        radioBtnMaennlich = new JRadioButton();
        radioBtnMaennlich.setText("männlich");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel8.add(radioBtnMaennlich, gbc);
        radioBtnGeschlechtAlle = new JRadioButton();
        radioBtnGeschlechtAlle.setSelected(true);
        radioBtnGeschlechtAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel8.add(radioBtnGeschlechtAlle, gbc);
        final JPanel spacer21 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel8.add(spacer21, gbc);
        final JPanel spacer22 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        statusDispensationGeschlechtPanel.add(spacer22, gbc);
        final JPanel spacer23 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        statusDispensationGeschlechtPanel.add(spacer23, gbc);
        final JPanel spacer24 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer24, gbc);
        final JPanel spacer25 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer25, gbc);
        final JPanel spacer26 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer26, gbc);
        final JPanel spacer27 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer27, gbc);
        panelRight = new JPanel();
        panelRight.setLayout(new GridBagLayout());
        panel2.add(panelRight, new GridConstraints(1, 1, 2, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        kursPanel = new JPanel();
        kursPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 10);
        panelRight.add(kursPanel, gbc);
        kursPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Kurs", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(kursPanel.getFont().getName(), Font.BOLD, kursPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label13 = new JLabel();
        label13.setText("Lehrkraft");
        label13.setDisplayedMnemonic('L');
        label13.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label13, gbc);
        final JPanel spacer28 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer28, gbc);
        txtLehrkraft = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(txtLehrkraft, gbc);
        final JPanel spacer29 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(spacer29, gbc);
        final JPanel spacer30 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(spacer30, gbc);
        final JLabel label14 = new JLabel();
        label14.setText("Wochentag");
        label14.setDisplayedMnemonic('W');
        label14.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label14, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(comboBoxWochentag, gbc);
        final JPanel spacer31 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer31, gbc);
        final JLabel label15 = new JLabel();
        label15.setText("Zeit");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label15, gbc);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        kursPanel.add(panel9, gbc);
        final JLabel label16 = new JLabel();
        label16.setText("bis");
        label16.setDisplayedMnemonic('I');
        label16.setDisplayedMnemonicIndex(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel9.add(label16, gbc);
        txtBis = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        panel9.add(txtBis, gbc);
        txtVon = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 5);
        panel9.add(txtVon, gbc);
        final JLabel label17 = new JLabel();
        label17.setText("von");
        label17.setDisplayedMnemonic('O');
        label17.setDisplayedMnemonicIndex(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel9.add(label17, gbc);
        final JPanel spacer32 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer32, gbc);
        errLblLehrkraft = new JLabel();
        errLblLehrkraft.setText("errLblLehrkraft");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(errLblLehrkraft, gbc);
        errLblVon = new JLabel();
        errLblVon.setText("errLblVon");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(errLblVon, gbc);
        errLblBis = new JLabel();
        errLblBis.setText("errLblBis");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(errLblBis, gbc);
        final JPanel spacer33 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(spacer33, gbc);
        final JPanel spacer34 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        kursPanel.add(spacer34, gbc);
        final JPanel spacer35 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer35, gbc);
        codesPanel = new JPanel();
        codesPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 10, 10);
        panelRight.add(codesPanel, gbc);
        codesPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Codes", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(codesPanel.getFont().getName(), Font.BOLD, codesPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label18 = new JLabel();
        label18.setText("Codes");
        label18.setDisplayedMnemonic('C');
        label18.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(label18, gbc);
        txtCodes = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(txtCodes, gbc);
        final JPanel spacer36 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(spacer36, gbc);
        errLblCodes = new JLabel();
        errLblCodes.setText("errLblCodes");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        codesPanel.add(errLblCodes, gbc);
        final JPanel spacer37 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(spacer37, gbc);
        final JPanel spacer38 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        codesPanel.add(spacer38, gbc);
        final JPanel spacer39 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        codesPanel.add(spacer39, gbc);
        final JPanel spacer40 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        codesPanel.add(spacer40, gbc);
        stichtagPanel = new JPanel();
        stichtagPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 10, 10);
        panelRight.add(stichtagPanel, gbc);
        stichtagPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Stichtag für Suche", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(stichtagPanel.getFont().getName(), Font.BOLD, stichtagPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label19 = new JLabel();
        label19.setText("Stichtag");
        label19.setDisplayedMnemonic('T');
        label19.setDisplayedMnemonicIndex(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        stichtagPanel.add(label19, gbc);
        final JPanel spacer41 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        stichtagPanel.add(spacer41, gbc);
        txtStichtag = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stichtagPanel.add(txtStichtag, gbc);
        final JPanel spacer42 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stichtagPanel.add(spacer42, gbc);
        final JPanel spacer43 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stichtagPanel.add(spacer43, gbc);
        errLblStichtag = new JLabel();
        errLblStichtag.setText("errLblStichtag");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        stichtagPanel.add(errLblStichtag, gbc);
        final JPanel spacer44 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        stichtagPanel.add(spacer44, gbc);
        final JPanel spacer45 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        stichtagPanel.add(spacer45, gbc);
        label1.setLabelFor(txtNachname);
        label2.setLabelFor(txtVorname);
        label3.setLabelFor(txtPlz);
        label4.setLabelFor(txtGeburtsdatumSuchperiode);
        label6.setLabelFor(txtFestnetz);
        label7.setLabelFor(txtNatel);
        label8.setLabelFor(txtEmail);
        label9.setLabelFor(txtStrasseHausnummer);
        label13.setLabelFor(txtLehrkraft);
        label14.setLabelFor(comboBoxWochentag);
        label16.setLabelFor(txtBis);
        label17.setLabelFor(txtVon);
        label18.setLabelFor(txtCodes);
        label19.setLabelFor(txtStichtag);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnSchueler);
        buttonGroup.add(radioBtnEltern);
        buttonGroup.add(radioBtnRechnungsempfaenger);
        buttonGroup.add(radioBtnRolleAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnAngemeldet);
        buttonGroup.add(radioBtnAbgemeldet);
        buttonGroup.add(radioBtnAnmeldestatusAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnDispensiert);
        buttonGroup.add(radioBtnNichtDispensiert);
        buttonGroup.add(radioBtnDispensationAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnWeiblich);
        buttonGroup.add(radioBtnMaennlich);
        buttonGroup.add(radioBtnGeschlechtAlle);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
