package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.common.dataTypes.Gruppe;
import ch.metzenthin.svm.common.dataTypes.Wochentag;
import ch.metzenthin.svm.domain.model.SchuelerSuchenModel;
import ch.metzenthin.svm.persistence.entities.ElternmithilfeCode;
import ch.metzenthin.svm.persistence.entities.Mitarbeiter;
import ch.metzenthin.svm.persistence.entities.SchuelerCode;
import ch.metzenthin.svm.ui.control.SchuelerSuchenController;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author Martin Schraner
 */
public class SchuelerSuchenPanel {
    private final SvmContext svmContext;
    private SchuelerSuchenController schuelerSuchenController;
    private JPanel panel;
    private JPanel stammdatenPanel;
    private JPanel kursPanel;
    private JPanel codesPanel;
    private JPanel panelLeft;
    private JPanel panelRight;
    private JPanel statusDispensationGeschlechtPanel;
    private JPanel buttonPanel;
    private JPanel datenPanel;
    private JPanel titelPanel;
    private JPanel suchenPanel;
    private JPanel maerchenPanel;
    private JTextField txtNachname;
    private JTextField txtVorname;
    private JTextField txtStrasseHausnummer;
    private JTextField txtPlz;
    private JTextField txtOrt;
    private JTextField txtFestnetz;
    private JTextField txtNatel;
    private JTextField txtEmail;
    private JTextField txtGeburtsdatumSuchperiode;
    private JTextField txtStichtag;
    private JTextField txtZeitBeginn;
    private JTextField txtKuchenVorstellung;
    private JTextField txtZusatzattributMaerchen;
    private JTextArea txtAreaRollen;
    private JRadioButton radioBtnRolleAlle;
    private JRadioButton radioBtnAngemeldet;
    private JRadioButton radioBtnAbgemeldet;
    private JRadioButton radioBtnAnmeldestatusAlle;
    private JRadioButton radioBtnWeiblich;
    private JRadioButton radioBtnMaennlich;
    private JRadioButton radioBtnGeschlechtAlle;
    private JRadioButton radioBtnDispensiert;
    private JRadioButton radioBtnNichtDispensiert;
    private JRadioButton radioBtnDispensationAlle;
    private JRadioButton radioBtnSchueler;
    private JRadioButton radioBtnEltern;
    private JRadioButton radioBtnRechnungsempfaenger;
    private JSpinner spinnerSemesterKurs;
    private JSpinner spinnerMaerchen;
    private JComboBox<Wochentag> comboBoxWochentag;
    private JComboBox<Mitarbeiter> comboBoxLehrkraft;
    private JComboBox<SchuelerCode> comboBoxSchuelerCode;
    private JComboBox<Gruppe> comboBoxGruppe;
    private JComboBox<ElternmithilfeCode> comboBoxElternmithilfeCode;
    private JButton btnSuchen;
    private JButton btnAbbrechen;
    private JLabel errLblNachname;
    private JLabel errLblVorname;
    private JLabel errLblStrasseHausnummer;
    private JLabel errLblPlz;
    private JLabel errLblOrt;
    private JLabel errLblFestnetz;
    private JLabel errLblNatel;
    private JLabel errLblEmail;
    private JLabel errLblGeburtsdatumSuchperiode;
    private JLabel errLblStichtag;
    private JLabel errLblZeitBeginn;
    private JLabel errLblRollen;
    private JLabel errLblKuchenVorstellung;
    private JLabel errLblZusatzattributMaerchen;
    private JCheckBox checkBoxKursFuerSucheBeruecksichtigen;
    private JCheckBox checkBoxMaerchenFuerSucheBeruecksichtigen;
    private SchuelerSuchenModel schuelerSuchenModel;
    private ActionListener nextPanelListener;

    public SchuelerSuchenPanel(SvmContext svmContext) {
        this.svmContext = svmContext;
        $$$setupUI$$$();
        schuelerSuchenModel = svmContext.getModelFactory().createSchuelerSuchenModel();
        initializeErrLbls();
        createSchuelerSuchenController();
    }

    private void initializeErrLbls() {
        errLblNachname.setVisible(false);
        errLblNachname.setForeground(Color.RED);
        errLblVorname.setVisible(false);
        errLblVorname.setForeground(Color.RED);
        errLblStrasseHausnummer.setVisible(false);
        errLblStrasseHausnummer.setForeground(Color.RED);
        errLblOrt.setVisible(false);
        errLblOrt.setForeground(Color.RED);
        errLblPlz.setVisible(false);
        errLblPlz.setForeground(Color.RED);
        errLblFestnetz.setVisible(false);
        errLblFestnetz.setForeground(Color.RED);
        errLblNatel.setVisible(false);
        errLblNatel.setForeground(Color.RED);
        errLblEmail.setVisible(false);
        errLblEmail.setForeground(Color.RED);
        errLblGeburtsdatumSuchperiode.setVisible(false);
        errLblGeburtsdatumSuchperiode.setForeground(Color.RED);
        errLblStichtag.setVisible(false);
        errLblStichtag.setForeground(Color.RED);
        errLblZeitBeginn.setVisible(false);
        errLblZeitBeginn.setForeground(Color.RED);
        errLblKuchenVorstellung.setVisible(false);
        errLblKuchenVorstellung.setForeground(Color.RED);
        errLblRollen.setVisible(false);
        errLblRollen.setForeground(Color.RED);
        errLblZusatzattributMaerchen.setVisible(false);
        errLblZusatzattributMaerchen.setForeground(Color.RED);
    }

    private void createSchuelerSuchenController() {
        schuelerSuchenController = new SchuelerSuchenController(svmContext, schuelerSuchenModel);
        schuelerSuchenController.setTxtNachname(txtNachname);
        schuelerSuchenController.setTxtVorname(txtVorname);
        schuelerSuchenController.setTxtStrasseHausnummer(txtStrasseHausnummer);
        schuelerSuchenController.setTxtPlz(txtPlz);
        schuelerSuchenController.setTxtOrt(txtOrt);
        schuelerSuchenController.setTxtFestnetz(txtFestnetz);
        schuelerSuchenController.setTxtNatel(txtNatel);
        schuelerSuchenController.setTxtEmail(txtEmail);
        schuelerSuchenController.setTxtGeburtsdatumSuchperiode(txtGeburtsdatumSuchperiode);
        schuelerSuchenController.setTxtZeitBeginn(txtZeitBeginn);
        schuelerSuchenController.setTxtStichtag(txtStichtag);
        schuelerSuchenController.setTxtKuchenVorstellung(txtKuchenVorstellung);
        schuelerSuchenController.setTxtZusatzattributMaerchen(txtZusatzattributMaerchen);
        schuelerSuchenController.setTxtAreaRollen(txtAreaRollen);
        schuelerSuchenController.setSpinnerSemesterKurs(spinnerSemesterKurs);
        schuelerSuchenController.setSpinnerMaerchen(spinnerMaerchen);
        schuelerSuchenController.setComboBoxSchuelerCode(comboBoxSchuelerCode);
        schuelerSuchenController.setComboBoxWochentag(comboBoxWochentag);
        schuelerSuchenController.setComboBoxLehrkraft(comboBoxLehrkraft);
        schuelerSuchenController.setComboBoxGruppe(comboBoxGruppe);
        schuelerSuchenController.setComboBoxElternmithilfeCode(comboBoxElternmithilfeCode);
        schuelerSuchenController.setCheckBoxKursFuerSucheBeruecksichtigen(checkBoxKursFuerSucheBeruecksichtigen);
        schuelerSuchenController.setCheckBoxMaerchenFuerSucheBeruecksichtigen(checkBoxMaerchenFuerSucheBeruecksichtigen);
        schuelerSuchenController.setRadioBtnGroupRolle(radioBtnSchueler, radioBtnEltern, radioBtnRechnungsempfaenger, radioBtnRolleAlle);
        schuelerSuchenController.setRadioBtnGroupAnmeldestatus(radioBtnAngemeldet, radioBtnAbgemeldet, radioBtnAnmeldestatusAlle);
        schuelerSuchenController.setRadioBtnGroupDispensation(radioBtnDispensiert, radioBtnNichtDispensiert, radioBtnDispensationAlle);
        schuelerSuchenController.setRadioBtnGroupGeschlecht(radioBtnWeiblich, radioBtnMaennlich, radioBtnGeschlechtAlle);
        schuelerSuchenController.setErrLblNachname(errLblNachname);
        schuelerSuchenController.setErrLblVorname(errLblVorname);
        schuelerSuchenController.setErrLblStrasseHausnummer(errLblStrasseHausnummer);
        schuelerSuchenController.setErrLblPlz(errLblPlz);
        schuelerSuchenController.setErrLblOrt(errLblOrt);
        schuelerSuchenController.setErrLblFestnetz(errLblFestnetz);
        schuelerSuchenController.setErrLblNatel(errLblNatel);
        schuelerSuchenController.setErrLblEmail(errLblEmail);
        schuelerSuchenController.setErrLblGeburtsdatumSuchperiode(errLblGeburtsdatumSuchperiode);
        schuelerSuchenController.setErrLblStichtag(errLblStichtag);
        schuelerSuchenController.setErrLblZeitBeginn(errLblZeitBeginn);
        schuelerSuchenController.setErrLblRollen(errLblRollen);
        schuelerSuchenController.setErrLblKuchenVorstellung(errLblKuchenVorstellung);
        schuelerSuchenController.setErrLblZusatzattributMaerchen(errLblZusatzattributMaerchen);
        schuelerSuchenController.setBtnSuchen(btnSuchen);
        schuelerSuchenController.setBtnAbbrechen(btnAbbrechen);
        schuelerSuchenController.addZurueckListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onZurueck();
            }
        });
    }

    private void createUIComponents() {
        spinnerSemesterKurs = new JSpinner();
        spinnerMaerchen = new JSpinner();
        comboBoxWochentag = new JComboBox<>();
        comboBoxLehrkraft = new JComboBox<>();
        comboBoxSchuelerCode = new JComboBox<>();
        comboBoxGruppe = new JComboBox<>();
        comboBoxElternmithilfeCode = new JComboBox<>();
    }

    private void onZurueck() {
        nextPanelListener.actionPerformed(new ActionEvent(new Object[]{$$$getRootComponent$$$(), "Schüler suchen", Boolean.TRUE}, ActionEvent.ACTION_PERFORMED, "Zurück zu Schüler suchen"));
    }

    public void addCloseListener(ActionListener actionListener) {
        schuelerSuchenController.addCloseListener(actionListener);
    }

    public void addNextPanelListener(ActionListener nextPanelListener) {
        this.nextPanelListener = nextPanelListener;
        schuelerSuchenController.addNextPanelListener(nextPanelListener);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridBagLayout());
        panel.add(buttonPanel, BorderLayout.SOUTH);
        btnSuchen = new JButton();
        btnSuchen.setMaximumSize(new Dimension(114, 29));
        btnSuchen.setMinimumSize(new Dimension(114, 29));
        btnSuchen.setPreferredSize(new Dimension(114, 29));
        btnSuchen.setSelected(true);
        btnSuchen.setText("Suchen");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 5);
        buttonPanel.add(btnSuchen, gbc);
        btnAbbrechen = new JButton();
        btnAbbrechen.setMaximumSize(new Dimension(114, 29));
        btnAbbrechen.setMinimumSize(new Dimension(114, 29));
        btnAbbrechen.setPreferredSize(new Dimension(114, 29));
        btnAbbrechen.setText("Abbrechen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 5);
        buttonPanel.add(btnAbbrechen, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttonPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttonPanel.add(spacer2, gbc);
        datenPanel = new JPanel();
        datenPanel.setLayout(new GridBagLayout());
        panel.add(datenPanel, BorderLayout.CENTER);
        titelPanel = new JPanel();
        titelPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 20, 10);
        datenPanel.add(titelPanel, gbc);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 36));
        label1.setText("Schüler suchen");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        titelPanel.add(label1, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        titelPanel.add(spacer3, gbc);
        suchenPanel = new JPanel();
        suchenPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        datenPanel.add(suchenPanel, gbc);
        panelLeft = new JPanel();
        panelLeft.setLayout(new GridBagLayout());
        suchenPanel.add(panelLeft, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        stammdatenPanel = new JPanel();
        stammdatenPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 10, 0);
        panelLeft.add(stammdatenPanel, gbc);
        stammdatenPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Stammdaten", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(stammdatenPanel.getFont().getName(), Font.BOLD, stammdatenPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label2 = new JLabel();
        label2.setText("Nachname");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label2, gbc);
        txtNachname = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 9;
        gbc.weightx = 0.3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtNachname, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Vorname");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label3, gbc);
        txtVorname = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtVorname, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("PLZ/Ort");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label4, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel1, gbc);
        txtPlz = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(txtPlz, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer4, gbc);
        txtOrt = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 0.8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(txtOrt, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Geburtsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 15;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label5, gbc);
        txtGeburtsdatumSuchperiode = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 15;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtGeburtsdatumSuchperiode, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 19;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel2, gbc);
        radioBtnSchueler = new JRadioButton();
        radioBtnSchueler.setText("Schüler");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel2.add(radioBtnSchueler, gbc);
        radioBtnEltern = new JRadioButton();
        radioBtnEltern.setText("Eltern");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel2.add(radioBtnEltern, gbc);
        radioBtnRechnungsempfaenger = new JRadioButton();
        radioBtnRechnungsempfaenger.setText("Rechnungsempfänger");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel2.add(radioBtnRechnungsempfaenger, gbc);
        radioBtnRolleAlle = new JRadioButton();
        radioBtnRolleAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(radioBtnRolleAlle, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Rolle");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 19;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Festnetz");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label7, gbc);
        txtFestnetz = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtFestnetz, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Natel");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label8, gbc);
        txtNatel = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtNatel, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Email");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label9, gbc);
        txtEmail = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtEmail, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 11;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(spacer6, gbc);
        txtStrasseHausnummer = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtStrasseHausnummer, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Strasse/Nr.");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label10, gbc);
        errLblVorname = new JLabel();
        errLblVorname.setText("errLblVorname");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 8;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblVorname, gbc);
        errLblStrasseHausnummer = new JLabel();
        errLblStrasseHausnummer.setText("errLblStrasseNummer");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.gridwidth = 10;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblStrasseHausnummer, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel3, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer7, gbc);
        errLblOrt = new JLabel();
        errLblOrt.setText("errLblOrt");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(errLblOrt, gbc);
        errLblPlz = new JLabel();
        errLblPlz.setText("errLblPlz");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(errLblPlz, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer8, gbc);
        errLblFestnetz = new JLabel();
        errLblFestnetz.setText("errLblFestnetz");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblFestnetz, gbc);
        errLblNatel = new JLabel();
        errLblNatel.setText("errLblNatel");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblNatel, gbc);
        errLblEmail = new JLabel();
        errLblEmail.setText("errLblEmail");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblEmail, gbc);
        errLblGeburtsdatumSuchperiode = new JLabel();
        errLblGeburtsdatumSuchperiode.setText("errLblGeburtsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 14;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblGeburtsdatumSuchperiode, gbc);
        errLblNachname = new JLabel();
        errLblNachname.setText("errrLblNachname");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblNachname, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        stammdatenPanel.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer11, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer12, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer13, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer14, gbc);
        final JPanel spacer15 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer15, gbc);
        final JPanel spacer16 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer16, gbc);
        final JPanel spacer17 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 16;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer17, gbc);
        final JPanel spacer18 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(spacer18, gbc);
        final JPanel spacer19 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer19, gbc);
        final JPanel spacer20 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 20;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer20, gbc);
        final JLabel label11 = new JLabel();
        label11.setText("Geschlecht");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 17;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label11, gbc);
        final JPanel spacer21 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 18;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer21, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 17;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel4, gbc);
        radioBtnWeiblich = new JRadioButton();
        radioBtnWeiblich.setText("weiblich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnWeiblich, gbc);
        radioBtnMaennlich = new JRadioButton();
        radioBtnMaennlich.setText("männlich");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnMaennlich, gbc);
        radioBtnGeschlechtAlle = new JRadioButton();
        radioBtnGeschlechtAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel4.add(radioBtnGeschlechtAlle, gbc);
        final JPanel spacer22 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(spacer22, gbc);
        statusDispensationGeschlechtPanel = new JPanel();
        statusDispensationGeschlechtPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        panelLeft.add(statusDispensationGeschlechtPanel, gbc);
        statusDispensationGeschlechtPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Status, Dispensation", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(statusDispensationGeschlechtPanel.getFont().getName(), Font.BOLD, statusDispensationGeschlechtPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label12 = new JLabel();
        label12.setText("Status");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        statusDispensationGeschlechtPanel.add(label12, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        statusDispensationGeschlechtPanel.add(panel5, gbc);
        radioBtnAngemeldet = new JRadioButton();
        radioBtnAngemeldet.setText("angemeldet");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel5.add(radioBtnAngemeldet, gbc);
        radioBtnAbgemeldet = new JRadioButton();
        radioBtnAbgemeldet.setText("abgemeldet");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel5.add(radioBtnAbgemeldet, gbc);
        radioBtnAnmeldestatusAlle = new JRadioButton();
        radioBtnAnmeldestatusAlle.setSelected(false);
        radioBtnAnmeldestatusAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel5.add(radioBtnAnmeldestatusAlle, gbc);
        final JPanel spacer23 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel5.add(spacer23, gbc);
        final JPanel spacer24 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        statusDispensationGeschlechtPanel.add(spacer24, gbc);
        final JLabel label13 = new JLabel();
        label13.setText("Dispensation");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        statusDispensationGeschlechtPanel.add(label13, gbc);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        statusDispensationGeschlechtPanel.add(panel6, gbc);
        radioBtnDispensiert = new JRadioButton();
        radioBtnDispensiert.setSelected(false);
        radioBtnDispensiert.setText("dispensiert");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel6.add(radioBtnDispensiert, gbc);
        radioBtnNichtDispensiert = new JRadioButton();
        radioBtnNichtDispensiert.setText("nicht dispensiert");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel6.add(radioBtnNichtDispensiert, gbc);
        radioBtnDispensationAlle = new JRadioButton();
        radioBtnDispensationAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel6.add(radioBtnDispensationAlle, gbc);
        final JPanel spacer25 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(spacer25, gbc);
        final JPanel spacer26 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        statusDispensationGeschlechtPanel.add(spacer26, gbc);
        final JPanel spacer27 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        statusDispensationGeschlechtPanel.add(spacer27, gbc);
        final JPanel spacer28 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer28, gbc);
        final JPanel spacer29 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer29, gbc);
        final JPanel spacer30 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer30, gbc);
        final JLabel label14 = new JLabel();
        label14.setText("Stichtag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        statusDispensationGeschlechtPanel.add(label14, gbc);
        txtStichtag = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        statusDispensationGeschlechtPanel.add(txtStichtag, gbc);
        errLblStichtag = new JLabel();
        errLblStichtag.setText("errLblStichtag");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        statusDispensationGeschlechtPanel.add(errLblStichtag, gbc);
        final JPanel spacer31 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer31, gbc);
        codesPanel = new JPanel();
        codesPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        panelLeft.add(codesPanel, gbc);
        codesPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Schüler-Code", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(codesPanel.getFont().getName(), Font.BOLD, codesPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label15 = new JLabel();
        label15.setText("Code");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(label15, gbc);
        final JPanel spacer32 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(spacer32, gbc);
        final JPanel spacer33 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(spacer33, gbc);
        final JPanel spacer34 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        codesPanel.add(spacer34, gbc);
        final JPanel spacer35 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        codesPanel.add(spacer35, gbc);
        final JPanel spacer36 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        codesPanel.add(spacer36, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(comboBoxSchuelerCode, gbc);
        final JPanel spacer37 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(spacer37, gbc);
        panelRight = new JPanel();
        panelRight.setLayout(new GridBagLayout());
        suchenPanel.add(panelRight, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        kursPanel = new JPanel();
        kursPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 10);
        panelRight.add(kursPanel, gbc);
        kursPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Kurs", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(kursPanel.getFont().getName(), Font.BOLD, kursPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label16 = new JLabel();
        label16.setText("Wochentag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label16, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(comboBoxWochentag, gbc);
        final JPanel spacer38 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer38, gbc);
        final JLabel label17 = new JLabel();
        label17.setText("Zeit Beginn");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label17, gbc);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        kursPanel.add(panel7, gbc);
        txtZeitBeginn = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel7.add(txtZeitBeginn, gbc);
        final JPanel spacer39 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer39, gbc);
        errLblZeitBeginn = new JLabel();
        errLblZeitBeginn.setText("errLblVon");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(errLblZeitBeginn, gbc);
        final JPanel spacer40 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        kursPanel.add(spacer40, gbc);
        final JPanel spacer41 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer41, gbc);
        final JPanel spacer42 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer42, gbc);
        final JLabel label18 = new JLabel();
        label18.setText("Schuljahr, Semester");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label18, gbc);
        final JLabel label19 = new JLabel();
        label19.setText("Für Suche berücksichtigen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label19, gbc);
        checkBoxKursFuerSucheBeruecksichtigen = new JCheckBox();
        checkBoxKursFuerSucheBeruecksichtigen.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(checkBoxKursFuerSucheBeruecksichtigen, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(comboBoxLehrkraft, gbc);
        final JLabel label20 = new JLabel();
        label20.setText("Lehrkraft");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label20, gbc);
        final JPanel spacer43 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(spacer43, gbc);
        final JPanel spacer44 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(spacer44, gbc);
        final JPanel spacer45 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer45, gbc);
        final JPanel spacer46 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer46, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(spinnerSemesterKurs, gbc);
        maerchenPanel = new JPanel();
        maerchenPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 10, 10);
        panelRight.add(maerchenPanel, gbc);
        maerchenPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Märchen", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(maerchenPanel.getFont().getName(), Font.BOLD, maerchenPanel.getFont().getSize())));
        final JLabel label21 = new JLabel();
        label21.setText("Märchen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(label21, gbc);
        final JPanel spacer47 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        maerchenPanel.add(spacer47, gbc);
        final JPanel spacer48 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        maerchenPanel.add(spacer48, gbc);
        final JPanel spacer49 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        maerchenPanel.add(spacer49, gbc);
        final JPanel spacer50 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        maerchenPanel.add(spacer50, gbc);
        final JPanel spacer51 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        maerchenPanel.add(spacer51, gbc);
        final JLabel label22 = new JLabel();
        label22.setText("Gruppe");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(label22, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        maerchenPanel.add(comboBoxGruppe, gbc);
        final JPanel spacer52 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        maerchenPanel.add(spacer52, gbc);
        final JLabel label23 = new JLabel();
        label23.setText("Rolle(n)");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(label23, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 40;
        maerchenPanel.add(scrollPane1, gbc);
        txtAreaRollen = new JTextArea();
        txtAreaRollen.setLineWrap(true);
        txtAreaRollen.setWrapStyleWord(true);
        scrollPane1.setViewportView(txtAreaRollen);
        final JPanel spacer53 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        maerchenPanel.add(spacer53, gbc);
        final JLabel label24 = new JLabel();
        label24.setText("Elternmithilfe-Code");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(label24, gbc);
        final JLabel label25 = new JLabel();
        label25.setText("Vorstellung mit Kuchen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(label25, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        maerchenPanel.add(comboBoxElternmithilfeCode, gbc);
        final JPanel spacer54 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        maerchenPanel.add(spacer54, gbc);
        final JPanel spacer55 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        maerchenPanel.add(spacer55, gbc);
        final JLabel label26 = new JLabel();
        label26.setText("Zusatzattribut");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(label26, gbc);
        final JPanel spacer56 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.VERTICAL;
        maerchenPanel.add(spacer56, gbc);
        txtZusatzattributMaerchen = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        maerchenPanel.add(txtZusatzattributMaerchen, gbc);
        errLblRollen = new JLabel();
        errLblRollen.setText("errLblRollen");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(errLblRollen, gbc);
        errLblZusatzattributMaerchen = new JLabel();
        errLblZusatzattributMaerchen.setText("errLblZusatzattribut");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(errLblZusatzattributMaerchen, gbc);
        final JLabel label27 = new JLabel();
        label27.setText("Für Suche berücksichtigen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(label27, gbc);
        final JPanel spacer57 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.VERTICAL;
        maerchenPanel.add(spacer57, gbc);
        checkBoxMaerchenFuerSucheBeruecksichtigen = new JCheckBox();
        checkBoxMaerchenFuerSucheBeruecksichtigen.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(checkBoxMaerchenFuerSucheBeruecksichtigen, gbc);
        txtKuchenVorstellung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        maerchenPanel.add(txtKuchenVorstellung, gbc);
        errLblKuchenVorstellung = new JLabel();
        errLblKuchenVorstellung.setText("errLblKuchenVorstellung");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        maerchenPanel.add(errLblKuchenVorstellung, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        maerchenPanel.add(spinnerMaerchen, gbc);
        final JPanel spacer58 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        datenPanel.add(spacer58, gbc);
        label2.setLabelFor(txtNachname);
        label3.setLabelFor(txtVorname);
        label4.setLabelFor(txtPlz);
        label5.setLabelFor(txtGeburtsdatumSuchperiode);
        label7.setLabelFor(txtFestnetz);
        label8.setLabelFor(txtNatel);
        label9.setLabelFor(txtEmail);
        label10.setLabelFor(txtStrasseHausnummer);
        label14.setLabelFor(txtStichtag);
        label15.setLabelFor(comboBoxSchuelerCode);
        label16.setLabelFor(comboBoxWochentag);
        label17.setLabelFor(txtZeitBeginn);
        label18.setLabelFor(spinnerSemesterKurs);
        label20.setLabelFor(comboBoxLehrkraft);
        label21.setLabelFor(spinnerMaerchen);
        label22.setLabelFor(comboBoxGruppe);
        label23.setLabelFor(txtAreaRollen);
        label24.setLabelFor(comboBoxElternmithilfeCode);
        label25.setLabelFor(txtKuchenVorstellung);
        label26.setLabelFor(txtZusatzattributMaerchen);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnSchueler);
        buttonGroup.add(radioBtnEltern);
        buttonGroup.add(radioBtnRechnungsempfaenger);
        buttonGroup.add(radioBtnRolleAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnAngemeldet);
        buttonGroup.add(radioBtnAbgemeldet);
        buttonGroup.add(radioBtnAnmeldestatusAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnDispensiert);
        buttonGroup.add(radioBtnNichtDispensiert);
        buttonGroup.add(radioBtnDispensationAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnWeiblich);
        buttonGroup.add(radioBtnMaennlich);
        buttonGroup.add(radioBtnGeschlechtAlle);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
