package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.domain.model.SchuelerModel;
import ch.metzenthin.svm.ui.control.CompletedListener;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;

/**
 * @author Hans Stamm
 */
public class SchuelerErfassenTabbedPane {
    private JTabbedPane schuelerErfassenTabbedPane;
    private JPanel panel1;
    private SchuelerPanel schuelerPanel;
    private AngehoerigerPanel elternteilEinsPanel;
    private JPanel panel;
    private JPanel schuelerTab;
    private JPanel elternteilEinsTab;
    private JButton btnSpeichern;
    private JButton btnAbbrechen;
    private JPanel elernteilZweiTab;
    private AngehoerigerPanel elternteilZweiPanel;
    private JPanel rechnungsempfaengerTab;
    private AngehoerigerPanel rechnungsempfaengerPanel;
    private JPanel btnPanel;

    private ActionListener closeListener;

    private final SchuelerModel schuelerModel;


    public SchuelerErfassenTabbedPane(SvmContext svmContext) {
        $$$setupUI$$$();
        btnSpeichern.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onSpeichern();
            }
        });
        btnAbbrechen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onAbbrechen();
            }
        });
        schuelerPanel.addCompletedListener(new CompletedListener() {
            @Override
            public void completed(boolean completed) {
                onSchuelerPanelCompleted(completed);
            }
        });
        schuelerModel = svmContext.getModelFactory().createSchuelerModel();
        schuelerPanel.setModel(schuelerModel);
        onSchuelerPanelCompleted(false);
    }

    public void addCloseListener(ActionListener actionListener) {
        closeListener = actionListener;
    }

    private void onSchuelerPanelCompleted(boolean completed) {
        System.out.println("SchuelerErfassenPanel SchuelerPanel completed=" + completed);
        btnSpeichern.setEnabled(completed);
    }

    private void onAbbrechen() {
        System.out.println("SchuelerErfassenPanel Abbrechen gedrückt");
        closeListener.actionPerformed(new ActionEvent(btnAbbrechen, ActionEvent.ACTION_PERFORMED, "Close nach Abbrechen"));
        // todo Dialog, ob wirklich abgebrochen werden soll
    }

    private void onSpeichern() {
        System.out.println("SchuelerErfassenPanel Speichern gedrückt");
        schuelerModel.save();
        // todo Dialog "erfolgreich gespeichert"
        closeListener.actionPerformed(new ActionEvent(btnSpeichern, ActionEvent.ACTION_PERFORMED, "Close nach Speichern"));
    }

    private void createUIComponents() {
        elternteilEinsPanel = new AngehoerigerPanel();
        elternteilZweiPanel = new AngehoerigerPanel();
        rechnungsempfaengerPanel = new AngehoerigerPanel();
    }

    private boolean isSelected(ItemEvent e) {
        return e.getStateChange() == ItemEvent.SELECTED;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        schuelerErfassenTabbedPane = new JTabbedPane();
        panel.add(schuelerErfassenTabbedPane, BorderLayout.CENTER);
        schuelerTab = new JPanel();
        schuelerTab.setLayout(new BorderLayout(0, 0));
        schuelerErfassenTabbedPane.addTab("Schüler", schuelerTab);
        schuelerPanel = new SchuelerPanel();
        schuelerTab.add(schuelerPanel.$$$getRootComponent$$$(), BorderLayout.CENTER);
        elternteilEinsTab = new JPanel();
        elternteilEinsTab.setLayout(new BorderLayout(0, 0));
        schuelerErfassenTabbedPane.addTab("Vater", elternteilEinsTab);
        elternteilEinsTab.add(elternteilEinsPanel.$$$getRootComponent$$$(), BorderLayout.CENTER);
        elernteilZweiTab = new JPanel();
        elernteilZweiTab.setLayout(new BorderLayout(0, 0));
        schuelerErfassenTabbedPane.addTab("Mutter", elernteilZweiTab);
        elernteilZweiTab.add(elternteilZweiPanel.$$$getRootComponent$$$(), BorderLayout.CENTER);
        rechnungsempfaengerTab = new JPanel();
        rechnungsempfaengerTab.setLayout(new BorderLayout(0, 0));
        schuelerErfassenTabbedPane.addTab("Rechnungsempfänger", rechnungsempfaengerTab);
        rechnungsempfaengerTab.add(rechnungsempfaengerPanel.$$$getRootComponent$$$(), BorderLayout.CENTER);
        btnPanel = new JPanel();
        btnPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(btnPanel, BorderLayout.SOUTH);
        btnSpeichern = new JButton();
        btnSpeichern.setText("Speichern");
        btnSpeichern.setMnemonic('S');
        btnSpeichern.setDisplayedMnemonicIndex(0);
        btnPanel.add(btnSpeichern);
        btnAbbrechen = new JButton();
        btnAbbrechen.setText("Abbrechen");
        btnAbbrechen.setMnemonic('A');
        btnAbbrechen.setDisplayedMnemonicIndex(0);
        btnPanel.add(btnAbbrechen);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
