package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.commands.AdresseInsertCommand;
import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.domain.Person;
import ch.metzenthin.svm.model.entities.Adresse;
import ch.metzenthin.svm.model.entities.Angehoeriger;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 * @author hans
 */
public class SchuelerErfassenPanel {
    private JPanel panel;
    private SchuelerPanel schuelerPanel;
    private ElternteilEinsPanel elternteilEinsPanel;
    private ElternteilZweiPanel elternteilZweiPanel;
    private DrittempfaengerPanel drittempfaengerPanel;
    private JPanel btnPanel;
    private JButton btnSpeichern;
    private JButton btnAbbrechen;
    private SvmContext svmContext;

    public SchuelerErfassenPanel(SvmContext svmContext) {
        this.svmContext = svmContext;
        $$$setupUI$$$();
        btnSpeichern.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onSpeichern();
            }
        });
        btnAbbrechen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onAbbrechen();
            }
        });
    }

    private void onAbbrechen() {
        System.out.println("Abbrechen gedrückt");
    }

    private void onSpeichern() {
        System.out.println("Speichern gedrückt");

        Person person = new Person() {
            String nachname;
            String vorname;
            String strasse;
            String plz;
            String ort;
            @Override
            public String getNachname() {
                return nachname;
            }

            @Override
            public String getVorname() {
                return vorname;
            }

            @Override
            public void setNachname(String text) {
                nachname = text;
            }

            @Override
            public void setVorname(String text) {
                vorname = text;
            }

            @Override
            public String getStrasse() {
                return strasse;
            }

            @Override
            public String getPlz() {
                return plz;
            }

            @Override
            public String getOrt() {
                return ort;
            }

            @Override
            public void setStrasse(String text) {
                strasse = text;
            }

            @Override
            public void setPlz(String text) {
                plz = text;
            }

            @Override
            public void setOrt(String text) {
                ort = text;
            }
        };
        Angehoeriger angehoeriger = new Angehoeriger();
        schuelerPanel.fillAngehoeriger(angehoeriger);
        Adresse adresse = new Adresse();
        schuelerPanel.fillAdresse(adresse);
        AdresseInsertCommand adresseInsertCommand = new AdresseInsertCommand(adresse);
        svmContext.getCommandInvoker().executeCommand(adresseInsertCommand);

    }

    private void createUIComponents() {
        elternteilEinsPanel = new ElternteilEinsPanel();
        elternteilEinsPanel.addRechnungsempfaengerAdresseItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                onElternteilEinsRechnungsempfaenger(e);
            }
        });
        elternteilZweiPanel = new ElternteilZweiPanel();
        elternteilZweiPanel.addRechnungsempfaengerAdresseItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                onElternteilZweiRechnungsempfaenger(e);
            }
        });
        drittempfaengerPanel = new DrittempfaengerPanel();
        drittempfaengerPanel.addRechnungsempfaengerAdresseItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                onDrittempfaengerRechnungsempfaenger(e);
            }
        });
    }

    private void onElternteilEinsRechnungsempfaenger(ItemEvent e) {
        System.out.println("Elternteil 1 Rechnungsempfänger. selected=" + isSelected(e));
    }

    private void onElternteilZweiRechnungsempfaenger(ItemEvent e) {
        System.out.println("Elternteil 2 Rechnungsempfänger. selected=" + isSelected(e));
    }

    private void onDrittempfaengerRechnungsempfaenger(ItemEvent e) {
        System.out.println("Drittempfänger Rechnungsempfänger. selected=" + isSelected(e));
    }

    private boolean isSelected(ItemEvent e) {
        return e.getStateChange() == ItemEvent.SELECTED;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel.add(panel1, BorderLayout.CENTER);
        schuelerPanel = new SchuelerPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        panel1.add(schuelerPanel.$$$getRootComponent$$$(), gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer2, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        panel1.add(elternteilEinsPanel.$$$getRootComponent$$$(), gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panel1.add(elternteilZweiPanel.$$$getRootComponent$$$(), gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        panel1.add(drittempfaengerPanel.$$$getRootComponent$$$(), gbc);
        btnPanel = new JPanel();
        btnPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(btnPanel, BorderLayout.SOUTH);
        btnSpeichern = new JButton();
        btnSpeichern.setText("Speichern");
        btnSpeichern.setMnemonic('S');
        btnSpeichern.setDisplayedMnemonicIndex(0);
        btnPanel.add(btnSpeichern);
        btnAbbrechen = new JButton();
        btnAbbrechen.setText("Abbrechen");
        btnAbbrechen.setMnemonic('A');
        btnAbbrechen.setDisplayedMnemonicIndex(0);
        btnPanel.add(btnAbbrechen);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
