package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.common.utils.Converter;
import ch.metzenthin.svm.dataTypes.Wochentag;
import ch.metzenthin.svm.domain.model.SchuelerSuchenModel;
import ch.metzenthin.svm.persistence.entities.Code;
import ch.metzenthin.svm.ui.control.SchuelerSuchenController;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author Martin Schraner
 */
public class SchuelerSuchenPanel {
    private SchuelerSuchenController schuelerSuchenController;
    private JPanel panel;
    private JPanel stammdatenPanel;
    private JPanel kursPanel;
    private JPanel codesPanel;
    private JPanel stichtagPanel;
    private JTextField txtNachname;
    private JTextField txtVorname;
    private JTextField txtStrasseHausnummer;
    private JTextField txtPlz;
    private JTextField txtOrt;
    private JTextField txtFestnetz;
    private JTextField txtNatel;
    private JTextField txtEmail;
    private JTextField txtGeburtsdatumSuchperiode;
    private JTextField txtLehrkraft;
    private JTextField txtVon;
    private JTextField txtBis;
    private JTextField txtStichtag;
    private JRadioButton radioBtnRolleAlle;
    private JRadioButton radioBtnAngemeldet;
    private JRadioButton radioBtnAbgemeldet;
    private JRadioButton radioBtnAnmeldestatusAlle;
    private JRadioButton radioBtnWeiblich;
    private JRadioButton radioBtnMaennlich;
    private JRadioButton radioBtnGeschlechtAlle;
    private JRadioButton radioBtnDispensiert;
    private JRadioButton radioBtnNichtDispensiert;
    private JRadioButton radioBtnDispensationAlle;
    private JRadioButton radioBtnSchueler;
    private JRadioButton radioBtnEltern;
    private JRadioButton radioBtnRechnungsempfaenger;
    private JComboBox<Wochentag> comboBoxWochentag;
    private JComboBox<Code> comboBoxCode;
    private JButton btnSuchen;
    private JButton btnAbbrechen;
    private JLabel errLblNachname;
    private JLabel errLblVorname;
    private JLabel errLblStrasseHausnummer;
    private JLabel errLblPlz;
    private JLabel errLblOrt;
    private JLabel errLblFestnetz;
    private JLabel errLblNatel;
    private JLabel errLblEmail;
    private JLabel errLblGeburtsdatumSuchperiode;
    private JLabel errLblLehrkraft;
    private JLabel errLblVon;
    private JLabel errLblBis;
    private JLabel errLblStichtag;
    private JPanel panelLeft;
    private JPanel panelRight;
    private JPanel statusDispensationGeschlechtPanel;
    private JPanel buttonPanel;
    private JPanel datenPanel;
    private JPanel titelPanel;
    private JPanel suchenPanel;
    private SchuelerSuchenModel schuelerSuchenModel;
    private ActionListener nextPanelListener;
    private SvmContext svmContext;

    public SchuelerSuchenPanel(SvmContext svmContext) {
        $$$setupUI$$$();
        schuelerSuchenModel = svmContext.getModelFactory().createSchuelerSuchenModel();
        initializeTxtFields();
        initializeRadioButtonGroups();
        initializeErrLbls();
        createSchuelerSuchenController(svmContext);
    }

    private void initializeTxtFields() {
        txtStichtag.setText(Converter.asString(schuelerSuchenModel.getStichtagInit()));
    }

    private void initializeRadioButtonGroups() {
        switch (schuelerSuchenModel.getRolleInit()) {
            case SCHUELER:
                radioBtnSchueler.setSelected(true);
                break;
            case ELTERN:
                radioBtnEltern.setSelected(true);
                break;
            case RECHNUNGSEMPFAENGER:
                radioBtnRechnungsempfaenger.setSelected(true);
                break;
            case ALLE:
                radioBtnRolleAlle.setSelected(true);
                break;
        }
        switch (schuelerSuchenModel.getAnmeldestatusInit()) {
            case ANGEMELDET:
                radioBtnAngemeldet.setSelected(true);
                break;
            case ABGEMELDET:
                radioBtnAbgemeldet.setSelected(true);
                break;
            case ALLE:
                radioBtnAnmeldestatusAlle.setSelected(true);
                break;
        }
        switch (schuelerSuchenModel.getDispensationInit()) {
            case DISPENSIERT:
                radioBtnDispensiert.setSelected(true);
                break;
            case NICHT_DISPENSIERT:
                radioBtnNichtDispensiert.setSelected(true);
                break;
            case ALLE:
                radioBtnDispensationAlle.setSelected(true);
                break;
        }
        switch (schuelerSuchenModel.getGeschlechtInit()) {
            case WEIBLICH:
                radioBtnWeiblich.setSelected(true);
                break;
            case MAENNLICH:
                radioBtnMaennlich.setSelected(true);
                break;
            case ALLE:
                radioBtnGeschlechtAlle.setSelected(true);
                break;
        }
    }

    private void initializeErrLbls() {
        errLblNachname.setVisible(false);
        errLblNachname.setForeground(Color.RED);
        errLblVorname.setVisible(false);
        errLblVorname.setForeground(Color.RED);
        errLblStrasseHausnummer.setVisible(false);
        errLblStrasseHausnummer.setForeground(Color.RED);
        errLblOrt.setVisible(false);
        errLblOrt.setForeground(Color.RED);
        errLblPlz.setVisible(false);
        errLblPlz.setForeground(Color.RED);
        errLblFestnetz.setVisible(false);
        errLblFestnetz.setForeground(Color.RED);
        errLblNatel.setVisible(false);
        errLblNatel.setForeground(Color.RED);
        errLblEmail.setVisible(false);
        errLblEmail.setForeground(Color.RED);
        errLblGeburtsdatumSuchperiode.setVisible(false);
        errLblGeburtsdatumSuchperiode.setForeground(Color.RED);
        errLblLehrkraft.setVisible(false);
        errLblLehrkraft.setForeground(Color.RED);
        errLblVon.setVisible(false);
        errLblVon.setForeground(Color.RED);
        errLblBis.setVisible(false);
        errLblBis.setForeground(Color.RED);
        errLblStichtag.setVisible(false);
        errLblStichtag.setForeground(Color.RED);
    }

    private void createSchuelerSuchenController(SvmContext svmContext) {
        this.svmContext = svmContext;
        schuelerSuchenController = new SchuelerSuchenController(svmContext, schuelerSuchenModel);
        schuelerSuchenController.setTxtNachname(txtNachname);
        schuelerSuchenController.setTxtVorname(txtVorname);
        schuelerSuchenController.setTxtStrasseHausnummer(txtStrasseHausnummer);
        schuelerSuchenController.setTxtPlz(txtPlz);
        schuelerSuchenController.setTxtOrt(txtOrt);
        schuelerSuchenController.setTxtFestnetz(txtFestnetz);
        schuelerSuchenController.setTxtNatel(txtNatel);
        schuelerSuchenController.setTxtEmail(txtEmail);
        schuelerSuchenController.setTxtGeburtsdatumSuchperiode(txtGeburtsdatumSuchperiode);
        schuelerSuchenController.setTxtLehrkraft(txtLehrkraft);
        schuelerSuchenController.setTxtVon(txtVon);
        schuelerSuchenController.setTxtBis(txtBis);
        schuelerSuchenController.setTxtStichtag(txtStichtag);
        schuelerSuchenController.setComboBoxWochentag(comboBoxWochentag);
        schuelerSuchenController.setComboBoxCode(comboBoxCode);
        schuelerSuchenController.setRadioBtnGroupRolle(radioBtnSchueler, radioBtnEltern, radioBtnRechnungsempfaenger, radioBtnRolleAlle);
        schuelerSuchenController.setRadioBtnGroupAnmeldestatus(radioBtnAngemeldet, radioBtnAbgemeldet, radioBtnAnmeldestatusAlle);
        schuelerSuchenController.setRadioBtnGroupDispensation(radioBtnDispensiert, radioBtnNichtDispensiert, radioBtnDispensationAlle);
        schuelerSuchenController.setRadioBtnGroupGeschlecht(radioBtnWeiblich, radioBtnMaennlich, radioBtnGeschlechtAlle);
        schuelerSuchenController.setErrLblNachname(errLblNachname);
        schuelerSuchenController.setErrLblVorname(errLblVorname);
        schuelerSuchenController.setErrLblStrasseHausnummer(errLblStrasseHausnummer);
        schuelerSuchenController.setErrLblPlz(errLblPlz);
        schuelerSuchenController.setErrLblOrt(errLblOrt);
        schuelerSuchenController.setErrLblFestnetz(errLblFestnetz);
        schuelerSuchenController.setErrLblNatel(errLblNatel);
        schuelerSuchenController.setErrLblEmail(errLblEmail);
        schuelerSuchenController.setErrLblGeburtsdatumSuchperiode(errLblGeburtsdatumSuchperiode);
        schuelerSuchenController.setErrLblStichtag(errLblStichtag);
        schuelerSuchenController.setBtnSuchen(btnSuchen);
        schuelerSuchenController.setBtnAbbrechen(btnAbbrechen);
        schuelerSuchenController.addZurueckListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onZurueck();
            }
        });
    }

    private void onZurueck() {
        svmContext.getCommandInvoker().clear();
        nextPanelListener.actionPerformed(new ActionEvent(new Object[]{$$$getRootComponent$$$(), "Schüler suchen"}, ActionEvent.ACTION_PERFORMED, "Zurück zu Schüler suchen"));
    }

    private void createUIComponents() {
        comboBoxWochentag = new JComboBox<>();
        comboBoxCode = new JComboBox<>();
    }

    public void addCloseListener(ActionListener actionListener) {
        schuelerSuchenController.addCloseListener(actionListener);
    }

    public void addNextPanelListener(ActionListener nextPanelListener) {
        this.nextPanelListener = nextPanelListener;
        schuelerSuchenController.addNextPanelListener(nextPanelListener);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridBagLayout());
        panel.add(buttonPanel, BorderLayout.SOUTH);
        btnSuchen = new JButton();
        btnSuchen.setMaximumSize(new Dimension(114, 29));
        btnSuchen.setMinimumSize(new Dimension(114, 29));
        btnSuchen.setPreferredSize(new Dimension(114, 29));
        btnSuchen.setSelected(true);
        btnSuchen.setText("Suchen");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 5);
        buttonPanel.add(btnSuchen, gbc);
        btnAbbrechen = new JButton();
        btnAbbrechen.setMaximumSize(new Dimension(114, 29));
        btnAbbrechen.setMinimumSize(new Dimension(114, 29));
        btnAbbrechen.setPreferredSize(new Dimension(114, 29));
        btnAbbrechen.setText("Abbrechen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 5);
        buttonPanel.add(btnAbbrechen, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttonPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttonPanel.add(spacer2, gbc);
        datenPanel = new JPanel();
        datenPanel.setLayout(new GridBagLayout());
        panel.add(datenPanel, BorderLayout.CENTER);
        titelPanel = new JPanel();
        titelPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 20, 10);
        datenPanel.add(titelPanel, gbc);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 36));
        label1.setText("Schüler suchen");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        titelPanel.add(label1, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        titelPanel.add(spacer3, gbc);
        suchenPanel = new JPanel();
        suchenPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        datenPanel.add(suchenPanel, gbc);
        panelLeft = new JPanel();
        panelLeft.setLayout(new GridBagLayout());
        suchenPanel.add(panelLeft, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        stammdatenPanel = new JPanel();
        stammdatenPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 10, 0);
        panelLeft.add(stammdatenPanel, gbc);
        stammdatenPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Stammdaten", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(stammdatenPanel.getFont().getName(), Font.BOLD, stammdatenPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label2 = new JLabel();
        label2.setText("Nachname");
        label2.setDisplayedMnemonic('N');
        label2.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label2, gbc);
        txtNachname = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 9;
        gbc.weightx = 0.3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtNachname, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Vorname");
        label3.setDisplayedMnemonic('V');
        label3.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label3, gbc);
        txtVorname = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtVorname, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("PLZ/Ort");
        label4.setDisplayedMnemonic('P');
        label4.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label4, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel1, gbc);
        txtPlz = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(txtPlz, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer4, gbc);
        txtOrt = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 0.8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(txtOrt, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Geburtsdatum");
        label5.setDisplayedMnemonic('G');
        label5.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 15;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label5, gbc);
        txtGeburtsdatumSuchperiode = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 15;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtGeburtsdatumSuchperiode, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 17;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel2, gbc);
        radioBtnSchueler = new JRadioButton();
        radioBtnSchueler.setText("Schüler");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel2.add(radioBtnSchueler, gbc);
        radioBtnEltern = new JRadioButton();
        radioBtnEltern.setText("Eltern");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel2.add(radioBtnEltern, gbc);
        radioBtnRechnungsempfaenger = new JRadioButton();
        radioBtnRechnungsempfaenger.setText("Rechnungsempfänger");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel2.add(radioBtnRechnungsempfaenger, gbc);
        radioBtnRolleAlle = new JRadioButton();
        radioBtnRolleAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(radioBtnRolleAlle, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Rolle");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 17;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Festnetz");
        label7.setDisplayedMnemonic('F');
        label7.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label7, gbc);
        txtFestnetz = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtFestnetz, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Natel");
        label8.setDisplayedMnemonic('A');
        label8.setDisplayedMnemonicIndex(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label8, gbc);
        txtNatel = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtNatel, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Email");
        label9.setDisplayedMnemonic('E');
        label9.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label9, gbc);
        txtEmail = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtEmail, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 11;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(spacer6, gbc);
        txtStrasseHausnummer = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(txtStrasseHausnummer, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Strasse/Nr.");
        label10.setDisplayedMnemonic('S');
        label10.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(label10, gbc);
        errLblVorname = new JLabel();
        errLblVorname.setText("errLblVorname");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 8;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblVorname, gbc);
        errLblStrasseHausnummer = new JLabel();
        errLblStrasseHausnummer.setText("errLblStrasseNummer");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.gridwidth = 10;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblStrasseHausnummer, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        stammdatenPanel.add(panel3, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer7, gbc);
        errLblOrt = new JLabel();
        errLblOrt.setText("errLblOrt");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(errLblOrt, gbc);
        errLblPlz = new JLabel();
        errLblPlz.setText("errLblPlz");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(errLblPlz, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer8, gbc);
        errLblFestnetz = new JLabel();
        errLblFestnetz.setText("errLblFestnetz");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblFestnetz, gbc);
        errLblNatel = new JLabel();
        errLblNatel.setText("errLblNatel");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblNatel, gbc);
        errLblEmail = new JLabel();
        errLblEmail.setText("errLblEmail");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblEmail, gbc);
        errLblGeburtsdatumSuchperiode = new JLabel();
        errLblGeburtsdatumSuchperiode.setText("errLblGeburtsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 14;
        gbc.gridwidth = 9;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblGeburtsdatumSuchperiode, gbc);
        errLblNachname = new JLabel();
        errLblNachname.setText("errrLblNachname");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        stammdatenPanel.add(errLblNachname, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        stammdatenPanel.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer11, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer12, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer13, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer14, gbc);
        final JPanel spacer15 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer15, gbc);
        final JPanel spacer16 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer16, gbc);
        final JPanel spacer17 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 16;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer17, gbc);
        final JPanel spacer18 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stammdatenPanel.add(spacer18, gbc);
        final JPanel spacer19 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer19, gbc);
        final JPanel spacer20 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 18;
        gbc.fill = GridBagConstraints.VERTICAL;
        stammdatenPanel.add(spacer20, gbc);
        statusDispensationGeschlechtPanel = new JPanel();
        statusDispensationGeschlechtPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        panelLeft.add(statusDispensationGeschlechtPanel, gbc);
        statusDispensationGeschlechtPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Status, Dispensation, Geschlecht", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(statusDispensationGeschlechtPanel.getFont().getName(), Font.BOLD, statusDispensationGeschlechtPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label11 = new JLabel();
        label11.setText("Status");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        statusDispensationGeschlechtPanel.add(label11, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        statusDispensationGeschlechtPanel.add(panel4, gbc);
        radioBtnAngemeldet = new JRadioButton();
        radioBtnAngemeldet.setText("angemeldet");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnAngemeldet, gbc);
        radioBtnAbgemeldet = new JRadioButton();
        radioBtnAbgemeldet.setText("abgemeldet");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnAbgemeldet, gbc);
        radioBtnAnmeldestatusAlle = new JRadioButton();
        radioBtnAnmeldestatusAlle.setSelected(false);
        radioBtnAnmeldestatusAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel4.add(radioBtnAnmeldestatusAlle, gbc);
        final JPanel spacer21 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(spacer21, gbc);
        final JPanel spacer22 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        statusDispensationGeschlechtPanel.add(spacer22, gbc);
        final JLabel label12 = new JLabel();
        label12.setText("Dispensation");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        statusDispensationGeschlechtPanel.add(label12, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        statusDispensationGeschlechtPanel.add(panel5, gbc);
        radioBtnDispensiert = new JRadioButton();
        radioBtnDispensiert.setSelected(false);
        radioBtnDispensiert.setText("dispensiert");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel5.add(radioBtnDispensiert, gbc);
        radioBtnNichtDispensiert = new JRadioButton();
        radioBtnNichtDispensiert.setText("nicht dispensiert");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel5.add(radioBtnNichtDispensiert, gbc);
        radioBtnDispensationAlle = new JRadioButton();
        radioBtnDispensationAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel5.add(radioBtnDispensationAlle, gbc);
        final JPanel spacer23 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel5.add(spacer23, gbc);
        final JLabel label13 = new JLabel();
        label13.setText("Geschlecht");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        statusDispensationGeschlechtPanel.add(label13, gbc);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.BOTH;
        statusDispensationGeschlechtPanel.add(panel6, gbc);
        radioBtnWeiblich = new JRadioButton();
        radioBtnWeiblich.setText("weiblich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel6.add(radioBtnWeiblich, gbc);
        radioBtnMaennlich = new JRadioButton();
        radioBtnMaennlich.setText("männlich");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel6.add(radioBtnMaennlich, gbc);
        radioBtnGeschlechtAlle = new JRadioButton();
        radioBtnGeschlechtAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel6.add(radioBtnGeschlechtAlle, gbc);
        final JPanel spacer24 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(spacer24, gbc);
        final JPanel spacer25 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        statusDispensationGeschlechtPanel.add(spacer25, gbc);
        final JPanel spacer26 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        statusDispensationGeschlechtPanel.add(spacer26, gbc);
        final JPanel spacer27 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer27, gbc);
        final JPanel spacer28 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer28, gbc);
        final JPanel spacer29 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer29, gbc);
        final JPanel spacer30 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        statusDispensationGeschlechtPanel.add(spacer30, gbc);
        panelRight = new JPanel();
        panelRight.setLayout(new GridBagLayout());
        suchenPanel.add(panelRight, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        kursPanel = new JPanel();
        kursPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 10);
        panelRight.add(kursPanel, gbc);
        kursPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Kurs", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(kursPanel.getFont().getName(), Font.BOLD, kursPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label14 = new JLabel();
        label14.setText("Lehrkraft");
        label14.setDisplayedMnemonic('L');
        label14.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label14, gbc);
        final JPanel spacer31 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer31, gbc);
        txtLehrkraft = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(txtLehrkraft, gbc);
        final JPanel spacer32 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(spacer32, gbc);
        final JPanel spacer33 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(spacer33, gbc);
        final JLabel label15 = new JLabel();
        label15.setText("Wochentag");
        label15.setDisplayedMnemonic('W');
        label15.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label15, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(comboBoxWochentag, gbc);
        final JPanel spacer34 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer34, gbc);
        final JLabel label16 = new JLabel();
        label16.setText("Zeit");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(label16, gbc);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        kursPanel.add(panel7, gbc);
        final JLabel label17 = new JLabel();
        label17.setText("bis");
        label17.setDisplayedMnemonic('I');
        label17.setDisplayedMnemonicIndex(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel7.add(label17, gbc);
        txtBis = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        panel7.add(txtBis, gbc);
        txtVon = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 5);
        panel7.add(txtVon, gbc);
        final JLabel label18 = new JLabel();
        label18.setText("von");
        label18.setDisplayedMnemonic('O');
        label18.setDisplayedMnemonicIndex(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel7.add(label18, gbc);
        final JPanel spacer35 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer35, gbc);
        errLblLehrkraft = new JLabel();
        errLblLehrkraft.setText("errLblLehrkraft");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(errLblLehrkraft, gbc);
        errLblVon = new JLabel();
        errLblVon.setText("errLblVon");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(errLblVon, gbc);
        errLblBis = new JLabel();
        errLblBis.setText("errLblBis");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        kursPanel.add(errLblBis, gbc);
        final JPanel spacer36 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kursPanel.add(spacer36, gbc);
        final JPanel spacer37 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        kursPanel.add(spacer37, gbc);
        final JPanel spacer38 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        kursPanel.add(spacer38, gbc);
        codesPanel = new JPanel();
        codesPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 10, 10);
        panelRight.add(codesPanel, gbc);
        codesPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Codes", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(codesPanel.getFont().getName(), Font.BOLD, codesPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label19 = new JLabel();
        label19.setText("Codes");
        label19.setDisplayedMnemonic('C');
        label19.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(label19, gbc);
        final JPanel spacer39 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(spacer39, gbc);
        final JPanel spacer40 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(spacer40, gbc);
        final JPanel spacer41 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        codesPanel.add(spacer41, gbc);
        final JPanel spacer42 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        codesPanel.add(spacer42, gbc);
        final JPanel spacer43 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        codesPanel.add(spacer43, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(comboBoxCode, gbc);
        final JPanel spacer44 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codesPanel.add(spacer44, gbc);
        stichtagPanel = new JPanel();
        stichtagPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 10, 10);
        panelRight.add(stichtagPanel, gbc);
        stichtagPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Stichtag für Suche", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(stichtagPanel.getFont().getName(), Font.BOLD, stichtagPanel.getFont().getSize()), new Color(-16777216)));
        final JLabel label20 = new JLabel();
        label20.setText("Stichtag");
        label20.setDisplayedMnemonic('T');
        label20.setDisplayedMnemonicIndex(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        stichtagPanel.add(label20, gbc);
        final JPanel spacer45 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        stichtagPanel.add(spacer45, gbc);
        txtStichtag = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stichtagPanel.add(txtStichtag, gbc);
        final JPanel spacer46 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stichtagPanel.add(spacer46, gbc);
        final JPanel spacer47 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stichtagPanel.add(spacer47, gbc);
        errLblStichtag = new JLabel();
        errLblStichtag.setText("errLblStichtag");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        stichtagPanel.add(errLblStichtag, gbc);
        final JPanel spacer48 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        stichtagPanel.add(spacer48, gbc);
        final JPanel spacer49 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        stichtagPanel.add(spacer49, gbc);
        final JPanel spacer50 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        datenPanel.add(spacer50, gbc);
        label2.setLabelFor(txtNachname);
        label3.setLabelFor(txtVorname);
        label4.setLabelFor(txtPlz);
        label5.setLabelFor(txtGeburtsdatumSuchperiode);
        label7.setLabelFor(txtFestnetz);
        label8.setLabelFor(txtNatel);
        label9.setLabelFor(txtEmail);
        label10.setLabelFor(txtStrasseHausnummer);
        label14.setLabelFor(txtLehrkraft);
        label15.setLabelFor(comboBoxWochentag);
        label17.setLabelFor(txtBis);
        label18.setLabelFor(txtVon);
        label20.setLabelFor(txtStichtag);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnSchueler);
        buttonGroup.add(radioBtnEltern);
        buttonGroup.add(radioBtnRechnungsempfaenger);
        buttonGroup.add(radioBtnRolleAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnAngemeldet);
        buttonGroup.add(radioBtnAbgemeldet);
        buttonGroup.add(radioBtnAnmeldestatusAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnDispensiert);
        buttonGroup.add(radioBtnNichtDispensiert);
        buttonGroup.add(radioBtnDispensationAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnWeiblich);
        buttonGroup.add(radioBtnMaennlich);
        buttonGroup.add(radioBtnGeschlechtAlle);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
