package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.common.dataTypes.Stipendium;
import ch.metzenthin.svm.domain.model.SemesterrechnungenSuchenModel;
import ch.metzenthin.svm.persistence.entities.SemesterrechnungCode;
import ch.metzenthin.svm.ui.control.SemesterrechnungenSuchenController;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author Martin Schraner
 */
public class SemesterrechnungenSuchenPanel {
    private JPanel panel1;
    private JPanel datenPanel;
    private JPanel titelPanel;
    private JPanel suchenPanel;
    private JPanel leftPanel;
    private JPanel rightPanel;
    private JPanel buttonPanel;
    private JPanel semesterPanel;
    private JPanel namePanel;
    private JPanel codePanel;
    private JPanel stipendiumGratiskindPanel;
    private JPanel rechnungPanel;
    private JSpinner spinnerSemester;
    private JTextField txtNachname;
    private JTextField txtVorname;
    private JTextField txtRechnungsdatum;
    private JTextField txtWochenbetrag;
    private JTextField txtSchulgeld;
    private JLabel errLblNachname;
    private JLabel errLblVorname;
    private JLabel errLblRechnungsdatum;
    private JLabel errLblWochenbetrag;
    private JLabel errLblSchulgeld;
    private JComboBox<SemesterrechnungCode> comboBoxSemesterrechnungCode;
    private JComboBox<Stipendium> comboBoxStipendium;
    private JCheckBox checkBoxGratiskinder;
    private JCheckBox checkBoxSechsJahresRabatt;
    private JRadioButton radioBtnRechnungsempfaenger;
    private JRadioButton radioBtnSchueler;
    private JRadioButton radioBtnEltern;
    private JRadioButton radioBtnRolleAlle;
    private JRadioButton radioBtnAm;
    private JRadioButton radioBtnVor;
    private JRadioButton radioBtnNach;
    private JRadioButton radioBtnOffen;
    private JRadioButton radioBtnBezahlt;
    private JRadioButton radioBtnRechnungsstatusAlle;
    private JButton btnSuchen;
    private JButton btnAbbrechen;
    private final SvmContext svmContext;
    private SemesterrechnungenSuchenController semesterrechnungenSuchenController;
    private SemesterrechnungenSuchenModel semesterrechnungenSuchenModel;
    private ActionListener nextPanelListener;

    public SemesterrechnungenSuchenPanel(SvmContext svmContext) {
        this.svmContext = svmContext;
        $$$setupUI$$$();
        semesterrechnungenSuchenModel = svmContext.getModelFactory().createSemesterrechnungenSuchenModel();
        initializeErrLbls();
        createSemesterrechnungenSuchenController();
    }

    private void initializeErrLbls() {
        errLblNachname.setVisible(false);
        errLblNachname.setForeground(Color.RED);
        errLblVorname.setVisible(false);
        errLblVorname.setForeground(Color.RED);
        errLblRechnungsdatum.setVisible(false);
        errLblRechnungsdatum.setForeground(Color.RED);
        errLblWochenbetrag.setVisible(false);
        errLblWochenbetrag.setForeground(Color.RED);
        errLblSchulgeld.setVisible(false);
        errLblSchulgeld.setForeground(Color.RED);
    }

    private void createSemesterrechnungenSuchenController() {
        semesterrechnungenSuchenController = new SemesterrechnungenSuchenController(svmContext, semesterrechnungenSuchenModel);
        semesterrechnungenSuchenController.setTxtNachname(txtNachname);
        semesterrechnungenSuchenController.setTxtVorname(txtVorname);
        semesterrechnungenSuchenController.setTxtRechnungsdatum(txtRechnungsdatum);
        semesterrechnungenSuchenController.setTxtWochenbetrag(txtWochenbetrag);
        semesterrechnungenSuchenController.setTxtSchulgeld(txtSchulgeld);
        semesterrechnungenSuchenController.setSpinnerSemester(spinnerSemester);
        semesterrechnungenSuchenController.setComboBoxSemesterrechnungCode(comboBoxSemesterrechnungCode);
        semesterrechnungenSuchenController.setComboBoxStipendium(comboBoxStipendium);
        semesterrechnungenSuchenController.setCheckBoxSechsJahresRabatt(checkBoxSechsJahresRabatt);
        semesterrechnungenSuchenController.setCheckBoxGratiskinder(checkBoxGratiskinder);
        semesterrechnungenSuchenController.setRadioBtnGroupRolle(radioBtnSchueler, radioBtnEltern, radioBtnRechnungsempfaenger, radioBtnRolleAlle);
        semesterrechnungenSuchenController.setRadioBtnGroupRechunungsdatum(radioBtnAm, radioBtnVor, radioBtnNach);
        semesterrechnungenSuchenController.setRadioBtnGroupRechnungsstatus(radioBtnOffen, radioBtnBezahlt, radioBtnRechnungsstatusAlle);
        semesterrechnungenSuchenController.setErrLblNachname(errLblNachname);
        semesterrechnungenSuchenController.setErrLblVorname(errLblVorname);
        semesterrechnungenSuchenController.setErrLblRechnungsdatum(errLblRechnungsdatum);
        semesterrechnungenSuchenController.setErrLblWochenbetrag(errLblWochenbetrag);
        semesterrechnungenSuchenController.setErrLblSchulgeld(errLblSchulgeld);
        semesterrechnungenSuchenController.setBtnSuchen(btnSuchen);
        semesterrechnungenSuchenController.setBtnAbbrechen(btnAbbrechen);
        semesterrechnungenSuchenController.addZurueckListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onZurueck();
            }
        });
    }

    private void createUIComponents() {
        spinnerSemester = new JSpinner();
        comboBoxSemesterrechnungCode = new JComboBox<>();
        comboBoxStipendium = new JComboBox<>();
    }

    private void onZurueck() {
        nextPanelListener.actionPerformed(new ActionEvent(new Object[]{$$$getRootComponent$$$(), "Semesterrechnungen suchen", Boolean.TRUE}, ActionEvent.ACTION_PERFORMED, "Zurück zu Schüler suchen"));
    }

    public void addCloseListener(ActionListener actionListener) {
        semesterrechnungenSuchenController.addCloseListener(actionListener);
    }

    public void addNextPanelListener(ActionListener nextPanelListener) {
        this.nextPanelListener = nextPanelListener;
        semesterrechnungenSuchenController.addNextPanelListener(nextPanelListener);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        datenPanel = new JPanel();
        datenPanel.setLayout(new GridBagLayout());
        panel1.add(datenPanel, BorderLayout.CENTER);
        titelPanel = new JPanel();
        titelPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 20, 10);
        datenPanel.add(titelPanel, gbc);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 36));
        label1.setText("Semesterrechnungen suchen");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        titelPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        titelPanel.add(spacer1, gbc);
        suchenPanel = new JPanel();
        suchenPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        datenPanel.add(suchenPanel, gbc);
        leftPanel = new JPanel();
        leftPanel.setLayout(new GridBagLayout());
        suchenPanel.add(leftPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        semesterPanel = new JPanel();
        semesterPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 10, 0);
        leftPanel.add(semesterPanel, gbc);
        semesterPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Schuljahr / Semester", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(semesterPanel.getFont().getName(), Font.BOLD, semesterPanel.getFont().getSize())));
        final JLabel label2 = new JLabel();
        label2.setText("Schuljahr, Semester");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        semesterPanel.add(label2, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        semesterPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        semesterPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        semesterPanel.add(spacer4, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        semesterPanel.add(spinnerSemester, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        semesterPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        semesterPanel.add(spacer6, gbc);
        namePanel = new JPanel();
        namePanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        leftPanel.add(namePanel, gbc);
        namePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Name", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(namePanel.getFont().getName(), Font.BOLD, namePanel.getFont().getSize())));
        final JLabel label3 = new JLabel();
        label3.setText("Nachname");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        namePanel.add(label3, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        namePanel.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        namePanel.add(spacer8, gbc);
        txtNachname = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        namePanel.add(txtNachname, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        namePanel.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        namePanel.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        namePanel.add(spacer11, gbc);
        errLblNachname = new JLabel();
        errLblNachname.setText("errLblNachname");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        namePanel.add(errLblNachname, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Vorname");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        namePanel.add(label4, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        namePanel.add(spacer12, gbc);
        txtVorname = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        namePanel.add(txtVorname, gbc);
        errLblVorname = new JLabel();
        errLblVorname.setText("errLblVorname");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        namePanel.add(errLblVorname, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Rolle");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        namePanel.add(label5, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        namePanel.add(spacer13, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.BOTH;
        namePanel.add(panel2, gbc);
        radioBtnRechnungsempfaenger = new JRadioButton();
        radioBtnRechnungsempfaenger.setText("Rechnungsempfänger");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel2.add(radioBtnRechnungsempfaenger, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer14, gbc);
        radioBtnSchueler = new JRadioButton();
        radioBtnSchueler.setText("Schüler");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel2.add(radioBtnSchueler, gbc);
        radioBtnEltern = new JRadioButton();
        radioBtnEltern.setText("Eltern");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel2.add(radioBtnEltern, gbc);
        radioBtnRolleAlle = new JRadioButton();
        radioBtnRolleAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(radioBtnRolleAlle, gbc);
        codePanel = new JPanel();
        codePanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        leftPanel.add(codePanel, gbc);
        codePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Semesterrechnung-Code", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(codePanel.getFont().getName(), Font.BOLD, codePanel.getFont().getSize())));
        final JLabel label6 = new JLabel();
        label6.setText("Code");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        codePanel.add(label6, gbc);
        final JPanel spacer15 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codePanel.add(spacer15, gbc);
        final JPanel spacer16 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        codePanel.add(spacer16, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codePanel.add(comboBoxSemesterrechnungCode, gbc);
        final JPanel spacer17 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codePanel.add(spacer17, gbc);
        final JPanel spacer18 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        codePanel.add(spacer18, gbc);
        final JPanel spacer19 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        codePanel.add(spacer19, gbc);
        rightPanel = new JPanel();
        rightPanel.setLayout(new GridBagLayout());
        suchenPanel.add(rightPanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        stipendiumGratiskindPanel = new JPanel();
        stipendiumGratiskindPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 10);
        rightPanel.add(stipendiumGratiskindPanel, gbc);
        stipendiumGratiskindPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Stipendium / Rabatte", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(stipendiumGratiskindPanel.getFont().getName(), Font.BOLD, stipendiumGratiskindPanel.getFont().getSize())));
        final JLabel label7 = new JLabel();
        label7.setText("Stipendium");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        stipendiumGratiskindPanel.add(label7, gbc);
        final JPanel spacer20 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stipendiumGratiskindPanel.add(spacer20, gbc);
        final JPanel spacer21 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        stipendiumGratiskindPanel.add(spacer21, gbc);
        final JPanel spacer22 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stipendiumGratiskindPanel.add(spacer22, gbc);
        final JPanel spacer23 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        stipendiumGratiskindPanel.add(spacer23, gbc);
        final JPanel spacer24 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        stipendiumGratiskindPanel.add(spacer24, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stipendiumGratiskindPanel.add(comboBoxStipendium, gbc);
        final JPanel spacer25 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        stipendiumGratiskindPanel.add(spacer25, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Rabatte");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        stipendiumGratiskindPanel.add(label8, gbc);
        checkBoxSechsJahresRabatt = new JCheckBox();
        checkBoxSechsJahresRabatt.setText("6-Jahres-Rabatt");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 10);
        stipendiumGratiskindPanel.add(checkBoxSechsJahresRabatt, gbc);
        checkBoxGratiskinder = new JCheckBox();
        checkBoxGratiskinder.setText("Gratiskind");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        stipendiumGratiskindPanel.add(checkBoxGratiskinder, gbc);
        rechnungPanel = new JPanel();
        rechnungPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 10, 10);
        rightPanel.add(rechnungPanel, gbc);
        rechnungPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Rechnung", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(rechnungPanel.getFont().getName(), Font.BOLD, rechnungPanel.getFont().getSize())));
        final JLabel label9 = new JLabel();
        label9.setText("Status");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        rechnungPanel.add(label9, gbc);
        final JPanel spacer26 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rechnungPanel.add(spacer26, gbc);
        final JPanel spacer27 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        rechnungPanel.add(spacer27, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        rechnungPanel.add(panel3, gbc);
        radioBtnOffen = new JRadioButton();
        radioBtnOffen.setText("offen");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel3.add(radioBtnOffen, gbc);
        radioBtnBezahlt = new JRadioButton();
        radioBtnBezahlt.setText("bezahlt");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel3.add(radioBtnBezahlt, gbc);
        radioBtnRechnungsstatusAlle = new JRadioButton();
        radioBtnRechnungsstatusAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(radioBtnRechnungsstatusAlle, gbc);
        final JPanel spacer28 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer28, gbc);
        final JPanel spacer29 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rechnungPanel.add(spacer29, gbc);
        final JPanel spacer30 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        rechnungPanel.add(spacer30, gbc);
        final JPanel spacer31 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        rechnungPanel.add(spacer31, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Wochenbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        rechnungPanel.add(label10, gbc);
        txtWochenbetrag = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rechnungPanel.add(txtWochenbetrag, gbc);
        errLblWochenbetrag = new JLabel();
        errLblWochenbetrag.setText("errLblWochenbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        rechnungPanel.add(errLblWochenbetrag, gbc);
        final JPanel spacer32 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        rechnungPanel.add(spacer32, gbc);
        final JLabel label11 = new JLabel();
        label11.setText("Schulgeld");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        rechnungPanel.add(label11, gbc);
        final JPanel spacer33 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        rechnungPanel.add(spacer33, gbc);
        txtSchulgeld = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rechnungPanel.add(txtSchulgeld, gbc);
        errLblSchulgeld = new JLabel();
        errLblSchulgeld.setText("errLblSchulgeld");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        rechnungPanel.add(errLblSchulgeld, gbc);
        txtRechnungsdatum = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rechnungPanel.add(txtRechnungsdatum, gbc);
        errLblRechnungsdatum = new JLabel();
        errLblRechnungsdatum.setText("errLblRechnungsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        rechnungPanel.add(errLblRechnungsdatum, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        rechnungPanel.add(panel4, gbc);
        radioBtnAm = new JRadioButton();
        radioBtnAm.setText("am");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnAm, gbc);
        radioBtnVor = new JRadioButton();
        radioBtnVor.setText("vor");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnVor, gbc);
        radioBtnNach = new JRadioButton();
        radioBtnNach.setText("nach");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel4.add(radioBtnNach, gbc);
        final JPanel spacer34 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(spacer34, gbc);
        final JPanel spacer35 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        rechnungPanel.add(spacer35, gbc);
        final JLabel label12 = new JLabel();
        label12.setText("Rechnungsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        rechnungPanel.add(label12, gbc);
        final JPanel spacer36 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        datenPanel.add(spacer36, gbc);
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridBagLayout());
        panel1.add(buttonPanel, BorderLayout.SOUTH);
        btnSuchen = new JButton();
        btnSuchen.setMaximumSize(new Dimension(114, 29));
        btnSuchen.setMinimumSize(new Dimension(114, 29));
        btnSuchen.setPreferredSize(new Dimension(114, 29));
        btnSuchen.setText("Suchen");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(btnSuchen, gbc);
        final JPanel spacer37 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(spacer37, gbc);
        final JPanel spacer38 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttonPanel.add(spacer38, gbc);
        final JPanel spacer39 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttonPanel.add(spacer39, gbc);
        btnAbbrechen = new JButton();
        btnAbbrechen.setMaximumSize(new Dimension(114, 29));
        btnAbbrechen.setMinimumSize(new Dimension(114, 29));
        btnAbbrechen.setPreferredSize(new Dimension(114, 29));
        btnAbbrechen.setText("Abbrechen");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(btnAbbrechen, gbc);
        label2.setLabelFor(spinnerSemester);
        label3.setLabelFor(txtNachname);
        label4.setLabelFor(txtVorname);
        label6.setLabelFor(comboBoxSemesterrechnungCode);
        label7.setLabelFor(comboBoxStipendium);
        label10.setLabelFor(txtWochenbetrag);
        label11.setLabelFor(txtSchulgeld);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnRechnungsempfaenger);
        buttonGroup.add(radioBtnSchueler);
        buttonGroup.add(radioBtnEltern);
        buttonGroup.add(radioBtnRolleAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnOffen);
        buttonGroup.add(radioBtnBezahlt);
        buttonGroup.add(radioBtnRechnungsstatusAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnAm);
        buttonGroup.add(radioBtnVor);
        buttonGroup.add(radioBtnNach);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
