package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.common.dataTypes.Stipendium;
import ch.metzenthin.svm.domain.model.SemesterrechnungenSuchenModel;
import ch.metzenthin.svm.persistence.entities.SemesterrechnungCode;
import ch.metzenthin.svm.ui.control.SemesterrechnungenSuchenController;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author Martin Schraner
 */
public class SemesterrechnungenSuchenPanel {
    private JPanel panel1;
    private JPanel titelPanel;
    private JPanel suchenPanel;
    private JPanel leftPanel;
    private JPanel rightPanel;
    private JPanel buttonPanel;
    private JPanel semesterPanel;
    private JPanel namePanel;
    private JPanel codePanel;
    private JPanel stipendiumGratiskindPanel;
    private JPanel vorrechnungPanel;
    private JPanel nachrechnungPanel;
    private JPanel differenzPanel;
    private JSpinner spinnerSemester;
    private JTextField txtNachname;
    private JTextField txtVorname;
    private JTextField txtRechnungsdatumVorrechnung;
    private JTextField txtErmaessigungVorrechnung;
    private JTextField txtZuschlagVorrechnung;
    private JTextField txtWochenbetragVorrechnung;
    private JTextField txtRechnungsbetragVorrechnung;
    private JTextField txtRestbetragVorrechnung;
    private JTextField txtRechnungsdatumNachrechnung;
    private JTextField txtErmaessigungNachrechnung;
    private JTextField txtZuschlagNachrechnung;
    private JTextField txtAnzahlWochenNachrechnung;
    private JTextField txtWochenbetragNachrechnung;
    private JTextField txtRechnungsbetragNachrechnung;
    private JTextField txtRestbetragNachrechnung;
    private JTextField txtDifferenzRechnungsbetrag;
    private JLabel errLblNachname;
    private JLabel errLblVorname;
    private JLabel errLblRechnungsdatumVorrechnung;
    private JLabel errLblErmaessigungVorrechnung;
    private JLabel errLblZuschlagVorrechnung;
    private JLabel errLblWochenbetragVorrechnung;
    private JLabel errLblRechnungsbetragVorrechnung;
    private JLabel errLblRestbetragVorrechnung;
    private JLabel errLblRechnungsdatumNachrechnung;
    private JLabel errLblErmaessigungNachrechnung;
    private JLabel errLblZuschlagNachrechnung;
    private JLabel errLblAnzahlWochenNachrechnung;
    private JLabel errLblWochenbetragNachrechnung;
    private JLabel errLblRechnungsbetragNachrechnung;
    private JLabel errLblRestbetragNachrechnung;
    private JLabel errLblDifferenzRechnungsbetrag;
    private JComboBox<SemesterrechnungCode> comboBoxSemesterrechnungCode;
    private JComboBox<Stipendium> comboBoxStipendium;
    private JCheckBox checkBoxGratiskinder;
    private JRadioButton radioBtnRechnungsempfaenger;
    private JRadioButton radioBtnSchueler;
    private JRadioButton radioBtnEltern;
    private JRadioButton radioBtnRolleAlle;
    private JRadioButton radioBtnSemesterrechnungCodeJa;
    private JRadioButton radioBtnSemesterrechnungCodeNein;
    private JRadioButton radioBtnSemesterrechnungCodeAlle;
    private JRadioButton radioBtnStipendiumJa;
    private JRadioButton radioBtnStipendiumNein;
    private JRadioButton radioBtnStipendiumAlle;
    private JRadioButton radioBtnRechnungsdatumGesetztVorrechnung;
    private JRadioButton radioBtnRechnungsdatumNichtGesetztVorrechnung;
    private JRadioButton radioBtnRechnungsdatumGesetztAlleVorrechnung;
    private JRadioButton radioBtnAmVorrechnung;
    private JRadioButton radioBtnVorVorrechnung;
    private JRadioButton radioBtnNachVorrechnung;
    private JRadioButton radioBtnGleichErmaessigungVorrechnung;
    private JRadioButton radioBtnKleinerErmaessigungVorrechnung;
    private JRadioButton radioBtnGroesserErmaessigungVorrechnung;
    private JRadioButton radioBtnGleichZuschlagVorrechnung;
    private JRadioButton radioBtnKleinerZuschlagVorrechnung;
    private JRadioButton radioBtnGroesserZuschlagVorrechnung;
    private JRadioButton radioBtnGleichWochenbetragVorrechnung;
    private JRadioButton radioBtnKleinerWochenbetragVorrechnung;
    private JRadioButton radioBtnGroesserWochenbetragVorrechnung;
    private JRadioButton radioBtnGleichRechnungsbetragVorrechnung;
    private JRadioButton radioBtnKleinerRechnungsbetragVorrechnung;
    private JRadioButton radioBtnGroesserRechnungsbetragVorrechnung;
    private JRadioButton radioBtnGleichRestbetragVorrechnung;
    private JRadioButton radioBtnKleinerRestbetragVorrechnung;
    private JRadioButton radioBtnGroesserRestbetragVorrechnung;
    private JRadioButton radioBtnSechsJahresRabattJaVorrechnung;
    private JRadioButton radioBtnSechsJahresRabattNeinVorrechnung;
    private JRadioButton radioBtnSechsJahresRabattAlleVorrechnung;
    private JRadioButton radioBtnRechnungsdatumGesetztNachrechnung;
    private JRadioButton radioBtnRechnungsdatumNichtGesetztNachrechnung;
    private JRadioButton radioBtnRechnungsdatumGesetztAlleNachrechnung;
    private JRadioButton radioBtnAmNachrechnung;
    private JRadioButton radioBtnVorNachrechnung;
    private JRadioButton radioBtnNachNachrechnung;
    private JRadioButton radioBtnGleichErmaessigungNachrechnung;
    private JRadioButton radioBtnKleinerErmaessigungNachrechnung;
    private JRadioButton radioBtnGroesserErmaessigungNachrechnung;
    private JRadioButton radioBtnGleichZuschlagNachrechnung;
    private JRadioButton radioBtnKleinerZuschlagNachrechnung;
    private JRadioButton radioBtnGroesserZuschlagNachrechnung;
    private JRadioButton radioBtnGleichAnzahlWochenNachrechnung;
    private JRadioButton radioBtnKleinerAnzahlWochenNachrechnung;
    private JRadioButton radioBtnGroesserAnzahlWochenNachrechnung;
    private JRadioButton radioBtnGleichWochenbetragNachrechnung;
    private JRadioButton radioBtnKleinerWochenbetragNachrechnung;
    private JRadioButton radioBtnGroesserWochenbetragNachrechnung;
    private JRadioButton radioBtnGleichRechnungsbetragNachrechnung;
    private JRadioButton radioBtnKleinerRechnungsbetragNachrechnung;
    private JRadioButton radioBtnGroesserRechnungsbetragNachrechnung;
    private JRadioButton radioBtnGleichRestbetragNachrechnung;
    private JRadioButton radioBtnKleinerRestbetragNachrechnung;
    private JRadioButton radioBtnGroesserRestbetragNachrechnung;
    private JRadioButton radioBtnSechsJahresRabattJaNachrechnung;
    private JRadioButton radioBtnSechsJahresRabattNeinNachrechnung;
    private JRadioButton radioBtnSechsJahresRabattAlleNachrechnung;
    private JRadioButton radioBtnDifferenzRechnungsbetragGleich;
    private JRadioButton radioBtnDifferenzRechnungsbetragKleiner;
    private JRadioButton radioBtnDifferenzRechnungsbetragGroesser;
    private JButton btnSuchen;
    private JButton btnAbbrechen;
    private JPanel datenPanel;
    private final SvmContext svmContext;
    private SemesterrechnungenSuchenController semesterrechnungenSuchenController;
    private SemesterrechnungenSuchenModel semesterrechnungenSuchenModel;
    private ActionListener nextPanelListener;

    public SemesterrechnungenSuchenPanel(SvmContext svmContext) {
        this.svmContext = svmContext;
        $$$setupUI$$$();
        semesterrechnungenSuchenModel = svmContext.getModelFactory().createSemesterrechnungenSuchenModel();
        initializeErrLbls();
        createSemesterrechnungenSuchenController();
    }

    private void initializeErrLbls() {
        errLblNachname.setVisible(false);
        errLblNachname.setForeground(Color.RED);
        errLblVorname.setVisible(false);
        errLblVorname.setForeground(Color.RED);
        errLblRechnungsdatumVorrechnung.setVisible(false);
        errLblRechnungsdatumVorrechnung.setForeground(Color.RED);
        errLblErmaessigungVorrechnung.setVisible(false);
        errLblErmaessigungVorrechnung.setForeground(Color.RED);
        errLblZuschlagVorrechnung.setVisible(false);
        errLblZuschlagVorrechnung.setForeground(Color.RED);
        errLblWochenbetragVorrechnung.setVisible(false);
        errLblWochenbetragVorrechnung.setForeground(Color.RED);
        errLblRechnungsbetragVorrechnung.setVisible(false);
        errLblRechnungsbetragVorrechnung.setForeground(Color.RED);
        errLblRestbetragVorrechnung.setVisible(false);
        errLblRestbetragVorrechnung.setForeground(Color.RED);
        errLblRechnungsdatumNachrechnung.setVisible(false);
        errLblRechnungsdatumNachrechnung.setForeground(Color.RED);
        errLblErmaessigungNachrechnung.setVisible(false);
        errLblErmaessigungNachrechnung.setForeground(Color.RED);
        errLblZuschlagNachrechnung.setVisible(false);
        errLblZuschlagNachrechnung.setForeground(Color.RED);
        errLblAnzahlWochenNachrechnung.setVisible(false);
        errLblAnzahlWochenNachrechnung.setForeground(Color.RED);
        errLblWochenbetragNachrechnung.setVisible(false);
        errLblWochenbetragNachrechnung.setForeground(Color.RED);
        errLblRechnungsbetragNachrechnung.setVisible(false);
        errLblRechnungsbetragNachrechnung.setForeground(Color.RED);
        errLblRestbetragNachrechnung.setVisible(false);
        errLblRestbetragNachrechnung.setForeground(Color.RED);
        errLblDifferenzRechnungsbetrag.setVisible(false);
        errLblDifferenzRechnungsbetrag.setForeground(Color.RED);
    }

    private void createSemesterrechnungenSuchenController() {
        semesterrechnungenSuchenController = new SemesterrechnungenSuchenController(svmContext, semesterrechnungenSuchenModel);
        semesterrechnungenSuchenController.setTxtNachname(txtNachname);
        semesterrechnungenSuchenController.setTxtVorname(txtVorname);
        semesterrechnungenSuchenController.setTxtRechnungsdatumVorrechnung(txtRechnungsdatumVorrechnung);
        semesterrechnungenSuchenController.setTxtErmaessigungVorrechnung(txtErmaessigungVorrechnung);
        semesterrechnungenSuchenController.setTxtZuschlagVorrechnung(txtZuschlagVorrechnung);
        semesterrechnungenSuchenController.setTxtWochenbetragVorrechnung(txtWochenbetragVorrechnung);
        semesterrechnungenSuchenController.setTxtRechnungsbetragVorrechnung(txtRechnungsbetragVorrechnung);
        semesterrechnungenSuchenController.setTxtRestbetragVorrechnung(txtRestbetragVorrechnung);
        semesterrechnungenSuchenController.setTxtRechnungsdatumNachrechnung(txtRechnungsdatumNachrechnung);
        semesterrechnungenSuchenController.setTxtErmaessigungNachrechnung(txtErmaessigungNachrechnung);
        semesterrechnungenSuchenController.setTxtZuschlagNachrechnung(txtZuschlagNachrechnung);
        semesterrechnungenSuchenController.setTxtAnzahlWochenNachrechnung(txtAnzahlWochenNachrechnung);
        semesterrechnungenSuchenController.setTxtWochenbetragNachrechnung(txtWochenbetragNachrechnung);
        semesterrechnungenSuchenController.setTxtRechnungsbetragNachrechnung(txtRechnungsbetragNachrechnung);
        semesterrechnungenSuchenController.setTxtRestbetragNachrechnung(txtRestbetragNachrechnung);
        semesterrechnungenSuchenController.setTxtDifferenzRechnungsbetrag(txtDifferenzRechnungsbetrag);
        semesterrechnungenSuchenController.setSpinnerSemester(spinnerSemester);
        semesterrechnungenSuchenController.setComboBoxSemesterrechnungCode(comboBoxSemesterrechnungCode);
        semesterrechnungenSuchenController.setComboBoxStipendium(comboBoxStipendium);
        semesterrechnungenSuchenController.setCheckBoxGratiskinder(checkBoxGratiskinder);
        semesterrechnungenSuchenController.setRadioBtnGroupRolle(radioBtnSchueler, radioBtnEltern, radioBtnRechnungsempfaenger, radioBtnRolleAlle);
        semesterrechnungenSuchenController.setRadioBtnGroupSemesterrechnungCodeJaNein(radioBtnSemesterrechnungCodeJa, radioBtnSemesterrechnungCodeNein, radioBtnSemesterrechnungCodeAlle);
        semesterrechnungenSuchenController.setRadioBtnGroupStipendiumJaNein(radioBtnStipendiumJa, radioBtnStipendiumNein, radioBtnStipendiumAlle);
        semesterrechnungenSuchenController.setRadioBtnGroupRechnungsdatumGesetztVorrechnung(radioBtnRechnungsdatumGesetztVorrechnung, radioBtnRechnungsdatumNichtGesetztVorrechnung, radioBtnRechnungsdatumGesetztAlleVorrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungRechnungsdatumVorrechnung(radioBtnAmVorrechnung, radioBtnVorVorrechnung, radioBtnNachVorrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungErmaessigungVorrechnung(radioBtnGleichErmaessigungVorrechnung, radioBtnKleinerErmaessigungVorrechnung, radioBtnGroesserErmaessigungVorrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungZuschlagVorrechnung(radioBtnGleichZuschlagVorrechnung, radioBtnKleinerZuschlagVorrechnung, radioBtnGroesserZuschlagVorrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungWochenbetragVorrechnung(radioBtnGleichWochenbetragVorrechnung, radioBtnKleinerWochenbetragVorrechnung, radioBtnGroesserWochenbetragVorrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungRechnungsbetragVorrechnung(radioBtnGleichRechnungsbetragVorrechnung, radioBtnKleinerRechnungsbetragVorrechnung, radioBtnGroesserRechnungsbetragVorrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungRestbetragVorrechnung(radioBtnGleichRestbetragVorrechnung, radioBtnKleinerRestbetragVorrechnung, radioBtnGroesserRestbetragVorrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupSechsJahresRabattJaNeinVorrechnung(radioBtnSechsJahresRabattJaVorrechnung, radioBtnSechsJahresRabattNeinVorrechnung, radioBtnSechsJahresRabattAlleVorrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupRechungsdatumGesetztNachrechnung(radioBtnRechnungsdatumGesetztNachrechnung, radioBtnRechnungsdatumNichtGesetztNachrechnung, radioBtnRechnungsdatumGesetztAlleNachrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungRechnungsdatumNachrechnung(radioBtnAmNachrechnung, radioBtnVorNachrechnung, radioBtnNachNachrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungErmaessigungNachrechnung(radioBtnGleichErmaessigungNachrechnung, radioBtnKleinerErmaessigungNachrechnung, radioBtnGroesserErmaessigungNachrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungZuschlagNachrechnung(radioBtnGleichZuschlagNachrechnung, radioBtnKleinerZuschlagNachrechnung, radioBtnGroesserZuschlagNachrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungAnzahlWochenNachrechnung(radioBtnGleichAnzahlWochenNachrechnung, radioBtnKleinerAnzahlWochenNachrechnung, radioBtnGroesserAnzahlWochenNachrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungWochenbetragNachrechnung(radioBtnGleichWochenbetragNachrechnung, radioBtnKleinerWochenbetragNachrechnung, radioBtnGroesserWochenbetragNachrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungRechnungsbetragNachrechnung(radioBtnGleichRechnungsbetragNachrechnung, radioBtnKleinerRechnungsbetragNachrechnung, radioBtnGroesserRechnungsbetragNachrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungRestbetragNachrechnung(radioBtnGleichRestbetragNachrechnung, radioBtnKleinerRestbetragNachrechnung, radioBtnGroesserRestbetragNachrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupSechsJahresRabattJaNeinNachrechnung(radioBtnSechsJahresRabattJaNachrechnung, radioBtnSechsJahresRabattNeinNachrechnung, radioBtnSechsJahresRabattAlleNachrechnung);
        semesterrechnungenSuchenController.setRadioBtnGroupPraezisierungDifferenzRechnungsbetrag(radioBtnDifferenzRechnungsbetragGleich, radioBtnDifferenzRechnungsbetragKleiner, radioBtnDifferenzRechnungsbetragGroesser);
        semesterrechnungenSuchenController.setErrLblNachname(errLblNachname);
        semesterrechnungenSuchenController.setErrLblVorname(errLblVorname);
        semesterrechnungenSuchenController.setErrLblRechnungsdatumVorrechnung(errLblRechnungsdatumVorrechnung);
        semesterrechnungenSuchenController.setErrLblErmaessigungVorrechnung(errLblErmaessigungVorrechnung);
        semesterrechnungenSuchenController.setErrLblZuschlagVorrechnung(errLblZuschlagVorrechnung);
        semesterrechnungenSuchenController.setErrLblWochenbetragVorrechnung(errLblWochenbetragVorrechnung);
        semesterrechnungenSuchenController.setErrLblRechnungsbetragVorrechnung(errLblRechnungsbetragVorrechnung);
        semesterrechnungenSuchenController.setErrLblRestbetragVorrechnung(errLblRestbetragVorrechnung);
        semesterrechnungenSuchenController.setErrLblRechnungsdatumNachrechnung(errLblRechnungsdatumNachrechnung);
        semesterrechnungenSuchenController.setErrLblErmaessigungNachrechnung(errLblErmaessigungNachrechnung);
        semesterrechnungenSuchenController.setErrLblZuschlagNachrechnung(errLblZuschlagNachrechnung);
        semesterrechnungenSuchenController.setErrLblAnzahlWochenNachrechnung(errLblAnzahlWochenNachrechnung);
        semesterrechnungenSuchenController.setErrLblWochenbetragNachrechnung(errLblWochenbetragNachrechnung);
        semesterrechnungenSuchenController.setErrLblRechnungsbetragNachrechnung(errLblRechnungsbetragNachrechnung);
        semesterrechnungenSuchenController.setErrLblRestbetragNachrechnung(errLblRestbetragNachrechnung);
        semesterrechnungenSuchenController.setErrLblDifferenzRechnungsbetrag(errLblDifferenzRechnungsbetrag);
        semesterrechnungenSuchenController.setBtnSuchen(btnSuchen);
        semesterrechnungenSuchenController.setBtnAbbrechen(btnAbbrechen);
        semesterrechnungenSuchenController.addZurueckListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onZurueck();
            }
        });
    }

    private void createUIComponents() {
        spinnerSemester = new JSpinner();
        comboBoxSemesterrechnungCode = new JComboBox<>();
        comboBoxStipendium = new JComboBox<>();
    }

    private void onZurueck() {
        nextPanelListener.actionPerformed(new ActionEvent(new Object[]{$$$getRootComponent$$$(), "Semesterrechnungen suchen", Boolean.TRUE}, ActionEvent.ACTION_PERFORMED, "Zurück zu Schüler suchen"));
    }

    public void addCloseListener(ActionListener actionListener) {
        semesterrechnungenSuchenController.addCloseListener(actionListener);
    }

    public void addNextPanelListener(ActionListener nextPanelListener) {
        this.nextPanelListener = nextPanelListener;
        semesterrechnungenSuchenController.addNextPanelListener(nextPanelListener);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, BorderLayout.CENTER);
        titelPanel = new JPanel();
        titelPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 20, 10);
        panel2.add(titelPanel, gbc);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 36));
        label1.setText("Semesterrechnungen suchen");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        titelPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        titelPanel.add(spacer1, gbc);
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panel2.add(buttonPanel, gbc);
        btnSuchen = new JButton();
        btnSuchen.setMaximumSize(new Dimension(114, 29));
        btnSuchen.setMinimumSize(new Dimension(114, 29));
        btnSuchen.setPreferredSize(new Dimension(114, 29));
        btnSuchen.setText("Suchen");
        btnSuchen.setMnemonic('S');
        btnSuchen.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(btnSuchen, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttonPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttonPanel.add(spacer4, gbc);
        btnAbbrechen = new JButton();
        btnAbbrechen.setMaximumSize(new Dimension(114, 29));
        btnAbbrechen.setMinimumSize(new Dimension(114, 29));
        btnAbbrechen.setPreferredSize(new Dimension(114, 29));
        btnAbbrechen.setText("Abbrechen");
        btnAbbrechen.setMnemonic('A');
        btnAbbrechen.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(btnAbbrechen, gbc);
        datenPanel = new JPanel();
        datenPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(datenPanel, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        datenPanel.add(scrollPane1, gbc);
        suchenPanel = new JPanel();
        suchenPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        scrollPane1.setViewportView(suchenPanel);
        leftPanel = new JPanel();
        leftPanel.setLayout(new GridBagLayout());
        suchenPanel.add(leftPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        semesterPanel = new JPanel();
        semesterPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 10, 0);
        leftPanel.add(semesterPanel, gbc);
        semesterPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Schuljahr / Semester", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(semesterPanel.getFont().getName(), Font.BOLD, semesterPanel.getFont().getSize())));
        final JLabel label2 = new JLabel();
        label2.setText("Schuljahr, Semester");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        semesterPanel.add(label2, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        semesterPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        semesterPanel.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        semesterPanel.add(spacer7, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        semesterPanel.add(spinnerSemester, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        semesterPanel.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        semesterPanel.add(spacer9, gbc);
        namePanel = new JPanel();
        namePanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        leftPanel.add(namePanel, gbc);
        namePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Name", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(namePanel.getFont().getName(), Font.BOLD, namePanel.getFont().getSize())));
        final JLabel label3 = new JLabel();
        label3.setText("Nachname");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        namePanel.add(label3, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        namePanel.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        namePanel.add(spacer11, gbc);
        txtNachname = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        namePanel.add(txtNachname, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        namePanel.add(spacer12, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        namePanel.add(spacer13, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        namePanel.add(spacer14, gbc);
        errLblNachname = new JLabel();
        errLblNachname.setText("errLblNachname");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        namePanel.add(errLblNachname, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Vorname");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        namePanel.add(label4, gbc);
        final JPanel spacer15 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        namePanel.add(spacer15, gbc);
        txtVorname = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        namePanel.add(txtVorname, gbc);
        errLblVorname = new JLabel();
        errLblVorname.setText("errLblVorname");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        namePanel.add(errLblVorname, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Rolle");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        namePanel.add(label5, gbc);
        final JPanel spacer16 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        namePanel.add(spacer16, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.BOTH;
        namePanel.add(panel3, gbc);
        radioBtnRechnungsempfaenger = new JRadioButton();
        radioBtnRechnungsempfaenger.setText("Rechnungsempfänger");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel3.add(radioBtnRechnungsempfaenger, gbc);
        final JPanel spacer17 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer17, gbc);
        radioBtnSchueler = new JRadioButton();
        radioBtnSchueler.setText("Schüler");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel3.add(radioBtnSchueler, gbc);
        radioBtnEltern = new JRadioButton();
        radioBtnEltern.setText("Eltern");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel3.add(radioBtnEltern, gbc);
        radioBtnRolleAlle = new JRadioButton();
        radioBtnRolleAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(radioBtnRolleAlle, gbc);
        codePanel = new JPanel();
        codePanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        leftPanel.add(codePanel, gbc);
        codePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Semesterrechnung-Code", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(codePanel.getFont().getName(), Font.BOLD, codePanel.getFont().getSize())));
        final JLabel label6 = new JLabel();
        label6.setText("Code");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridheight = 2;
        gbc.anchor = GridBagConstraints.WEST;
        codePanel.add(label6, gbc);
        final JPanel spacer18 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codePanel.add(spacer18, gbc);
        final JPanel spacer19 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        codePanel.add(spacer19, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codePanel.add(comboBoxSemesterrechnungCode, gbc);
        final JPanel spacer20 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        codePanel.add(spacer20, gbc);
        final JPanel spacer21 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        codePanel.add(spacer21, gbc);
        final JPanel spacer22 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        codePanel.add(spacer22, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        codePanel.add(panel4, gbc);
        radioBtnSemesterrechnungCodeJa = new JRadioButton();
        radioBtnSemesterrechnungCodeJa.setText("ja");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnSemesterrechnungCodeJa, gbc);
        radioBtnSemesterrechnungCodeNein = new JRadioButton();
        radioBtnSemesterrechnungCodeNein.setText("nein");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel4.add(radioBtnSemesterrechnungCodeNein, gbc);
        radioBtnSemesterrechnungCodeAlle = new JRadioButton();
        radioBtnSemesterrechnungCodeAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel4.add(radioBtnSemesterrechnungCodeAlle, gbc);
        final JPanel spacer23 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(spacer23, gbc);
        stipendiumGratiskindPanel = new JPanel();
        stipendiumGratiskindPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        leftPanel.add(stipendiumGratiskindPanel, gbc);
        stipendiumGratiskindPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Stipendium / Gratiskinder", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(stipendiumGratiskindPanel.getFont().getName(), Font.BOLD, stipendiumGratiskindPanel.getFont().getSize())));
        final JLabel label7 = new JLabel();
        label7.setText("Stipendium");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridheight = 2;
        gbc.anchor = GridBagConstraints.WEST;
        stipendiumGratiskindPanel.add(label7, gbc);
        final JPanel spacer24 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stipendiumGratiskindPanel.add(spacer24, gbc);
        final JPanel spacer25 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        stipendiumGratiskindPanel.add(spacer25, gbc);
        final JPanel spacer26 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stipendiumGratiskindPanel.add(spacer26, gbc);
        final JPanel spacer27 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        stipendiumGratiskindPanel.add(spacer27, gbc);
        final JPanel spacer28 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        stipendiumGratiskindPanel.add(spacer28, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        stipendiumGratiskindPanel.add(comboBoxStipendium, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Gratiskinder");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        stipendiumGratiskindPanel.add(label8, gbc);
        final JPanel spacer29 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        stipendiumGratiskindPanel.add(spacer29, gbc);
        checkBoxGratiskinder = new JCheckBox();
        checkBoxGratiskinder.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        stipendiumGratiskindPanel.add(checkBoxGratiskinder, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        stipendiumGratiskindPanel.add(panel5, gbc);
        radioBtnStipendiumJa = new JRadioButton();
        radioBtnStipendiumJa.setText("ja");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel5.add(radioBtnStipendiumJa, gbc);
        radioBtnStipendiumNein = new JRadioButton();
        radioBtnStipendiumNein.setText("nein");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel5.add(radioBtnStipendiumNein, gbc);
        radioBtnStipendiumAlle = new JRadioButton();
        radioBtnStipendiumAlle.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel5.add(radioBtnStipendiumAlle, gbc);
        final JPanel spacer30 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel5.add(spacer30, gbc);
        differenzPanel = new JPanel();
        differenzPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        leftPanel.add(differenzPanel, gbc);
        differenzPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Differenz Nachrechnung - Vorrechnung", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(differenzPanel.getFont().getName(), Font.BOLD, differenzPanel.getFont().getSize())));
        final JPanel spacer31 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        differenzPanel.add(spacer31, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Differenz Rechnungsbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        differenzPanel.add(label9, gbc);
        txtDifferenzRechnungsbetrag = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        differenzPanel.add(txtDifferenzRechnungsbetrag, gbc);
        errLblDifferenzRechnungsbetrag = new JLabel();
        errLblDifferenzRechnungsbetrag.setText("errLblDifferenzRechnungsbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        differenzPanel.add(errLblDifferenzRechnungsbetrag, gbc);
        final JPanel spacer32 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        differenzPanel.add(spacer32, gbc);
        final JPanel spacer33 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        differenzPanel.add(spacer33, gbc);
        final JPanel spacer34 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        differenzPanel.add(spacer34, gbc);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        differenzPanel.add(panel6, gbc);
        radioBtnDifferenzRechnungsbetragGleich = new JRadioButton();
        radioBtnDifferenzRechnungsbetragGleich.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel6.add(radioBtnDifferenzRechnungsbetragGleich, gbc);
        radioBtnDifferenzRechnungsbetragKleiner = new JRadioButton();
        radioBtnDifferenzRechnungsbetragKleiner.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel6.add(radioBtnDifferenzRechnungsbetragKleiner, gbc);
        radioBtnDifferenzRechnungsbetragGroesser = new JRadioButton();
        radioBtnDifferenzRechnungsbetragGroesser.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel6.add(radioBtnDifferenzRechnungsbetragGroesser, gbc);
        final JPanel spacer35 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(spacer35, gbc);
        final JPanel spacer36 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        differenzPanel.add(spacer36, gbc);
        final JPanel spacer37 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        differenzPanel.add(spacer37, gbc);
        rightPanel = new JPanel();
        rightPanel.setLayout(new GridBagLayout());
        suchenPanel.add(rightPanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        vorrechnungPanel = new JPanel();
        vorrechnungPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 10);
        rightPanel.add(vorrechnungPanel, gbc);
        vorrechnungPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Vorrechnung", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(vorrechnungPanel.getFont().getName(), Font.BOLD, vorrechnungPanel.getFont().getSize())));
        final JLabel label10 = new JLabel();
        label10.setText("Wochenbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(label10, gbc);
        txtWochenbetragVorrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vorrechnungPanel.add(txtWochenbetragVorrechnung, gbc);
        errLblWochenbetragVorrechnung = new JLabel();
        errLblWochenbetragVorrechnung.setText("errLblWochenbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(errLblWochenbetragVorrechnung, gbc);
        final JLabel label11 = new JLabel();
        label11.setText("Rechnungsbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(label11, gbc);
        txtRechnungsbetragVorrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vorrechnungPanel.add(txtRechnungsbetragVorrechnung, gbc);
        errLblRechnungsbetragVorrechnung = new JLabel();
        errLblRechnungsbetragVorrechnung.setText("errLblRechnungsbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 10;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(errLblRechnungsbetragVorrechnung, gbc);
        txtRechnungsdatumVorrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vorrechnungPanel.add(txtRechnungsdatumVorrechnung, gbc);
        errLblRechnungsdatumVorrechnung = new JLabel();
        errLblRechnungsdatumVorrechnung.setText("errLblRechnungsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(errLblRechnungsdatumVorrechnung, gbc);
        final JLabel label12 = new JLabel();
        label12.setText("Rechnungsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.gridheight = 3;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(label12, gbc);
        final JLabel label13 = new JLabel();
        label13.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(label13, gbc);
        final JPanel spacer38 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vorrechnungPanel.add(spacer38, gbc);
        final JPanel spacer39 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vorrechnungPanel.add(spacer39, gbc);
        final JPanel spacer40 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        vorrechnungPanel.add(spacer40, gbc);
        final JLabel label14 = new JLabel();
        label14.setText("Ermässigung");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(label14, gbc);
        txtErmaessigungVorrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vorrechnungPanel.add(txtErmaessigungVorrechnung, gbc);
        final JPanel spacer41 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        vorrechnungPanel.add(spacer41, gbc);
        final JLabel label15 = new JLabel();
        label15.setText("Zuschlag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(label15, gbc);
        txtZuschlagVorrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vorrechnungPanel.add(txtZuschlagVorrechnung, gbc);
        errLblZuschlagVorrechnung = new JLabel();
        errLblZuschlagVorrechnung.setText("errLblZuschlag");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(errLblZuschlagVorrechnung, gbc);
        final JPanel spacer42 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        vorrechnungPanel.add(spacer42, gbc);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        vorrechnungPanel.add(panel7, gbc);
        radioBtnAmVorrechnung = new JRadioButton();
        radioBtnAmVorrechnung.setText("am");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel7.add(radioBtnAmVorrechnung, gbc);
        radioBtnVorVorrechnung = new JRadioButton();
        radioBtnVorVorrechnung.setText("vor");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel7.add(radioBtnVorVorrechnung, gbc);
        radioBtnNachVorrechnung = new JRadioButton();
        radioBtnNachVorrechnung.setText("nach");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel7.add(radioBtnNachVorrechnung, gbc);
        final JPanel spacer43 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel7.add(spacer43, gbc);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.BOTH;
        vorrechnungPanel.add(panel8, gbc);
        radioBtnGleichErmaessigungVorrechnung = new JRadioButton();
        radioBtnGleichErmaessigungVorrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel8.add(radioBtnGleichErmaessigungVorrechnung, gbc);
        final JPanel spacer44 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel8.add(spacer44, gbc);
        radioBtnKleinerErmaessigungVorrechnung = new JRadioButton();
        radioBtnKleinerErmaessigungVorrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel8.add(radioBtnKleinerErmaessigungVorrechnung, gbc);
        radioBtnGroesserErmaessigungVorrechnung = new JRadioButton();
        radioBtnGroesserErmaessigungVorrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel8.add(radioBtnGroesserErmaessigungVorrechnung, gbc);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.BOTH;
        vorrechnungPanel.add(panel9, gbc);
        radioBtnGleichZuschlagVorrechnung = new JRadioButton();
        radioBtnGleichZuschlagVorrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel9.add(radioBtnGleichZuschlagVorrechnung, gbc);
        radioBtnKleinerZuschlagVorrechnung = new JRadioButton();
        radioBtnKleinerZuschlagVorrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel9.add(radioBtnKleinerZuschlagVorrechnung, gbc);
        radioBtnGroesserZuschlagVorrechnung = new JRadioButton();
        radioBtnGroesserZuschlagVorrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel9.add(radioBtnGroesserZuschlagVorrechnung, gbc);
        final JPanel spacer45 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel9.add(spacer45, gbc);
        final JPanel panel10 = new JPanel();
        panel10.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.BOTH;
        vorrechnungPanel.add(panel10, gbc);
        radioBtnGleichWochenbetragVorrechnung = new JRadioButton();
        radioBtnGleichWochenbetragVorrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel10.add(radioBtnGleichWochenbetragVorrechnung, gbc);
        radioBtnKleinerWochenbetragVorrechnung = new JRadioButton();
        radioBtnKleinerWochenbetragVorrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel10.add(radioBtnKleinerWochenbetragVorrechnung, gbc);
        radioBtnGroesserWochenbetragVorrechnung = new JRadioButton();
        radioBtnGroesserWochenbetragVorrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel10.add(radioBtnGroesserWochenbetragVorrechnung, gbc);
        final JPanel spacer46 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel10.add(spacer46, gbc);
        final JPanel panel11 = new JPanel();
        panel11.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.BOTH;
        vorrechnungPanel.add(panel11, gbc);
        radioBtnGleichRechnungsbetragVorrechnung = new JRadioButton();
        radioBtnGleichRechnungsbetragVorrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel11.add(radioBtnGleichRechnungsbetragVorrechnung, gbc);
        radioBtnKleinerRechnungsbetragVorrechnung = new JRadioButton();
        radioBtnKleinerRechnungsbetragVorrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel11.add(radioBtnKleinerRechnungsbetragVorrechnung, gbc);
        radioBtnGroesserRechnungsbetragVorrechnung = new JRadioButton();
        radioBtnGroesserRechnungsbetragVorrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel11.add(radioBtnGroesserRechnungsbetragVorrechnung, gbc);
        final JPanel spacer47 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel11.add(spacer47, gbc);
        final JPanel spacer48 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        vorrechnungPanel.add(spacer48, gbc);
        errLblErmaessigungVorrechnung = new JLabel();
        errLblErmaessigungVorrechnung.setText("errLblErmaessigung");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(errLblErmaessigungVorrechnung, gbc);
        final JPanel spacer49 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        vorrechnungPanel.add(spacer49, gbc);
        final JPanel spacer50 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        vorrechnungPanel.add(spacer50, gbc);
        final JPanel spacer51 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        vorrechnungPanel.add(spacer51, gbc);
        final JPanel spacer52 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        vorrechnungPanel.add(spacer52, gbc);
        final JPanel panel12 = new JPanel();
        panel12.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 15;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        vorrechnungPanel.add(panel12, gbc);
        radioBtnSechsJahresRabattJaVorrechnung = new JRadioButton();
        radioBtnSechsJahresRabattJaVorrechnung.setText("ja");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel12.add(radioBtnSechsJahresRabattJaVorrechnung, gbc);
        radioBtnSechsJahresRabattNeinVorrechnung = new JRadioButton();
        radioBtnSechsJahresRabattNeinVorrechnung.setText("nein");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel12.add(radioBtnSechsJahresRabattNeinVorrechnung, gbc);
        radioBtnSechsJahresRabattAlleVorrechnung = new JRadioButton();
        radioBtnSechsJahresRabattAlleVorrechnung.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel12.add(radioBtnSechsJahresRabattAlleVorrechnung, gbc);
        final JPanel spacer53 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel12.add(spacer53, gbc);
        final JLabel label16 = new JLabel();
        label16.setText("6-Jahres-Rabatt");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 15;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(label16, gbc);
        final JPanel spacer54 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 16;
        gbc.fill = GridBagConstraints.VERTICAL;
        vorrechnungPanel.add(spacer54, gbc);
        final JPanel panel13 = new JPanel();
        panel13.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        vorrechnungPanel.add(panel13, gbc);
        radioBtnRechnungsdatumGesetztVorrechnung = new JRadioButton();
        radioBtnRechnungsdatumGesetztVorrechnung.setText("gesetzt");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel13.add(radioBtnRechnungsdatumGesetztVorrechnung, gbc);
        radioBtnRechnungsdatumNichtGesetztVorrechnung = new JRadioButton();
        radioBtnRechnungsdatumNichtGesetztVorrechnung.setText("nicht gesetzt");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel13.add(radioBtnRechnungsdatumNichtGesetztVorrechnung, gbc);
        radioBtnRechnungsdatumGesetztAlleVorrechnung = new JRadioButton();
        radioBtnRechnungsdatumGesetztAlleVorrechnung.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel13.add(radioBtnRechnungsdatumGesetztAlleVorrechnung, gbc);
        final JPanel spacer55 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel13.add(spacer55, gbc);
        final JLabel label17 = new JLabel();
        label17.setText("Restbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 13;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(label17, gbc);
        final JPanel spacer56 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.VERTICAL;
        vorrechnungPanel.add(spacer56, gbc);
        final JPanel panel14 = new JPanel();
        panel14.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 13;
        gbc.fill = GridBagConstraints.BOTH;
        vorrechnungPanel.add(panel14, gbc);
        radioBtnGleichRestbetragVorrechnung = new JRadioButton();
        radioBtnGleichRestbetragVorrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel14.add(radioBtnGleichRestbetragVorrechnung, gbc);
        radioBtnKleinerRestbetragVorrechnung = new JRadioButton();
        radioBtnKleinerRestbetragVorrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel14.add(radioBtnKleinerRestbetragVorrechnung, gbc);
        radioBtnGroesserRestbetragVorrechnung = new JRadioButton();
        radioBtnGroesserRestbetragVorrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel14.add(radioBtnGroesserRestbetragVorrechnung, gbc);
        final JPanel spacer57 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel14.add(spacer57, gbc);
        errLblRestbetragVorrechnung = new JLabel();
        errLblRestbetragVorrechnung.setText("errLblRestbetragVorrechnung");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 12;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        vorrechnungPanel.add(errLblRestbetragVorrechnung, gbc);
        txtRestbetragVorrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vorrechnungPanel.add(txtRestbetragVorrechnung, gbc);
        nachrechnungPanel = new JPanel();
        nachrechnungPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 10, 10);
        rightPanel.add(nachrechnungPanel, gbc);
        nachrechnungPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Nachrechnung", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(nachrechnungPanel.getFont().getName(), Font.BOLD, nachrechnungPanel.getFont().getSize())));
        final JLabel label18 = new JLabel();
        label18.setText("Rechnungsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridheight = 3;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(label18, gbc);
        final JPanel spacer58 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        nachrechnungPanel.add(spacer58, gbc);
        final JPanel spacer59 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        nachrechnungPanel.add(spacer59, gbc);
        final JPanel spacer60 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        nachrechnungPanel.add(spacer60, gbc);
        final JPanel panel15 = new JPanel();
        panel15.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        nachrechnungPanel.add(panel15, gbc);
        radioBtnAmNachrechnung = new JRadioButton();
        radioBtnAmNachrechnung.setText("am");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel15.add(radioBtnAmNachrechnung, gbc);
        radioBtnVorNachrechnung = new JRadioButton();
        radioBtnVorNachrechnung.setText("vor");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel15.add(radioBtnVorNachrechnung, gbc);
        radioBtnNachNachrechnung = new JRadioButton();
        radioBtnNachNachrechnung.setText("nach");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel15.add(radioBtnNachNachrechnung, gbc);
        final JPanel spacer61 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel15.add(spacer61, gbc);
        txtRechnungsdatumNachrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        nachrechnungPanel.add(txtRechnungsdatumNachrechnung, gbc);
        final JPanel spacer62 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        nachrechnungPanel.add(spacer62, gbc);
        final JPanel spacer63 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        nachrechnungPanel.add(spacer63, gbc);
        final JPanel spacer64 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        nachrechnungPanel.add(spacer64, gbc);
        errLblRechnungsdatumNachrechnung = new JLabel();
        errLblRechnungsdatumNachrechnung.setText("errLblRechnungsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 7;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(errLblRechnungsdatumNachrechnung, gbc);
        final JLabel label19 = new JLabel();
        label19.setText("Ermässigung");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(label19, gbc);
        txtErmaessigungNachrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 5;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        nachrechnungPanel.add(txtErmaessigungNachrechnung, gbc);
        final JPanel panel16 = new JPanel();
        panel16.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        nachrechnungPanel.add(panel16, gbc);
        radioBtnGleichErmaessigungNachrechnung = new JRadioButton();
        radioBtnGleichErmaessigungNachrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel16.add(radioBtnGleichErmaessigungNachrechnung, gbc);
        radioBtnKleinerErmaessigungNachrechnung = new JRadioButton();
        radioBtnKleinerErmaessigungNachrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel16.add(radioBtnKleinerErmaessigungNachrechnung, gbc);
        radioBtnGroesserErmaessigungNachrechnung = new JRadioButton();
        radioBtnGroesserErmaessigungNachrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel16.add(radioBtnGroesserErmaessigungNachrechnung, gbc);
        final JPanel spacer65 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel16.add(spacer65, gbc);
        errLblErmaessigungNachrechnung = new JLabel();
        errLblErmaessigungNachrechnung.setText("errLblErmaessigung");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.gridwidth = 7;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(errLblErmaessigungNachrechnung, gbc);
        final JPanel spacer66 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        nachrechnungPanel.add(spacer66, gbc);
        final JLabel label20 = new JLabel();
        label20.setText("Zuschlag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(label20, gbc);
        txtZuschlagNachrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 7;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        nachrechnungPanel.add(txtZuschlagNachrechnung, gbc);
        final JPanel panel17 = new JPanel();
        panel17.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        nachrechnungPanel.add(panel17, gbc);
        radioBtnGleichZuschlagNachrechnung = new JRadioButton();
        radioBtnGleichZuschlagNachrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel17.add(radioBtnGleichZuschlagNachrechnung, gbc);
        radioBtnKleinerZuschlagNachrechnung = new JRadioButton();
        radioBtnKleinerZuschlagNachrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel17.add(radioBtnKleinerZuschlagNachrechnung, gbc);
        radioBtnGroesserZuschlagNachrechnung = new JRadioButton();
        radioBtnGroesserZuschlagNachrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel17.add(radioBtnGroesserZuschlagNachrechnung, gbc);
        final JPanel spacer67 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel17.add(spacer67, gbc);
        errLblZuschlagNachrechnung = new JLabel();
        errLblZuschlagNachrechnung.setText("errLblZuschlag");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.gridwidth = 7;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(errLblZuschlagNachrechnung, gbc);
        final JPanel spacer68 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        nachrechnungPanel.add(spacer68, gbc);
        final JLabel label21 = new JLabel();
        label21.setText("Anzahl Wochen");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(label21, gbc);
        txtAnzahlWochenNachrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 9;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        nachrechnungPanel.add(txtAnzahlWochenNachrechnung, gbc);
        final JPanel panel18 = new JPanel();
        panel18.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        nachrechnungPanel.add(panel18, gbc);
        radioBtnGleichAnzahlWochenNachrechnung = new JRadioButton();
        radioBtnGleichAnzahlWochenNachrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel18.add(radioBtnGleichAnzahlWochenNachrechnung, gbc);
        radioBtnKleinerAnzahlWochenNachrechnung = new JRadioButton();
        radioBtnKleinerAnzahlWochenNachrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel18.add(radioBtnKleinerAnzahlWochenNachrechnung, gbc);
        radioBtnGroesserAnzahlWochenNachrechnung = new JRadioButton();
        radioBtnGroesserAnzahlWochenNachrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel18.add(radioBtnGroesserAnzahlWochenNachrechnung, gbc);
        final JPanel spacer69 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel18.add(spacer69, gbc);
        errLblAnzahlWochenNachrechnung = new JLabel();
        errLblAnzahlWochenNachrechnung.setText("errLblAnzahlWochenNachrechnung");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.gridwidth = 7;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(errLblAnzahlWochenNachrechnung, gbc);
        final JPanel spacer70 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        nachrechnungPanel.add(spacer70, gbc);
        final JLabel label22 = new JLabel();
        label22.setText("Wochenbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(label22, gbc);
        txtWochenbetragNachrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 11;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        nachrechnungPanel.add(txtWochenbetragNachrechnung, gbc);
        final JPanel panel19 = new JPanel();
        panel19.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        nachrechnungPanel.add(panel19, gbc);
        radioBtnGleichWochenbetragNachrechnung = new JRadioButton();
        radioBtnGleichWochenbetragNachrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel19.add(radioBtnGleichWochenbetragNachrechnung, gbc);
        radioBtnKleinerWochenbetragNachrechnung = new JRadioButton();
        radioBtnKleinerWochenbetragNachrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel19.add(radioBtnKleinerWochenbetragNachrechnung, gbc);
        radioBtnGroesserWochenbetragNachrechnung = new JRadioButton();
        radioBtnGroesserWochenbetragNachrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel19.add(radioBtnGroesserWochenbetragNachrechnung, gbc);
        final JPanel spacer71 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel19.add(spacer71, gbc);
        errLblWochenbetragNachrechnung = new JLabel();
        errLblWochenbetragNachrechnung.setText("errLblWochenbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.gridwidth = 7;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(errLblWochenbetragNachrechnung, gbc);
        final JPanel spacer72 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.VERTICAL;
        nachrechnungPanel.add(spacer72, gbc);
        final JLabel label23 = new JLabel();
        label23.setText("Rechnungsbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(label23, gbc);
        txtRechnungsbetragNachrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 13;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        nachrechnungPanel.add(txtRechnungsbetragNachrechnung, gbc);
        final JPanel panel20 = new JPanel();
        panel20.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        nachrechnungPanel.add(panel20, gbc);
        radioBtnGleichRechnungsbetragNachrechnung = new JRadioButton();
        radioBtnGleichRechnungsbetragNachrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel20.add(radioBtnGleichRechnungsbetragNachrechnung, gbc);
        radioBtnKleinerRechnungsbetragNachrechnung = new JRadioButton();
        radioBtnKleinerRechnungsbetragNachrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel20.add(radioBtnKleinerRechnungsbetragNachrechnung, gbc);
        radioBtnGroesserRechnungsbetragNachrechnung = new JRadioButton();
        radioBtnGroesserRechnungsbetragNachrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel20.add(radioBtnGroesserRechnungsbetragNachrechnung, gbc);
        final JPanel spacer73 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel20.add(spacer73, gbc);
        errLblRechnungsbetragNachrechnung = new JLabel();
        errLblRechnungsbetragNachrechnung.setText("errLblRechnungsbetragNachrechnung");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.gridwidth = 7;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(errLblRechnungsbetragNachrechnung, gbc);
        final JPanel spacer74 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.VERTICAL;
        nachrechnungPanel.add(spacer74, gbc);
        final JLabel label24 = new JLabel();
        label24.setText("6-Jahres-Rabatt");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 17;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(label24, gbc);
        final JPanel spacer75 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 18;
        gbc.fill = GridBagConstraints.VERTICAL;
        nachrechnungPanel.add(spacer75, gbc);
        final JPanel panel21 = new JPanel();
        panel21.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 17;
        gbc.gridwidth = 7;
        gbc.fill = GridBagConstraints.BOTH;
        nachrechnungPanel.add(panel21, gbc);
        radioBtnSechsJahresRabattJaNachrechnung = new JRadioButton();
        radioBtnSechsJahresRabattJaNachrechnung.setText("ja");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel21.add(radioBtnSechsJahresRabattJaNachrechnung, gbc);
        radioBtnSechsJahresRabattNeinNachrechnung = new JRadioButton();
        radioBtnSechsJahresRabattNeinNachrechnung.setText("nein");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel21.add(radioBtnSechsJahresRabattNeinNachrechnung, gbc);
        radioBtnSechsJahresRabattAlleNachrechnung = new JRadioButton();
        radioBtnSechsJahresRabattAlleNachrechnung.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel21.add(radioBtnSechsJahresRabattAlleNachrechnung, gbc);
        final JPanel spacer76 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel21.add(spacer76, gbc);
        final JPanel panel22 = new JPanel();
        panel22.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 7;
        gbc.fill = GridBagConstraints.BOTH;
        nachrechnungPanel.add(panel22, gbc);
        radioBtnRechnungsdatumGesetztNachrechnung = new JRadioButton();
        radioBtnRechnungsdatumGesetztNachrechnung.setText("gesetzt");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel22.add(radioBtnRechnungsdatumGesetztNachrechnung, gbc);
        radioBtnRechnungsdatumNichtGesetztNachrechnung = new JRadioButton();
        radioBtnRechnungsdatumNichtGesetztNachrechnung.setText("nicht gesetzt");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel22.add(radioBtnRechnungsdatumNichtGesetztNachrechnung, gbc);
        radioBtnRechnungsdatumGesetztAlleNachrechnung = new JRadioButton();
        radioBtnRechnungsdatumGesetztAlleNachrechnung.setText("alle");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel22.add(radioBtnRechnungsdatumGesetztAlleNachrechnung, gbc);
        final JPanel spacer77 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel22.add(spacer77, gbc);
        final JLabel label25 = new JLabel();
        label25.setText("Restbetrag");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 15;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(label25, gbc);
        final JPanel spacer78 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 16;
        gbc.fill = GridBagConstraints.VERTICAL;
        nachrechnungPanel.add(spacer78, gbc);
        errLblRestbetragNachrechnung = new JLabel();
        errLblRestbetragNachrechnung.setText("errLblRestbetragNachrechnung");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 14;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        nachrechnungPanel.add(errLblRestbetragNachrechnung, gbc);
        txtRestbetragNachrechnung = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 15;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        nachrechnungPanel.add(txtRestbetragNachrechnung, gbc);
        final JPanel panel23 = new JPanel();
        panel23.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 15;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        nachrechnungPanel.add(panel23, gbc);
        radioBtnGleichRestbetragNachrechnung = new JRadioButton();
        radioBtnGleichRestbetragNachrechnung.setText("gleich");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel23.add(radioBtnGleichRestbetragNachrechnung, gbc);
        radioBtnKleinerRestbetragNachrechnung = new JRadioButton();
        radioBtnKleinerRestbetragNachrechnung.setText("kleiner");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 5);
        panel23.add(radioBtnKleinerRestbetragNachrechnung, gbc);
        radioBtnGroesserRestbetragNachrechnung = new JRadioButton();
        radioBtnGroesserRestbetragNachrechnung.setText("grösser");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel23.add(radioBtnGroesserRestbetragNachrechnung, gbc);
        final JPanel spacer79 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel23.add(spacer79, gbc);
        label2.setLabelFor(spinnerSemester);
        label3.setLabelFor(txtNachname);
        label4.setLabelFor(txtVorname);
        label6.setLabelFor(comboBoxSemesterrechnungCode);
        label7.setLabelFor(comboBoxStipendium);
        label9.setLabelFor(txtDifferenzRechnungsbetrag);
        label10.setLabelFor(txtWochenbetragVorrechnung);
        label11.setLabelFor(txtRechnungsbetragVorrechnung);
        label12.setLabelFor(txtRechnungsdatumVorrechnung);
        label14.setLabelFor(txtErmaessigungVorrechnung);
        label15.setLabelFor(txtZuschlagVorrechnung);
        label17.setLabelFor(txtRestbetragVorrechnung);
        label18.setLabelFor(txtRechnungsdatumNachrechnung);
        label19.setLabelFor(txtErmaessigungNachrechnung);
        label20.setLabelFor(txtZuschlagNachrechnung);
        label21.setLabelFor(txtAnzahlWochenNachrechnung);
        label22.setLabelFor(txtWochenbetragNachrechnung);
        label23.setLabelFor(txtRechnungsbetragNachrechnung);
        label25.setLabelFor(txtRestbetragNachrechnung);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnRechnungsempfaenger);
        buttonGroup.add(radioBtnSchueler);
        buttonGroup.add(radioBtnEltern);
        buttonGroup.add(radioBtnRolleAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnDifferenzRechnungsbetragGleich);
        buttonGroup.add(radioBtnDifferenzRechnungsbetragKleiner);
        buttonGroup.add(radioBtnDifferenzRechnungsbetragGroesser);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichWochenbetragVorrechnung);
        buttonGroup.add(radioBtnKleinerWochenbetragVorrechnung);
        buttonGroup.add(radioBtnGroesserWochenbetragVorrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichRechnungsbetragVorrechnung);
        buttonGroup.add(radioBtnKleinerRechnungsbetragVorrechnung);
        buttonGroup.add(radioBtnGroesserRechnungsbetragVorrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnAmVorrechnung);
        buttonGroup.add(radioBtnVorVorrechnung);
        buttonGroup.add(radioBtnNachVorrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnRechnungsdatumGesetztVorrechnung);
        buttonGroup.add(radioBtnRechnungsdatumNichtGesetztVorrechnung);
        buttonGroup.add(radioBtnRechnungsdatumGesetztAlleVorrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichErmaessigungVorrechnung);
        buttonGroup.add(radioBtnKleinerErmaessigungVorrechnung);
        buttonGroup.add(radioBtnGroesserErmaessigungVorrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichZuschlagVorrechnung);
        buttonGroup.add(radioBtnKleinerZuschlagVorrechnung);
        buttonGroup.add(radioBtnGroesserZuschlagVorrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnAmNachrechnung);
        buttonGroup.add(radioBtnVorNachrechnung);
        buttonGroup.add(radioBtnNachNachrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichErmaessigungNachrechnung);
        buttonGroup.add(radioBtnKleinerErmaessigungNachrechnung);
        buttonGroup.add(radioBtnGroesserErmaessigungNachrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichZuschlagNachrechnung);
        buttonGroup.add(radioBtnKleinerZuschlagNachrechnung);
        buttonGroup.add(radioBtnGroesserZuschlagNachrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichAnzahlWochenNachrechnung);
        buttonGroup.add(radioBtnKleinerAnzahlWochenNachrechnung);
        buttonGroup.add(radioBtnGroesserAnzahlWochenNachrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichWochenbetragNachrechnung);
        buttonGroup.add(radioBtnKleinerWochenbetragNachrechnung);
        buttonGroup.add(radioBtnGroesserWochenbetragNachrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichRechnungsbetragNachrechnung);
        buttonGroup.add(radioBtnKleinerRechnungsbetragNachrechnung);
        buttonGroup.add(radioBtnGroesserRechnungsbetragNachrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnRechnungsdatumGesetztNachrechnung);
        buttonGroup.add(radioBtnRechnungsdatumNichtGesetztNachrechnung);
        buttonGroup.add(radioBtnRechnungsdatumGesetztAlleNachrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnSechsJahresRabattJaVorrechnung);
        buttonGroup.add(radioBtnSechsJahresRabattNeinVorrechnung);
        buttonGroup.add(radioBtnSechsJahresRabattAlleVorrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnSechsJahresRabattJaNachrechnung);
        buttonGroup.add(radioBtnSechsJahresRabattNeinNachrechnung);
        buttonGroup.add(radioBtnSechsJahresRabattAlleNachrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnSemesterrechnungCodeJa);
        buttonGroup.add(radioBtnSemesterrechnungCodeNein);
        buttonGroup.add(radioBtnSemesterrechnungCodeAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnStipendiumJa);
        buttonGroup.add(radioBtnStipendiumNein);
        buttonGroup.add(radioBtnStipendiumAlle);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichRestbetragNachrechnung);
        buttonGroup.add(radioBtnKleinerRestbetragNachrechnung);
        buttonGroup.add(radioBtnGroesserRestbetragNachrechnung);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnGleichRestbetragVorrechnung);
        buttonGroup.add(radioBtnKleinerRestbetragVorrechnung);
        buttonGroup.add(radioBtnGroesserRestbetragVorrechnung);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
