package ch.metzenthin.svm.ui.components;

import ch.metzenthin.svm.common.SvmContext;
import ch.metzenthin.svm.ui.componentmodel.SemesterrechnungenTableModel;
import ch.metzenthin.svm.ui.control.SemesterrechnungenController;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * @author Martin Schraner
 */
public class SemesterrechnungenPanel {
    private JPanel panel1;
    private JPanel datenPanel;
    private JPanel titelPanel;
    private JPanel semesterrechnungenTablePanel;
    private JPanel btnPanel;
    private JTable semesterrechnungenTable;
    private JButton btnImportieren;
    private JButton btnExportieren;
    private JButton btnRechnungsdatum;
    private JButton btnDetailsBearbeiten;
    private JButton btnLoeschen;
    private JButton btnZurueck;
    private JButton btnAbbrechen;
    private JLabel lblTotal;
    private final SemesterrechnungenController semesterrechnungenController;

    public SemesterrechnungenPanel(SvmContext svmContext, SemesterrechnungenTableModel semesterrechnungenTableModel) {
        $$$setupUI$$$();
        createUIComponents();
        semesterrechnungenController = new SemesterrechnungenController(svmContext, svmContext.getModelFactory().createSemesterrechnungenModel(), semesterrechnungenTableModel);
        semesterrechnungenController.setSemesterrechnungenTable(semesterrechnungenTable);
        semesterrechnungenController.setLblTotal(lblTotal);
        semesterrechnungenController.setBtnDetailsBearbeiten(btnDetailsBearbeiten);
        semesterrechnungenController.setBtnImportieren(btnImportieren);
        semesterrechnungenController.setBtnExportieren(btnExportieren);
        semesterrechnungenController.setBtnRechnungsdatum(btnRechnungsdatum);
        semesterrechnungenController.setBtnLoeschen(btnLoeschen);
        semesterrechnungenController.setBtnZurueck(btnZurueck);
        semesterrechnungenController.setBtnAbbrechen(btnAbbrechen);
    }

    public void addNextPanelListener(ActionListener actionListener) {
        semesterrechnungenController.addNextPanelListener(actionListener);
    }

    public void addCloseListener(ActionListener closeListener) {
        semesterrechnungenController.addCloseListener(closeListener);
    }

    public void addZurueckListener(ActionListener zurueckListener) {
        semesterrechnungenController.addZurueckListener(zurueckListener);
    }

    private void createUIComponents() {
        // JTable mit optimiertem Scroll-Verhalten
        // http://stackoverflow.com/questions/6104916/how-to-make-jtable-both-autoresize-and-horizontall-scrollable
        semesterrechnungenTable = new JTable() {
            @Override
            public boolean getScrollableTracksViewportWidth() {
                return getPreferredSize().width < getParent().getWidth();
            }
        };
        semesterrechnungenTable.setAutoCreateRowSorter(true);
        semesterrechnungenTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        semesterrechnungenTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        final JScrollPane scrollPane = new JScrollPane(semesterrechnungenTable);
        semesterrechnungenTablePanel.add(scrollPane);
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        datenPanel = new JPanel();
        datenPanel.setLayout(new GridBagLayout());
        panel1.add(datenPanel, BorderLayout.CENTER);
        titelPanel = new JPanel();
        titelPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 20, 10);
        datenPanel.add(titelPanel, gbc);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 36));
        label1.setText("Suchresultat");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        titelPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        titelPanel.add(spacer1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 10, 10);
        datenPanel.add(panel2, gbc);
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Semesterrechnungen", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(panel2.getFont().getName(), Font.BOLD, panel2.getFont().getSize())));
        semesterrechnungenTablePanel = new JPanel();
        semesterrechnungenTablePanel.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(semesterrechnungenTablePanel, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer5, gbc);
        lblTotal = new JLabel();
        lblTotal.setText("lblTotal");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(lblTotal, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer6, gbc);
        btnPanel = new JPanel();
        btnPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        datenPanel.add(btnPanel, gbc);
        btnExportieren = new JButton();
        btnExportieren.setMaximumSize(new Dimension(120, 29));
        btnExportieren.setMinimumSize(new Dimension(120, 29));
        btnExportieren.setPreferredSize(new Dimension(120, 29));
        btnExportieren.setText("Exportieren");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(btnExportieren, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        btnPanel.add(spacer7, gbc);
        btnDetailsBearbeiten = new JButton();
        btnDetailsBearbeiten.setMaximumSize(new Dimension(176, 29));
        btnDetailsBearbeiten.setMinimumSize(new Dimension(176, 29));
        btnDetailsBearbeiten.setPreferredSize(new Dimension(176, 29));
        btnDetailsBearbeiten.setText("Details / Bearbeiten");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(btnDetailsBearbeiten, gbc);
        btnZurueck = new JButton();
        btnZurueck.setMaximumSize(new Dimension(114, 29));
        btnZurueck.setMinimumSize(new Dimension(114, 29));
        btnZurueck.setPreferredSize(new Dimension(114, 29));
        btnZurueck.setText("Zurück");
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(btnZurueck, gbc);
        btnAbbrechen = new JButton();
        btnAbbrechen.setMaximumSize(new Dimension(114, 29));
        btnAbbrechen.setMinimumSize(new Dimension(114, 29));
        btnAbbrechen.setPreferredSize(new Dimension(114, 29));
        btnAbbrechen.setText("Abbrechen");
        gbc = new GridBagConstraints();
        gbc.gridx = 12;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 10);
        btnPanel.add(btnAbbrechen, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        btnPanel.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 11;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(spacer11, gbc);
        btnImportieren = new JButton();
        btnImportieren.setMaximumSize(new Dimension(120, 29));
        btnImportieren.setMinimumSize(new Dimension(120, 29));
        btnImportieren.setPreferredSize(new Dimension(120, 29));
        btnImportieren.setText("Importieren");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(btnImportieren, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(spacer12, gbc);
        btnLoeschen = new JButton();
        btnLoeschen.setMaximumSize(new Dimension(120, 29));
        btnLoeschen.setMinimumSize(new Dimension(120, 29));
        btnLoeschen.setPreferredSize(new Dimension(120, 29));
        btnLoeschen.setText("Löschen");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 0, 0);
        btnPanel.add(btnLoeschen, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(spacer13, gbc);
        btnRechnungsdatum = new JButton();
        btnRechnungsdatum.setMaximumSize(new Dimension(158, 29));
        btnRechnungsdatum.setMinimumSize(new Dimension(158, 29));
        btnRechnungsdatum.setPreferredSize(new Dimension(158, 29));
        btnRechnungsdatum.setText("Rechnungsdatum");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(btnRechnungsdatum, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        btnPanel.add(spacer14, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
